// Code generated by protoc-gen-sensitive. DO NOT EDIT.

package v1alpha1

// func (x *GetRequest) Sanitize()            // is not generated as no sensitive fields found
// func (x *GetRequest) LogValue() slog.Value // is not generated as no sensitive fields found

// func (x *GetByNameRequest) Sanitize()            // is not generated as no sensitive fields found
// func (x *GetByNameRequest) LogValue() slog.Value // is not generated as no sensitive fields found

// func (x *DeleteRequest) Sanitize()            // is not generated as no sensitive fields found
// func (x *DeleteRequest) LogValue() slog.Value // is not generated as no sensitive fields found

// func (x *StartRequest) Sanitize()            // is not generated as no sensitive fields found
// func (x *StartRequest) LogValue() slog.Value // is not generated as no sensitive fields found

// func (x *StopRequest) Sanitize()            // is not generated as no sensitive fields found
// func (x *StopRequest) LogValue() slog.Value // is not generated as no sensitive fields found

// func (x *ListRequest) Sanitize()            // is not generated as no sensitive fields found
// func (x *ListRequest) LogValue() slog.Value // is not generated as no sensitive fields found

// func (x *UpdateVersionRequest) Sanitize()            // is not generated as no sensitive fields found
// func (x *UpdateVersionRequest) LogValue() slog.Value // is not generated as no sensitive fields found
