// Code generated by protoc-gen-gosdk. DO NOT EDIT.

package v1

import (
	context "context"
	check_nid "github.com/nebius/gosdk/check-nid"
	conn "github.com/nebius/gosdk/conn"
	iface "github.com/nebius/gosdk/internal/iface"
	iter "github.com/nebius/gosdk/iter"
	operations "github.com/nebius/gosdk/operations"
	grpcheader "github.com/nebius/gosdk/proto/fieldmask/grpcheader"
	v1 "github.com/nebius/gosdk/proto/nebius/ai/v1"
	v11 "github.com/nebius/gosdk/proto/nebius/common/v1"
	grpc "google.golang.org/grpc"
	proto "google.golang.org/protobuf/proto"
	slog "log/slog"
)

func init() {
	conn.ConventionResolverServiceIDToNameMap[EndpointServiceID] = "apps.msp"
}

func (s Services) Endpoint() EndpointService {
	return NewEndpointService(s.sdk)
}

const EndpointServiceID conn.ServiceID = "nebius.ai.v1.EndpointService"

type EndpointService interface {
	Get(context.Context, *v1.GetEndpointRequest, ...grpc.CallOption) (*v1.Endpoint, error)
	GetByName(context.Context, *v1.GetEndpointByNameRequest, ...grpc.CallOption) (*v1.Endpoint, error)
	List(context.Context, *v1.ListEndpointsRequest, ...grpc.CallOption) (*v1.ListEndpointsResponse, error)
	Filter(context.Context, *v1.ListEndpointsRequest, ...grpc.CallOption) iter.Seq2[*v1.Endpoint, error]
	Create(context.Context, *v1.CreateEndpointRequest, ...grpc.CallOption) (operations.Operation, error)
	Delete(context.Context, *v1.DeleteEndpointRequest, ...grpc.CallOption) (operations.Operation, error)
	Update(context.Context, *v1.UpdateEndpointRequest, ...grpc.CallOption) (operations.Operation, error)
	Start(context.Context, *v1.StartEndpointRequest, ...grpc.CallOption) (operations.Operation, error)
	Stop(context.Context, *v1.StopEndpointRequest, ...grpc.CallOption) (operations.Operation, error)
	GetOperation(context.Context, *v11.GetOperationRequest, ...grpc.CallOption) (operations.Operation, error)
	ListOperations(context.Context, *v11.ListOperationsRequest, ...grpc.CallOption) (*v11.ListOperationsResponse, error)
}

type endpointService struct {
	sdk iface.SDKWithParentID
}

func NewEndpointService(sdk iface.SDK) EndpointService {
	return endpointService{
		sdk: iface.WrapSDK(sdk),
	}
}

func (s endpointService) Get(ctx context.Context, request *v1.GetEndpointRequest, opts ...grpc.CallOption) (
	*v1.Endpoint,
	error,
) {
	if logger := s.sdk.GetLogger(); logger != nil {
		for path, warning := range check_nid.CheckMessageFields(request) {
			logger.WarnContext(ctx, warning, slog.String("path", path))
		}
	}
	address, err := s.sdk.Resolve(ctx, EndpointServiceID)
	if err != nil {
		return nil, err
	}
	con, err := s.sdk.Dial(ctx, address)
	if err != nil {
		return nil, err
	}
	return v1.NewEndpointServiceClient(con).Get(ctx, request, opts...)
}

func (s endpointService) GetByName(ctx context.Context, request *v1.GetEndpointByNameRequest, opts ...grpc.CallOption) (
	*v1.Endpoint,
	error,
) {
	if request.GetParentId() == "" {
		if parentID := s.sdk.ParentID(); parentID != "" {
			if check_nid.ValidateNIDString(parentID, nil) == "" {
				request.ParentId = parentID
			}
		}
		if request.GetParentId() == "" {
			if tenantID := s.sdk.TenantID(); tenantID != "" {
				if check_nid.ValidateNIDString(tenantID, nil) == "" {
					request.ParentId = tenantID
				}
			}
		}
	}
	if logger := s.sdk.GetLogger(); logger != nil {
		for path, warning := range check_nid.CheckMessageFields(request) {
			logger.WarnContext(ctx, warning, slog.String("path", path))
		}
	}
	address, err := s.sdk.Resolve(ctx, EndpointServiceID)
	if err != nil {
		return nil, err
	}
	con, err := s.sdk.Dial(ctx, address)
	if err != nil {
		return nil, err
	}
	return v1.NewEndpointServiceClient(con).GetByName(ctx, request, opts...)
}

func (s endpointService) List(ctx context.Context, request *v1.ListEndpointsRequest, opts ...grpc.CallOption) (
	*v1.ListEndpointsResponse,
	error,
) {
	if request.GetParentId() == "" {
		if parentID := s.sdk.ParentID(); parentID != "" {
			if check_nid.ValidateNIDString(parentID, nil) == "" {
				request.ParentId = parentID
			}
		}
		if request.GetParentId() == "" {
			if tenantID := s.sdk.TenantID(); tenantID != "" {
				if check_nid.ValidateNIDString(tenantID, nil) == "" {
					request.ParentId = tenantID
				}
			}
		}
	}
	if logger := s.sdk.GetLogger(); logger != nil {
		for path, warning := range check_nid.CheckMessageFields(request) {
			logger.WarnContext(ctx, warning, slog.String("path", path))
		}
	}
	address, err := s.sdk.Resolve(ctx, EndpointServiceID)
	if err != nil {
		return nil, err
	}
	con, err := s.sdk.Dial(ctx, address)
	if err != nil {
		return nil, err
	}
	return v1.NewEndpointServiceClient(con).List(ctx, request, opts...)
}

func (s endpointService) Filter(ctx context.Context, request *v1.ListEndpointsRequest, opts ...grpc.CallOption) iter.Seq2[*v1.Endpoint, error] {
	req := proto.Clone(request).(*v1.ListEndpointsRequest)
	return func(yield func(*v1.Endpoint, error) bool) {
		for {
			res, err := s.List(ctx, req, opts...)
			if err != nil {
				yield(nil, err)
				return
			}

			for _, item := range res.GetItems() {
				if !yield(item, nil) {
					return
				}
			}

			if res.GetNextPageToken() == "" {
				return
			}

			req.PageToken = res.GetNextPageToken()
		}
	}
}

func (s endpointService) Create(ctx context.Context, request *v1.CreateEndpointRequest, opts ...grpc.CallOption) (
	operations.Operation,
	error,
) {
	var metadataParentTypes []string
	if request.GetMetadata().GetParentId() == "" {
		if tenantID := s.sdk.TenantID(); tenantID != "" {
			if check_nid.ValidateNIDString(tenantID, metadataParentTypes) == "" {
				md := request.GetMetadata()
				if md == nil {
					md = &v11.ResourceMetadata{}
				}
				md.ParentId = tenantID
				request.Metadata = md
			}
		}
		if parentID := s.sdk.ParentID(); parentID != "" {
			if check_nid.ValidateNIDString(parentID, metadataParentTypes) == "" {
				md := request.GetMetadata()
				if md == nil {
					md = &v11.ResourceMetadata{}
				}
				md.ParentId = parentID
				request.Metadata = md
			}
		}
	}
	if logger := s.sdk.GetLogger(); logger != nil {
		for path, warning := range check_nid.CheckMessageFields(request) {
			logger.WarnContext(ctx, warning, slog.String("path", path))
		}
		if warning := check_nid.CheckMetadataParentNID(request.GetMetadata(), metadataParentTypes); warning != "" {
			logger.WarnContext(ctx, warning, slog.String("path", "metadata.parent_id"))
		}
	}
	address, err := s.sdk.Resolve(ctx, EndpointServiceID)
	if err != nil {
		return nil, err
	}
	con, err := s.sdk.Dial(ctx, address)
	if err != nil {
		return nil, err
	}
	op, err := v1.NewEndpointServiceClient(con).Create(ctx, request, opts...)
	if err != nil {
		return nil, err
	}
	return operations.New(op, v11.NewOperationServiceClient(con))
}

func (s endpointService) Delete(ctx context.Context, request *v1.DeleteEndpointRequest, opts ...grpc.CallOption) (
	operations.Operation,
	error,
) {
	if logger := s.sdk.GetLogger(); logger != nil {
		for path, warning := range check_nid.CheckMessageFields(request) {
			logger.WarnContext(ctx, warning, slog.String("path", path))
		}
	}
	address, err := s.sdk.Resolve(ctx, EndpointServiceID)
	if err != nil {
		return nil, err
	}
	con, err := s.sdk.Dial(ctx, address)
	if err != nil {
		return nil, err
	}
	op, err := v1.NewEndpointServiceClient(con).Delete(ctx, request, opts...)
	if err != nil {
		return nil, err
	}
	return operations.New(op, v11.NewOperationServiceClient(con))
}

func (s endpointService) Update(ctx context.Context, request *v1.UpdateEndpointRequest, opts ...grpc.CallOption) (
	operations.Operation,
	error,
) {
	var metadataParentTypes []string
	ctx, err := grpcheader.EnsureMessageResetMaskInOutgoingContext(ctx, request)
	if err != nil {
		return nil, err
	}
	if logger := s.sdk.GetLogger(); logger != nil {
		for path, warning := range check_nid.CheckMessageFields(request) {
			logger.WarnContext(ctx, warning, slog.String("path", path))
		}
		if warning := check_nid.CheckMetadataParentNID(request.GetMetadata(), metadataParentTypes); warning != "" {
			logger.WarnContext(ctx, warning, slog.String("path", "metadata.parent_id"))
		}
	}
	address, err := s.sdk.Resolve(ctx, EndpointServiceID)
	if err != nil {
		return nil, err
	}
	con, err := s.sdk.Dial(ctx, address)
	if err != nil {
		return nil, err
	}
	op, err := v1.NewEndpointServiceClient(con).Update(ctx, request, opts...)
	if err != nil {
		return nil, err
	}
	return operations.New(op, v11.NewOperationServiceClient(con))
}

func (s endpointService) Start(ctx context.Context, request *v1.StartEndpointRequest, opts ...grpc.CallOption) (
	operations.Operation,
	error,
) {
	if logger := s.sdk.GetLogger(); logger != nil {
		for path, warning := range check_nid.CheckMessageFields(request) {
			logger.WarnContext(ctx, warning, slog.String("path", path))
		}
	}
	address, err := s.sdk.Resolve(ctx, EndpointServiceID)
	if err != nil {
		return nil, err
	}
	con, err := s.sdk.Dial(ctx, address)
	if err != nil {
		return nil, err
	}
	op, err := v1.NewEndpointServiceClient(con).Start(ctx, request, opts...)
	if err != nil {
		return nil, err
	}
	return operations.New(op, v11.NewOperationServiceClient(con))
}

func (s endpointService) Stop(ctx context.Context, request *v1.StopEndpointRequest, opts ...grpc.CallOption) (
	operations.Operation,
	error,
) {
	if logger := s.sdk.GetLogger(); logger != nil {
		for path, warning := range check_nid.CheckMessageFields(request) {
			logger.WarnContext(ctx, warning, slog.String("path", path))
		}
	}
	address, err := s.sdk.Resolve(ctx, EndpointServiceID)
	if err != nil {
		return nil, err
	}
	con, err := s.sdk.Dial(ctx, address)
	if err != nil {
		return nil, err
	}
	op, err := v1.NewEndpointServiceClient(con).Stop(ctx, request, opts...)
	if err != nil {
		return nil, err
	}
	return operations.New(op, v11.NewOperationServiceClient(con))
}

func (s endpointService) GetOperation(ctx context.Context, request *v11.GetOperationRequest, opts ...grpc.CallOption) (operations.Operation, error) {
	address, err := s.sdk.Resolve(ctx, EndpointServiceID)
	if err != nil {
		return nil, err
	}
	con, err := s.sdk.Dial(ctx, address)
	if err != nil {
		return nil, err
	}
	client := v11.NewOperationServiceClient(con)
	op, err := client.Get(ctx, request, opts...)
	if err != nil {
		return nil, err
	}
	return operations.New(op, client)
}

func (s endpointService) ListOperations(ctx context.Context, request *v11.ListOperationsRequest, opts ...grpc.CallOption) (*v11.ListOperationsResponse, error) {
	address, err := s.sdk.Resolve(ctx, EndpointServiceID)
	if err != nil {
		return nil, err
	}
	con, err := s.sdk.Dial(ctx, address)
	if err != nil {
		return nil, err
	}
	return v11.NewOperationServiceClient(con).List(ctx, request, opts...)
}
