// Code generated by protoc-gen-gosdk. DO NOT EDIT.

package v1

import (
	context "context"
	check_nid "github.com/nebius/gosdk/check-nid"
	conn "github.com/nebius/gosdk/conn"
	iface "github.com/nebius/gosdk/internal/iface"
	alphaops "github.com/nebius/gosdk/operations/alphaops"
	grpcheader "github.com/nebius/gosdk/proto/fieldmask/grpcheader"
	v11 "github.com/nebius/gosdk/proto/nebius/common/v1"
	v1alpha1 "github.com/nebius/gosdk/proto/nebius/common/v1alpha1"
	v1 "github.com/nebius/gosdk/proto/nebius/monitoring/v1"
	grpc "google.golang.org/grpc"
	proto "google.golang.org/protobuf/proto"
	iter "iter"
)

func init() {
	conn.ConventionResolverServiceIDToNameMap[RecordingRuleServiceID] = "monitoring"
}

func (s Services) RecordingRule() RecordingRuleService {
	return NewRecordingRuleService(s.sdk)
}

const RecordingRuleServiceID conn.ServiceID = "nebius.monitoring.v1.RecordingRuleService"

type RecordingRuleService interface {
	Get(context.Context, *v1.GetRecordingRuleRequest, ...grpc.CallOption) (*v1.RecordingRule, error)
	List(context.Context, *v1.ListRecordingRulesRequest, ...grpc.CallOption) (*v1.ListRecordingRulesResponse, error)
	Filter(context.Context, *v1.ListRecordingRulesRequest, ...grpc.CallOption) iter.Seq2[*v1.RecordingRule, error]
	Create(context.Context, *v1.CreateRecordingRuleRequest, ...grpc.CallOption) (*alphaops.Operation, error)
	Update(context.Context, *v1.UpdateRecordingRuleRequest, ...grpc.CallOption) (*alphaops.Operation, error)
	Delete(context.Context, *v1.DeleteRecordingRuleRequest, ...grpc.CallOption) (*alphaops.Operation, error)
	GetOperation(context.Context, *v1alpha1.GetOperationRequest, ...grpc.CallOption) (*alphaops.Operation, error)
	ListOperations(context.Context, *v1alpha1.ListOperationsRequest, ...grpc.CallOption) (*v1alpha1.ListOperationsResponse, error)
}

type recordingRuleService struct {
	sdk iface.SDKWithParentID
}

func NewRecordingRuleService(sdk iface.SDK) RecordingRuleService {
	return recordingRuleService{
		sdk: iface.WrapSDK(sdk),
	}
}

func (s recordingRuleService) Get(ctx context.Context, request *v1.GetRecordingRuleRequest, opts ...grpc.CallOption) (
	*v1.RecordingRule,
	error,
) {
	address, err := s.sdk.Resolve(ctx, RecordingRuleServiceID)
	if err != nil {
		return nil, err
	}
	con, err := s.sdk.Dial(ctx, address)
	if err != nil {
		return nil, err
	}
	return v1.NewRecordingRuleServiceClient(con).Get(ctx, request, opts...)
}

func (s recordingRuleService) List(ctx context.Context, request *v1.ListRecordingRulesRequest, opts ...grpc.CallOption) (
	*v1.ListRecordingRulesResponse,
	error,
) {
	if request.GetParentId() == "" {
		if parentID := s.sdk.ParentID(); parentID != "" {
			if check_nid.IsNIDAllowedForAutoFill(parentID, nil) {
				request.ParentId = parentID
			}
		}
		if request.GetParentId() == "" {
			if tenantID := s.sdk.TenantID(); tenantID != "" {
				if check_nid.IsNIDAllowedForAutoFill(tenantID, nil) {
					request.ParentId = tenantID
				}
			}
		}
	}
	address, err := s.sdk.Resolve(ctx, RecordingRuleServiceID)
	if err != nil {
		return nil, err
	}
	con, err := s.sdk.Dial(ctx, address)
	if err != nil {
		return nil, err
	}
	return v1.NewRecordingRuleServiceClient(con).List(ctx, request, opts...)
}

func (s recordingRuleService) Filter(ctx context.Context, request *v1.ListRecordingRulesRequest, opts ...grpc.CallOption) iter.Seq2[*v1.RecordingRule, error] {
	req := proto.Clone(request).(*v1.ListRecordingRulesRequest)
	return func(yield func(*v1.RecordingRule, error) bool) {
		for {
			res, err := s.List(ctx, req, opts...)
			if err != nil {
				yield(nil, err)
				return
			}

			for _, item := range res.GetItems() {
				if !yield(item, nil) {
					return
				}
			}

			if res.GetNextPageToken() == "" {
				return
			}

			req.PageToken = res.GetNextPageToken()
		}
	}
}

func (s recordingRuleService) Create(ctx context.Context, request *v1.CreateRecordingRuleRequest, opts ...grpc.CallOption) (
	*alphaops.Operation,
	error,
) {
	if request.GetMetadata().GetParentId() == "" {
		if tenantID := s.sdk.TenantID(); tenantID != "" {
			if check_nid.IsNIDAllowedForAutoFill(tenantID, nil) {
				md := request.GetMetadata()
				if md == nil {
					md = &v11.ResourceMetadata{}
				}
				md.ParentId = tenantID
				request.Metadata = md
			}
		}
		if parentID := s.sdk.ParentID(); parentID != "" {
			if check_nid.IsNIDAllowedForAutoFill(parentID, nil) {
				md := request.GetMetadata()
				if md == nil {
					md = &v11.ResourceMetadata{}
				}
				md.ParentId = parentID
				request.Metadata = md
			}
		}
	}
	address, err := s.sdk.Resolve(ctx, RecordingRuleServiceID)
	if err != nil {
		return nil, err
	}
	con, err := s.sdk.Dial(ctx, address)
	if err != nil {
		return nil, err
	}
	op, err := v1.NewRecordingRuleServiceClient(con).Create(ctx, request, opts...)
	if err != nil {
		return nil, err
	}
	return alphaops.Wrap(op, v1alpha1.NewOperationServiceClient(con))
}

func (s recordingRuleService) Update(ctx context.Context, request *v1.UpdateRecordingRuleRequest, opts ...grpc.CallOption) (
	*alphaops.Operation,
	error,
) {
	ctx, err := grpcheader.EnsureMessageResetMaskInOutgoingContext(ctx, request)
	if err != nil {
		return nil, err
	}
	address, err := s.sdk.Resolve(ctx, RecordingRuleServiceID)
	if err != nil {
		return nil, err
	}
	con, err := s.sdk.Dial(ctx, address)
	if err != nil {
		return nil, err
	}
	op, err := v1.NewRecordingRuleServiceClient(con).Update(ctx, request, opts...)
	if err != nil {
		return nil, err
	}
	return alphaops.Wrap(op, v1alpha1.NewOperationServiceClient(con))
}

func (s recordingRuleService) Delete(ctx context.Context, request *v1.DeleteRecordingRuleRequest, opts ...grpc.CallOption) (
	*alphaops.Operation,
	error,
) {
	address, err := s.sdk.Resolve(ctx, RecordingRuleServiceID)
	if err != nil {
		return nil, err
	}
	con, err := s.sdk.Dial(ctx, address)
	if err != nil {
		return nil, err
	}
	op, err := v1.NewRecordingRuleServiceClient(con).Delete(ctx, request, opts...)
	if err != nil {
		return nil, err
	}
	return alphaops.Wrap(op, v1alpha1.NewOperationServiceClient(con))
}

func (s recordingRuleService) GetOperation(ctx context.Context, request *v1alpha1.GetOperationRequest, opts ...grpc.CallOption) (*alphaops.Operation, error) {
	address, err := s.sdk.Resolve(ctx, RecordingRuleServiceID)
	if err != nil {
		return nil, err
	}
	con, err := s.sdk.Dial(ctx, address)
	if err != nil {
		return nil, err
	}
	client := v1alpha1.NewOperationServiceClient(con)
	op, err := client.Get(ctx, request, opts...)
	if err != nil {
		return nil, err
	}
	return alphaops.Wrap(op, client)
}

func (s recordingRuleService) ListOperations(ctx context.Context, request *v1alpha1.ListOperationsRequest, opts ...grpc.CallOption) (*v1alpha1.ListOperationsResponse, error) {
	address, err := s.sdk.Resolve(ctx, RecordingRuleServiceID)
	if err != nil {
		return nil, err
	}
	con, err := s.sdk.Dial(ctx, address)
	if err != nil {
		return nil, err
	}
	return v1alpha1.NewOperationServiceClient(con).List(ctx, request, opts...)
}
