// Code generated by protoc-gen-sensitive. DO NOT EDIT.

package v1alpha1

// func (x *Maintenance) Sanitize()            // is not generated as no sensitive fields found
// func (x *Maintenance) LogValue() slog.Value // is not generated as no sensitive fields found

// func (x *MaintenanceSpec) Sanitize()            // is not generated as no sensitive fields found
// func (x *MaintenanceSpec) LogValue() slog.Value // is not generated as no sensitive fields found

// func (x *MaintenanceStatus) Sanitize()            // is not generated as no sensitive fields found
// func (x *MaintenanceStatus) LogValue() slog.Value // is not generated as no sensitive fields found

// func (x *Resource) Sanitize()            // is not generated as no sensitive fields found
// func (x *Resource) LogValue() slog.Value // is not generated as no sensitive fields found
