// Code generated by MockGen. DO NOT EDIT.
// Source: services/nebius/dns/v1/zone_service.sdk.go
//
// Generated by this command:
//
//	mockgen -source services/nebius/dns/v1/zone_service.sdk.go -package v1 -typed
//

// Package v1 is a generated GoMock package.
package v1

import (
	context "context"
	reflect "reflect"

	iter "github.com/nebius/gosdk/iter"
	v1 "github.com/nebius/gosdk/proto/nebius/common/v1"
	v10 "github.com/nebius/gosdk/proto/nebius/dns/v1"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockZoneService is a mock of ZoneService interface.
type MockZoneService struct {
	ctrl     *gomock.Controller
	recorder *MockZoneServiceMockRecorder
}

// MockZoneServiceMockRecorder is the mock recorder for MockZoneService.
type MockZoneServiceMockRecorder struct {
	mock *MockZoneService
}

// NewMockZoneService creates a new mock instance.
func NewMockZoneService(ctrl *gomock.Controller) *MockZoneService {
	mock := &MockZoneService{ctrl: ctrl}
	mock.recorder = &MockZoneServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockZoneService) EXPECT() *MockZoneServiceMockRecorder {
	return m.recorder
}

// Filter mocks base method.
func (m *MockZoneService) Filter(arg0 context.Context, arg1 *v10.ListZonesRequest, arg2 ...grpc.CallOption) iter.Seq2[*v10.Zone, error] {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Filter", varargs...)
	ret0, _ := ret[0].(iter.Seq2[*v10.Zone, error])
	return ret0
}

// Filter indicates an expected call of Filter.
func (mr *MockZoneServiceMockRecorder) Filter(arg0, arg1 any, arg2 ...any) *MockZoneServiceFilterCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Filter", reflect.TypeOf((*MockZoneService)(nil).Filter), varargs...)
	return &MockZoneServiceFilterCall{Call: call}
}

// MockZoneServiceFilterCall wrap *gomock.Call
type MockZoneServiceFilterCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockZoneServiceFilterCall) Return(arg0 iter.Seq2[*v10.Zone, error]) *MockZoneServiceFilterCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockZoneServiceFilterCall) Do(f func(context.Context, *v10.ListZonesRequest, ...grpc.CallOption) iter.Seq2[*v10.Zone, error]) *MockZoneServiceFilterCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockZoneServiceFilterCall) DoAndReturn(f func(context.Context, *v10.ListZonesRequest, ...grpc.CallOption) iter.Seq2[*v10.Zone, error]) *MockZoneServiceFilterCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Get mocks base method.
func (m *MockZoneService) Get(arg0 context.Context, arg1 *v10.GetZoneRequest, arg2 ...grpc.CallOption) (*v10.Zone, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(*v10.Zone)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockZoneServiceMockRecorder) Get(arg0, arg1 any, arg2 ...any) *MockZoneServiceGetCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockZoneService)(nil).Get), varargs...)
	return &MockZoneServiceGetCall{Call: call}
}

// MockZoneServiceGetCall wrap *gomock.Call
type MockZoneServiceGetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockZoneServiceGetCall) Return(arg0 *v10.Zone, arg1 error) *MockZoneServiceGetCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockZoneServiceGetCall) Do(f func(context.Context, *v10.GetZoneRequest, ...grpc.CallOption) (*v10.Zone, error)) *MockZoneServiceGetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockZoneServiceGetCall) DoAndReturn(f func(context.Context, *v10.GetZoneRequest, ...grpc.CallOption) (*v10.Zone, error)) *MockZoneServiceGetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByName mocks base method.
func (m *MockZoneService) GetByName(arg0 context.Context, arg1 *v1.GetByNameRequest, arg2 ...grpc.CallOption) (*v10.Zone, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetByName", varargs...)
	ret0, _ := ret[0].(*v10.Zone)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockZoneServiceMockRecorder) GetByName(arg0, arg1 any, arg2 ...any) *MockZoneServiceGetByNameCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockZoneService)(nil).GetByName), varargs...)
	return &MockZoneServiceGetByNameCall{Call: call}
}

// MockZoneServiceGetByNameCall wrap *gomock.Call
type MockZoneServiceGetByNameCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockZoneServiceGetByNameCall) Return(arg0 *v10.Zone, arg1 error) *MockZoneServiceGetByNameCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockZoneServiceGetByNameCall) Do(f func(context.Context, *v1.GetByNameRequest, ...grpc.CallOption) (*v10.Zone, error)) *MockZoneServiceGetByNameCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockZoneServiceGetByNameCall) DoAndReturn(f func(context.Context, *v1.GetByNameRequest, ...grpc.CallOption) (*v10.Zone, error)) *MockZoneServiceGetByNameCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// List mocks base method.
func (m *MockZoneService) List(arg0 context.Context, arg1 *v10.ListZonesRequest, arg2 ...grpc.CallOption) (*v10.ListZonesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].(*v10.ListZonesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockZoneServiceMockRecorder) List(arg0, arg1 any, arg2 ...any) *MockZoneServiceListCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockZoneService)(nil).List), varargs...)
	return &MockZoneServiceListCall{Call: call}
}

// MockZoneServiceListCall wrap *gomock.Call
type MockZoneServiceListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockZoneServiceListCall) Return(arg0 *v10.ListZonesResponse, arg1 error) *MockZoneServiceListCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockZoneServiceListCall) Do(f func(context.Context, *v10.ListZonesRequest, ...grpc.CallOption) (*v10.ListZonesResponse, error)) *MockZoneServiceListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockZoneServiceListCall) DoAndReturn(f func(context.Context, *v10.ListZonesRequest, ...grpc.CallOption) (*v10.ListZonesResponse, error)) *MockZoneServiceListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
