// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.6
// source: nebius/applications/v1alpha1/vmapp_template_service.proto

package v1alpha1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/nebius/gosdk/proto/nebius"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A request to retrieve a VM app template by ID.
type GetVmAppTemplateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the template to retrieve.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVmAppTemplateRequest) Reset() {
	*x = GetVmAppTemplateRequest{}
	mi := &file_nebius_applications_v1alpha1_vmapp_template_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVmAppTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVmAppTemplateRequest) ProtoMessage() {}

func (x *GetVmAppTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nebius_applications_v1alpha1_vmapp_template_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVmAppTemplateRequest.ProtoReflect.Descriptor instead.
func (*GetVmAppTemplateRequest) Descriptor() ([]byte, []int) {
	return file_nebius_applications_v1alpha1_vmapp_template_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetVmAppTemplateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// A request to list VM app templates.
type ListVmAppTemplatesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The project ID. The response includes templates from this project and the global catalog.
	// Required unless global_only is true.
	ParentId string `protobuf:"bytes,1,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	// The requested page size. The service currently ignores this field and returns all matching templates.
	// The default value is 0.
	PageSize int64 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// The pagination token. The service currently ignores this field. Leave it empty.
	PageToken string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// The text to find in template names and descriptions. The search is case-sensitive.
	Search string `protobuf:"bytes,4,opt,name=search,proto3" json:"search,omitempty"`
	// The categories to match. The response includes templates that match at least one category.
	Categories []string `protobuf:"bytes,5,rep,name=categories,proto3" json:"categories,omitempty"`
	// Returns only global templates when true. The service ignores parent_id in this mode.
	// Global catalog reads require authentication but do not require a resource permission.
	GlobalOnly bool `protobuf:"varint,7,opt,name=global_only,json=globalOnly,proto3" json:"global_only,omitempty"`
	// The template kind: "covm" or "devlab". The default is "covm".
	Kind          string `protobuf:"bytes,1000,opt,name=kind,proto3" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVmAppTemplatesRequest) Reset() {
	*x = ListVmAppTemplatesRequest{}
	mi := &file_nebius_applications_v1alpha1_vmapp_template_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVmAppTemplatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVmAppTemplatesRequest) ProtoMessage() {}

func (x *ListVmAppTemplatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nebius_applications_v1alpha1_vmapp_template_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVmAppTemplatesRequest.ProtoReflect.Descriptor instead.
func (*ListVmAppTemplatesRequest) Descriptor() ([]byte, []int) {
	return file_nebius_applications_v1alpha1_vmapp_template_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListVmAppTemplatesRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *ListVmAppTemplatesRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListVmAppTemplatesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListVmAppTemplatesRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *ListVmAppTemplatesRequest) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *ListVmAppTemplatesRequest) GetGlobalOnly() bool {
	if x != nil {
		return x.GlobalOnly
	}
	return false
}

func (x *ListVmAppTemplatesRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

// The templates that match the list request.
type ListVmAppTemplatesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// All matching templates. The service currently returns the complete list without pagination.
	Items []*VmAppTemplate `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	// The token for the next page. Currently always empty because the service returns all matching templates.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVmAppTemplatesResponse) Reset() {
	*x = ListVmAppTemplatesResponse{}
	mi := &file_nebius_applications_v1alpha1_vmapp_template_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVmAppTemplatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVmAppTemplatesResponse) ProtoMessage() {}

func (x *ListVmAppTemplatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nebius_applications_v1alpha1_vmapp_template_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVmAppTemplatesResponse.ProtoReflect.Descriptor instead.
func (*ListVmAppTemplatesResponse) Descriptor() ([]byte, []int) {
	return file_nebius_applications_v1alpha1_vmapp_template_service_proto_rawDescGZIP(), []int{2}
}

func (x *ListVmAppTemplatesResponse) GetItems() []*VmAppTemplate {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListVmAppTemplatesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_nebius_applications_v1alpha1_vmapp_template_service_proto protoreflect.FileDescriptor

const file_nebius_applications_v1alpha1_vmapp_template_service_proto_rawDesc = "" +
	"\n" +
	"9nebius/applications/v1alpha1/vmapp_template_service.proto\x12\x1cnebius.applications.v1alpha1\x1a\x1bbuf/validate/validate.proto\x1a\x18nebius/annotations.proto\x1a1nebius/applications/v1alpha1/vmapp_template.proto\"1\n" +
	"\x17GetVmAppTemplateRequest\x12\x16\n" +
	"\x02id\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x02id\"\xf6\x01\n" +
	"\x19ListVmAppTemplatesRequest\x12\x1b\n" +
	"\tparent_id\x18\x01 \x01(\tR\bparentId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\x12 \n" +
	"\x06search\x18\x04 \x01(\tB\b\xbaH\x05r\x03\x18\x80\x02R\x06search\x12(\n" +
	"\n" +
	"categories\x18\x05 \x03(\tB\b\xbaH\x05\x92\x01\x02\x10\x05R\n" +
	"categories\x12\x1f\n" +
	"\vglobal_only\x18\a \x01(\bR\n" +
	"globalOnly\x12\x13\n" +
	"\x04kind\x18\xe8\a \x01(\tR\x04kind\"\x87\x01\n" +
	"\x1aListVmAppTemplatesResponse\x12A\n" +
	"\x05items\x18\x01 \x03(\v2+.nebius.applications.v1alpha1.VmAppTemplateR\x05items\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken2\x89\x02\n" +
	"\x14VmAppTemplateService\x12i\n" +
	"\x03Get\x125.nebius.applications.v1alpha1.GetVmAppTemplateRequest\x1a+.nebius.applications.v1alpha1.VmAppTemplate\x12y\n" +
	"\x04List\x127.nebius.applications.v1alpha1.ListVmAppTemplatesRequest\x1a8.nebius.applications.v1alpha1.ListVmAppTemplatesResponse\x1a\v\xbaJ\bapps.mspB~\n" +
	"#ai.nebius.pub.applications.v1alpha1B\x19VmappTemplateServiceProtoP\x01Z:github.com/nebius/gosdk/proto/nebius/applications/v1alpha1b\x06proto3"

var (
	file_nebius_applications_v1alpha1_vmapp_template_service_proto_rawDescOnce sync.Once
	file_nebius_applications_v1alpha1_vmapp_template_service_proto_rawDescData []byte
)

func file_nebius_applications_v1alpha1_vmapp_template_service_proto_rawDescGZIP() []byte {
	file_nebius_applications_v1alpha1_vmapp_template_service_proto_rawDescOnce.Do(func() {
		file_nebius_applications_v1alpha1_vmapp_template_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nebius_applications_v1alpha1_vmapp_template_service_proto_rawDesc), len(file_nebius_applications_v1alpha1_vmapp_template_service_proto_rawDesc)))
	})
	return file_nebius_applications_v1alpha1_vmapp_template_service_proto_rawDescData
}

var file_nebius_applications_v1alpha1_vmapp_template_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_nebius_applications_v1alpha1_vmapp_template_service_proto_goTypes = []any{
	(*GetVmAppTemplateRequest)(nil),    // 0: nebius.applications.v1alpha1.GetVmAppTemplateRequest
	(*ListVmAppTemplatesRequest)(nil),  // 1: nebius.applications.v1alpha1.ListVmAppTemplatesRequest
	(*ListVmAppTemplatesResponse)(nil), // 2: nebius.applications.v1alpha1.ListVmAppTemplatesResponse
	(*VmAppTemplate)(nil),              // 3: nebius.applications.v1alpha1.VmAppTemplate
}
var file_nebius_applications_v1alpha1_vmapp_template_service_proto_depIdxs = []int32{
	3, // 0: nebius.applications.v1alpha1.ListVmAppTemplatesResponse.items:type_name -> nebius.applications.v1alpha1.VmAppTemplate
	0, // 1: nebius.applications.v1alpha1.VmAppTemplateService.Get:input_type -> nebius.applications.v1alpha1.GetVmAppTemplateRequest
	1, // 2: nebius.applications.v1alpha1.VmAppTemplateService.List:input_type -> nebius.applications.v1alpha1.ListVmAppTemplatesRequest
	3, // 3: nebius.applications.v1alpha1.VmAppTemplateService.Get:output_type -> nebius.applications.v1alpha1.VmAppTemplate
	2, // 4: nebius.applications.v1alpha1.VmAppTemplateService.List:output_type -> nebius.applications.v1alpha1.ListVmAppTemplatesResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_nebius_applications_v1alpha1_vmapp_template_service_proto_init() }
func file_nebius_applications_v1alpha1_vmapp_template_service_proto_init() {
	if File_nebius_applications_v1alpha1_vmapp_template_service_proto != nil {
		return
	}
	file_nebius_applications_v1alpha1_vmapp_template_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nebius_applications_v1alpha1_vmapp_template_service_proto_rawDesc), len(file_nebius_applications_v1alpha1_vmapp_template_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nebius_applications_v1alpha1_vmapp_template_service_proto_goTypes,
		DependencyIndexes: file_nebius_applications_v1alpha1_vmapp_template_service_proto_depIdxs,
		MessageInfos:      file_nebius_applications_v1alpha1_vmapp_template_service_proto_msgTypes,
	}.Build()
	File_nebius_applications_v1alpha1_vmapp_template_service_proto = out.File
	file_nebius_applications_v1alpha1_vmapp_template_service_proto_goTypes = nil
	file_nebius_applications_v1alpha1_vmapp_template_service_proto_depIdxs = nil
}
