// Code generated by protoc-gen-sensitive. DO NOT EDIT.

package v1

// func (x *ListQuotaAllowancesRequest) Sanitize()            // is not generated as no sensitive fields found
// func (x *ListQuotaAllowancesRequest) LogValue() slog.Value // is not generated as no sensitive fields found

// func (x *GetQuotaAllowanceRequest) Sanitize()            // is not generated as no sensitive fields found
// func (x *GetQuotaAllowanceRequest) LogValue() slog.Value // is not generated as no sensitive fields found

// func (x *ListQuotaAllowancesResponse) Sanitize()            // is not generated as no sensitive fields found
// func (x *ListQuotaAllowancesResponse) LogValue() slog.Value // is not generated as no sensitive fields found

// func (x *GetByNameRequest) Sanitize()            // is not generated as no sensitive fields found
// func (x *GetByNameRequest) LogValue() slog.Value // is not generated as no sensitive fields found
