// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.6
// source: nebius/kms/v1/asymmetric_key_service.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/nebius/gosdk/proto/nebius"
	v1 "github.com/nebius/gosdk/proto/nebius/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateAsymmetricKeyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The metadata for the resource.
	Metadata *v1.ResourceMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// The specifications for creating an asymmetric key.
	Spec          *AsymmetricKeySpec `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAsymmetricKeyRequest) Reset() {
	*x = CreateAsymmetricKeyRequest{}
	mi := &file_nebius_kms_v1_asymmetric_key_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAsymmetricKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAsymmetricKeyRequest) ProtoMessage() {}

func (x *CreateAsymmetricKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nebius_kms_v1_asymmetric_key_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAsymmetricKeyRequest.ProtoReflect.Descriptor instead.
func (*CreateAsymmetricKeyRequest) Descriptor() ([]byte, []int) {
	return file_nebius_kms_v1_asymmetric_key_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAsymmetricKeyRequest) GetMetadata() *v1.ResourceMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CreateAsymmetricKeyRequest) GetSpec() *AsymmetricKeySpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type UpdateAsymmetricKeyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The metadata for the resource.
	Metadata *v1.ResourceMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// The specifications for updating an asymmetric key.
	Spec          *AsymmetricKeySpec `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAsymmetricKeyRequest) Reset() {
	*x = UpdateAsymmetricKeyRequest{}
	mi := &file_nebius_kms_v1_asymmetric_key_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAsymmetricKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAsymmetricKeyRequest) ProtoMessage() {}

func (x *UpdateAsymmetricKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nebius_kms_v1_asymmetric_key_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAsymmetricKeyRequest.ProtoReflect.Descriptor instead.
func (*UpdateAsymmetricKeyRequest) Descriptor() ([]byte, []int) {
	return file_nebius_kms_v1_asymmetric_key_service_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateAsymmetricKeyRequest) GetMetadata() *v1.ResourceMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *UpdateAsymmetricKeyRequest) GetSpec() *AsymmetricKeySpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type GetAsymmetricKeyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the asymmetric KMS key to return.
	// To get the ID of an asymmetric KMS key use an [AsymmetricKeyService.List] request.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// By default, Get doesn't return resource if it is scheduled for deletion.
	// If show_scheduled_for_deletion = true, the Get operation returns the resource even if it is scheduled for deletion.
	// If show_scheduled_for_deletion = false, the Get method returns the NOT_FOUND gRPC status code.
	ShowScheduledForDeletion bool `protobuf:"varint,2,opt,name=show_scheduled_for_deletion,json=showScheduledForDeletion,proto3" json:"show_scheduled_for_deletion,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *GetAsymmetricKeyRequest) Reset() {
	*x = GetAsymmetricKeyRequest{}
	mi := &file_nebius_kms_v1_asymmetric_key_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAsymmetricKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAsymmetricKeyRequest) ProtoMessage() {}

func (x *GetAsymmetricKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nebius_kms_v1_asymmetric_key_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAsymmetricKeyRequest.ProtoReflect.Descriptor instead.
func (*GetAsymmetricKeyRequest) Descriptor() ([]byte, []int) {
	return file_nebius_kms_v1_asymmetric_key_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetAsymmetricKeyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetAsymmetricKeyRequest) GetShowScheduledForDeletion() bool {
	if x != nil {
		return x.ShowScheduledForDeletion
	}
	return false
}

type GetAsymmetricKeyByNameRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Parent Id and name of the asymmetric KMS key to return.
	// To get the name of an asymmetric KMS key use an [AsymmetricKeyService.List] request.
	ParentId      string `protobuf:"bytes,1,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAsymmetricKeyByNameRequest) Reset() {
	*x = GetAsymmetricKeyByNameRequest{}
	mi := &file_nebius_kms_v1_asymmetric_key_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAsymmetricKeyByNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAsymmetricKeyByNameRequest) ProtoMessage() {}

func (x *GetAsymmetricKeyByNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nebius_kms_v1_asymmetric_key_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAsymmetricKeyByNameRequest.ProtoReflect.Descriptor instead.
func (*GetAsymmetricKeyByNameRequest) Descriptor() ([]byte, []int) {
	return file_nebius_kms_v1_asymmetric_key_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetAsymmetricKeyByNameRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *GetAsymmetricKeyByNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListAsymmetricKeysRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the container to list asymmetric KMS keys in.
	ParentId string `protobuf:"bytes,1,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	// The maximum number of results per page to return. If the number of available
	// results is larger than [page_size], the service returns a [ListAsymmetricKeysResponse.next_page_token]
	// that can be used to get the next page of results in subsequent list requests.
	// Default value: 100.
	PageSize int64 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Page token. To get the next page of results, set [page_token] to the
	// [ListAsymmetricKeysResponse.next_page_token] returned by a previous list request.
	PageToken string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// By default, List operation doesn't include resources that are scheduled for deletion.
	// If show_scheduled_for_deletion = true, the listing includes resources that are scheduled for deletion.
	ShowScheduledForDeletion bool `protobuf:"varint,4,opt,name=show_scheduled_for_deletion,json=showScheduledForDeletion,proto3" json:"show_scheduled_for_deletion,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ListAsymmetricKeysRequest) Reset() {
	*x = ListAsymmetricKeysRequest{}
	mi := &file_nebius_kms_v1_asymmetric_key_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAsymmetricKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAsymmetricKeysRequest) ProtoMessage() {}

func (x *ListAsymmetricKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nebius_kms_v1_asymmetric_key_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAsymmetricKeysRequest.ProtoReflect.Descriptor instead.
func (*ListAsymmetricKeysRequest) Descriptor() ([]byte, []int) {
	return file_nebius_kms_v1_asymmetric_key_service_proto_rawDescGZIP(), []int{4}
}

func (x *ListAsymmetricKeysRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *ListAsymmetricKeysRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListAsymmetricKeysRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListAsymmetricKeysRequest) GetShowScheduledForDeletion() bool {
	if x != nil {
		return x.ShowScheduledForDeletion
	}
	return false
}

type ListAsymmetricKeysResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of asymmetric KMS keys in the specified container.
	Items []*AsymmetricKey `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	// This token allows you to get the next page of results for list requests. If the number
	// of results is greater than the specified [ListAsymmetricKeysRequest.page_size], use
	// the [next_page_token] as the value for the [ListAsymmetricKeysRequest.page_token] query parameter
	// in the next list request. Each subsequent list request will have its own
	// [next_page_token] to continue paging through the results.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAsymmetricKeysResponse) Reset() {
	*x = ListAsymmetricKeysResponse{}
	mi := &file_nebius_kms_v1_asymmetric_key_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAsymmetricKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAsymmetricKeysResponse) ProtoMessage() {}

func (x *ListAsymmetricKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nebius_kms_v1_asymmetric_key_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAsymmetricKeysResponse.ProtoReflect.Descriptor instead.
func (*ListAsymmetricKeysResponse) Descriptor() ([]byte, []int) {
	return file_nebius_kms_v1_asymmetric_key_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListAsymmetricKeysResponse) GetItems() []*AsymmetricKey {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListAsymmetricKeysResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type DeleteAsymmetricKeyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the asymmetric KMS key to schedule for deletion.
	// To get the ID of an asymmetric KMS key use an [AsymmetricKeyService.List] request.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAsymmetricKeyRequest) Reset() {
	*x = DeleteAsymmetricKeyRequest{}
	mi := &file_nebius_kms_v1_asymmetric_key_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAsymmetricKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAsymmetricKeyRequest) ProtoMessage() {}

func (x *DeleteAsymmetricKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nebius_kms_v1_asymmetric_key_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAsymmetricKeyRequest.ProtoReflect.Descriptor instead.
func (*DeleteAsymmetricKeyRequest) Descriptor() ([]byte, []int) {
	return file_nebius_kms_v1_asymmetric_key_service_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteAsymmetricKeyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateAsymmetricKeyDeletionDelayRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the asymmetric KMS key scheduled for deletion.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Deletion delay applied from the update timestamp.
	// Example: "86400s" (1 day). Valid range: 86400s (1 day) to 2592000s (30 days).
	DeletionDelay *durationpb.Duration `protobuf:"bytes,2,opt,name=deletion_delay,json=deletionDelay,proto3" json:"deletion_delay,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAsymmetricKeyDeletionDelayRequest) Reset() {
	*x = UpdateAsymmetricKeyDeletionDelayRequest{}
	mi := &file_nebius_kms_v1_asymmetric_key_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAsymmetricKeyDeletionDelayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAsymmetricKeyDeletionDelayRequest) ProtoMessage() {}

func (x *UpdateAsymmetricKeyDeletionDelayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nebius_kms_v1_asymmetric_key_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAsymmetricKeyDeletionDelayRequest.ProtoReflect.Descriptor instead.
func (*UpdateAsymmetricKeyDeletionDelayRequest) Descriptor() ([]byte, []int) {
	return file_nebius_kms_v1_asymmetric_key_service_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateAsymmetricKeyDeletionDelayRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateAsymmetricKeyDeletionDelayRequest) GetDeletionDelay() *durationpb.Duration {
	if x != nil {
		return x.DeletionDelay
	}
	return nil
}

type UndeleteAsymmetricKeyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the asymmetric KMS key to restore.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// A new name in case the current one is already in use.
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UndeleteAsymmetricKeyRequest) Reset() {
	*x = UndeleteAsymmetricKeyRequest{}
	mi := &file_nebius_kms_v1_asymmetric_key_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UndeleteAsymmetricKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UndeleteAsymmetricKeyRequest) ProtoMessage() {}

func (x *UndeleteAsymmetricKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nebius_kms_v1_asymmetric_key_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UndeleteAsymmetricKeyRequest.ProtoReflect.Descriptor instead.
func (*UndeleteAsymmetricKeyRequest) Descriptor() ([]byte, []int) {
	return file_nebius_kms_v1_asymmetric_key_service_proto_rawDescGZIP(), []int{8}
}

func (x *UndeleteAsymmetricKeyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UndeleteAsymmetricKeyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_nebius_kms_v1_asymmetric_key_service_proto protoreflect.FileDescriptor

const file_nebius_kms_v1_asymmetric_key_service_proto_rawDesc = "" +
	"\n" +
	"*nebius/kms/v1/asymmetric_key_service.proto\x12\rnebius.kms.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x18nebius/annotations.proto\x1a\x1fnebius/common/v1/metadata.proto\x1a nebius/common/v1/operation.proto\x1a\"nebius/kms/v1/asymmetric_key.proto\"\xae\x01\n" +
	"\x1aCreateAsymmetricKeyRequest\x12R\n" +
	"\bmetadata\x18\x01 \x01(\v2\".nebius.common.v1.ResourceMetadataB\x12\xbaH\x03\xc8\x01\x01\xe2J\t\x12\aprojectR\bmetadata\x12<\n" +
	"\x04spec\x18\x02 \x01(\v2 .nebius.kms.v1.AsymmetricKeySpecB\x06\xbaH\x03\xc8\x01\x01R\x04spec\"\xa6\x01\n" +
	"\x1aUpdateAsymmetricKeyRequest\x12R\n" +
	"\bmetadata\x18\x01 \x01(\v2\".nebius.common.v1.ResourceMetadataB\x12\xbaH\x03\xc8\x01\x01\xe2J\t\x12\aprojectR\bmetadata\x124\n" +
	"\x04spec\x18\x02 \x01(\v2 .nebius.kms.v1.AsymmetricKeySpecR\x04spec\"\x7f\n" +
	"\x17GetAsymmetricKeyRequest\x12%\n" +
	"\x02id\x18\x01 \x01(\tB\x15\xbaH\x03\xc8\x01\x01\xe2J\f\n" +
	"\n" +
	"kmsasymkeyR\x02id\x12=\n" +
	"\x1bshow_scheduled_for_deletion\x18\x02 \x01(\bR\x18showScheduledForDeletion\"l\n" +
	"\x1dGetAsymmetricKeyByNameRequest\x12/\n" +
	"\tparent_id\x18\x01 \x01(\tB\x12\xbaH\x03\xc8\x01\x01\xe2J\t\n" +
	"\aprojectR\bparentId\x12\x1a\n" +
	"\x04name\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x04name\"\xc7\x01\n" +
	"\x19ListAsymmetricKeysRequest\x12/\n" +
	"\tparent_id\x18\x01 \x01(\tB\x12\xbaH\x03\xc8\x01\x01\xe2J\t\n" +
	"\aprojectR\bparentId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\x12=\n" +
	"\x1bshow_scheduled_for_deletion\x18\x04 \x01(\bR\x18showScheduledForDeletion\"x\n" +
	"\x1aListAsymmetricKeysResponse\x122\n" +
	"\x05items\x18\x01 \x03(\v2\x1c.nebius.kms.v1.AsymmetricKeyR\x05items\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"C\n" +
	"\x1aDeleteAsymmetricKeyRequest\x12%\n" +
	"\x02id\x18\x01 \x01(\tB\x15\xbaH\x03\xc8\x01\x01\xe2J\f\n" +
	"\n" +
	"kmsasymkeyR\x02id\"\xaa\x01\n" +
	"'UpdateAsymmetricKeyDeletionDelayRequest\x12%\n" +
	"\x02id\x18\x01 \x01(\tB\x15\xbaH\x03\xc8\x01\x01\xe2J\f\n" +
	"\n" +
	"kmsasymkeyR\x02id\x12X\n" +
	"\x0edeletion_delay\x18\x02 \x01(\v2\x19.google.protobuf.DurationB\x16\xbaH\x13\xc8\x01\x01\xaa\x01\r\"\x05\b\x80\x9a\x9e\x012\x04\b\x80\xa3\x05R\rdeletionDelay\"Y\n" +
	"\x1cUndeleteAsymmetricKeyRequest\x12%\n" +
	"\x02id\x18\x01 \x01(\tB\x15\xbaH\x03\xc8\x01\x01\xe2J\f\n" +
	"\n" +
	"kmsasymkeyR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name2\xdd\x05\n" +
	"\x14AsymmetricKeyService\x12P\n" +
	"\x06Create\x12).nebius.kms.v1.CreateAsymmetricKeyRequest\x1a\x1b.nebius.common.v1.Operation\x12P\n" +
	"\x06Update\x12).nebius.kms.v1.UpdateAsymmetricKeyRequest\x1a\x1b.nebius.common.v1.Operation\x12K\n" +
	"\x03Get\x12&.nebius.kms.v1.GetAsymmetricKeyRequest\x1a\x1c.nebius.kms.v1.AsymmetricKey\x12W\n" +
	"\tGetByName\x12,.nebius.kms.v1.GetAsymmetricKeyByNameRequest\x1a\x1c.nebius.kms.v1.AsymmetricKey\x12[\n" +
	"\x04List\x12(.nebius.kms.v1.ListAsymmetricKeysRequest\x1a).nebius.kms.v1.ListAsymmetricKeysResponse\x12P\n" +
	"\x06Delete\x12).nebius.kms.v1.DeleteAsymmetricKeyRequest\x1a\x1b.nebius.common.v1.Operation\x12j\n" +
	"\x13UpdateDeletionDelay\x126.nebius.kms.v1.UpdateAsymmetricKeyDeletionDelayRequest\x1a\x1b.nebius.common.v1.Operation\x12T\n" +
	"\bUndelete\x12+.nebius.kms.v1.UndeleteAsymmetricKeyRequest\x1a\x1b.nebius.common.v1.Operation\x1a\n" +
	"\xbaJ\acpl.kmsB`\n" +
	"\x14ai.nebius.pub.kms.v1B\x19AsymmetricKeyServiceProtoP\x01Z+github.com/nebius/gosdk/proto/nebius/kms/v1b\x06proto3"

var (
	file_nebius_kms_v1_asymmetric_key_service_proto_rawDescOnce sync.Once
	file_nebius_kms_v1_asymmetric_key_service_proto_rawDescData []byte
)

func file_nebius_kms_v1_asymmetric_key_service_proto_rawDescGZIP() []byte {
	file_nebius_kms_v1_asymmetric_key_service_proto_rawDescOnce.Do(func() {
		file_nebius_kms_v1_asymmetric_key_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nebius_kms_v1_asymmetric_key_service_proto_rawDesc), len(file_nebius_kms_v1_asymmetric_key_service_proto_rawDesc)))
	})
	return file_nebius_kms_v1_asymmetric_key_service_proto_rawDescData
}

var file_nebius_kms_v1_asymmetric_key_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_nebius_kms_v1_asymmetric_key_service_proto_goTypes = []any{
	(*CreateAsymmetricKeyRequest)(nil),              // 0: nebius.kms.v1.CreateAsymmetricKeyRequest
	(*UpdateAsymmetricKeyRequest)(nil),              // 1: nebius.kms.v1.UpdateAsymmetricKeyRequest
	(*GetAsymmetricKeyRequest)(nil),                 // 2: nebius.kms.v1.GetAsymmetricKeyRequest
	(*GetAsymmetricKeyByNameRequest)(nil),           // 3: nebius.kms.v1.GetAsymmetricKeyByNameRequest
	(*ListAsymmetricKeysRequest)(nil),               // 4: nebius.kms.v1.ListAsymmetricKeysRequest
	(*ListAsymmetricKeysResponse)(nil),              // 5: nebius.kms.v1.ListAsymmetricKeysResponse
	(*DeleteAsymmetricKeyRequest)(nil),              // 6: nebius.kms.v1.DeleteAsymmetricKeyRequest
	(*UpdateAsymmetricKeyDeletionDelayRequest)(nil), // 7: nebius.kms.v1.UpdateAsymmetricKeyDeletionDelayRequest
	(*UndeleteAsymmetricKeyRequest)(nil),            // 8: nebius.kms.v1.UndeleteAsymmetricKeyRequest
	(*v1.ResourceMetadata)(nil),                     // 9: nebius.common.v1.ResourceMetadata
	(*AsymmetricKeySpec)(nil),                       // 10: nebius.kms.v1.AsymmetricKeySpec
	(*AsymmetricKey)(nil),                           // 11: nebius.kms.v1.AsymmetricKey
	(*durationpb.Duration)(nil),                     // 12: google.protobuf.Duration
	(*v1.Operation)(nil),                            // 13: nebius.common.v1.Operation
}
var file_nebius_kms_v1_asymmetric_key_service_proto_depIdxs = []int32{
	9,  // 0: nebius.kms.v1.CreateAsymmetricKeyRequest.metadata:type_name -> nebius.common.v1.ResourceMetadata
	10, // 1: nebius.kms.v1.CreateAsymmetricKeyRequest.spec:type_name -> nebius.kms.v1.AsymmetricKeySpec
	9,  // 2: nebius.kms.v1.UpdateAsymmetricKeyRequest.metadata:type_name -> nebius.common.v1.ResourceMetadata
	10, // 3: nebius.kms.v1.UpdateAsymmetricKeyRequest.spec:type_name -> nebius.kms.v1.AsymmetricKeySpec
	11, // 4: nebius.kms.v1.ListAsymmetricKeysResponse.items:type_name -> nebius.kms.v1.AsymmetricKey
	12, // 5: nebius.kms.v1.UpdateAsymmetricKeyDeletionDelayRequest.deletion_delay:type_name -> google.protobuf.Duration
	0,  // 6: nebius.kms.v1.AsymmetricKeyService.Create:input_type -> nebius.kms.v1.CreateAsymmetricKeyRequest
	1,  // 7: nebius.kms.v1.AsymmetricKeyService.Update:input_type -> nebius.kms.v1.UpdateAsymmetricKeyRequest
	2,  // 8: nebius.kms.v1.AsymmetricKeyService.Get:input_type -> nebius.kms.v1.GetAsymmetricKeyRequest
	3,  // 9: nebius.kms.v1.AsymmetricKeyService.GetByName:input_type -> nebius.kms.v1.GetAsymmetricKeyByNameRequest
	4,  // 10: nebius.kms.v1.AsymmetricKeyService.List:input_type -> nebius.kms.v1.ListAsymmetricKeysRequest
	6,  // 11: nebius.kms.v1.AsymmetricKeyService.Delete:input_type -> nebius.kms.v1.DeleteAsymmetricKeyRequest
	7,  // 12: nebius.kms.v1.AsymmetricKeyService.UpdateDeletionDelay:input_type -> nebius.kms.v1.UpdateAsymmetricKeyDeletionDelayRequest
	8,  // 13: nebius.kms.v1.AsymmetricKeyService.Undelete:input_type -> nebius.kms.v1.UndeleteAsymmetricKeyRequest
	13, // 14: nebius.kms.v1.AsymmetricKeyService.Create:output_type -> nebius.common.v1.Operation
	13, // 15: nebius.kms.v1.AsymmetricKeyService.Update:output_type -> nebius.common.v1.Operation
	11, // 16: nebius.kms.v1.AsymmetricKeyService.Get:output_type -> nebius.kms.v1.AsymmetricKey
	11, // 17: nebius.kms.v1.AsymmetricKeyService.GetByName:output_type -> nebius.kms.v1.AsymmetricKey
	5,  // 18: nebius.kms.v1.AsymmetricKeyService.List:output_type -> nebius.kms.v1.ListAsymmetricKeysResponse
	13, // 19: nebius.kms.v1.AsymmetricKeyService.Delete:output_type -> nebius.common.v1.Operation
	13, // 20: nebius.kms.v1.AsymmetricKeyService.UpdateDeletionDelay:output_type -> nebius.common.v1.Operation
	13, // 21: nebius.kms.v1.AsymmetricKeyService.Undelete:output_type -> nebius.common.v1.Operation
	14, // [14:22] is the sub-list for method output_type
	6,  // [6:14] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_nebius_kms_v1_asymmetric_key_service_proto_init() }
func file_nebius_kms_v1_asymmetric_key_service_proto_init() {
	if File_nebius_kms_v1_asymmetric_key_service_proto != nil {
		return
	}
	file_nebius_kms_v1_asymmetric_key_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nebius_kms_v1_asymmetric_key_service_proto_rawDesc), len(file_nebius_kms_v1_asymmetric_key_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nebius_kms_v1_asymmetric_key_service_proto_goTypes,
		DependencyIndexes: file_nebius_kms_v1_asymmetric_key_service_proto_depIdxs,
		MessageInfos:      file_nebius_kms_v1_asymmetric_key_service_proto_msgTypes,
	}.Build()
	File_nebius_kms_v1_asymmetric_key_service_proto = out.File
	file_nebius_kms_v1_asymmetric_key_service_proto_goTypes = nil
	file_nebius_kms_v1_asymmetric_key_service_proto_depIdxs = nil
}
