// Code generated by protoc-gen-sensitive. DO NOT EDIT.

package v1

// func (x *SymmetricKey) Sanitize()            // is not generated as no sensitive fields found
// func (x *SymmetricKey) LogValue() slog.Value // is not generated as no sensitive fields found

// func (x *SymmetricKeySpec) Sanitize()            // is not generated as no sensitive fields found
// func (x *SymmetricKeySpec) LogValue() slog.Value // is not generated as no sensitive fields found

// func (x *SymmetricKeyStatus) Sanitize()            // is not generated as no sensitive fields found
// func (x *SymmetricKeyStatus) LogValue() slog.Value // is not generated as no sensitive fields found
