// Code generated by MockGen. DO NOT EDIT.
// Source: services/nebius/capacity/v1/capacity_block_group_service.sdk.go
//
// Generated by this command:
//
//	mockgen -source services/nebius/capacity/v1/capacity_block_group_service.sdk.go -package v1 -typed
//

// Package v1 is a generated GoMock package.
package v1

import (
	context "context"
	reflect "reflect"

	iter "github.com/nebius/gosdk/iter"
	v1 "github.com/nebius/gosdk/proto/nebius/capacity/v1"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockCapacityBlockGroupService is a mock of CapacityBlockGroupService interface.
type MockCapacityBlockGroupService struct {
	ctrl     *gomock.Controller
	recorder *MockCapacityBlockGroupServiceMockRecorder
}

// MockCapacityBlockGroupServiceMockRecorder is the mock recorder for MockCapacityBlockGroupService.
type MockCapacityBlockGroupServiceMockRecorder struct {
	mock *MockCapacityBlockGroupService
}

// NewMockCapacityBlockGroupService creates a new mock instance.
func NewMockCapacityBlockGroupService(ctrl *gomock.Controller) *MockCapacityBlockGroupService {
	mock := &MockCapacityBlockGroupService{ctrl: ctrl}
	mock.recorder = &MockCapacityBlockGroupServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCapacityBlockGroupService) EXPECT() *MockCapacityBlockGroupServiceMockRecorder {
	return m.recorder
}

// Filter mocks base method.
func (m *MockCapacityBlockGroupService) Filter(arg0 context.Context, arg1 *v1.ListCapacityBlockGroupsRequest, arg2 ...grpc.CallOption) iter.Seq2[*v1.CapacityBlockGroup, error] {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Filter", varargs...)
	ret0, _ := ret[0].(iter.Seq2[*v1.CapacityBlockGroup, error])
	return ret0
}

// Filter indicates an expected call of Filter.
func (mr *MockCapacityBlockGroupServiceMockRecorder) Filter(arg0, arg1 any, arg2 ...any) *MockCapacityBlockGroupServiceFilterCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Filter", reflect.TypeOf((*MockCapacityBlockGroupService)(nil).Filter), varargs...)
	return &MockCapacityBlockGroupServiceFilterCall{Call: call}
}

// MockCapacityBlockGroupServiceFilterCall wrap *gomock.Call
type MockCapacityBlockGroupServiceFilterCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCapacityBlockGroupServiceFilterCall) Return(arg0 iter.Seq2[*v1.CapacityBlockGroup, error]) *MockCapacityBlockGroupServiceFilterCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCapacityBlockGroupServiceFilterCall) Do(f func(context.Context, *v1.ListCapacityBlockGroupsRequest, ...grpc.CallOption) iter.Seq2[*v1.CapacityBlockGroup, error]) *MockCapacityBlockGroupServiceFilterCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCapacityBlockGroupServiceFilterCall) DoAndReturn(f func(context.Context, *v1.ListCapacityBlockGroupsRequest, ...grpc.CallOption) iter.Seq2[*v1.CapacityBlockGroup, error]) *MockCapacityBlockGroupServiceFilterCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Get mocks base method.
func (m *MockCapacityBlockGroupService) Get(arg0 context.Context, arg1 *v1.GetCapacityBlockGroupRequest, arg2 ...grpc.CallOption) (*v1.CapacityBlockGroup, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(*v1.CapacityBlockGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCapacityBlockGroupServiceMockRecorder) Get(arg0, arg1 any, arg2 ...any) *MockCapacityBlockGroupServiceGetCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCapacityBlockGroupService)(nil).Get), varargs...)
	return &MockCapacityBlockGroupServiceGetCall{Call: call}
}

// MockCapacityBlockGroupServiceGetCall wrap *gomock.Call
type MockCapacityBlockGroupServiceGetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCapacityBlockGroupServiceGetCall) Return(arg0 *v1.CapacityBlockGroup, arg1 error) *MockCapacityBlockGroupServiceGetCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCapacityBlockGroupServiceGetCall) Do(f func(context.Context, *v1.GetCapacityBlockGroupRequest, ...grpc.CallOption) (*v1.CapacityBlockGroup, error)) *MockCapacityBlockGroupServiceGetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCapacityBlockGroupServiceGetCall) DoAndReturn(f func(context.Context, *v1.GetCapacityBlockGroupRequest, ...grpc.CallOption) (*v1.CapacityBlockGroup, error)) *MockCapacityBlockGroupServiceGetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByResourceAffinity mocks base method.
func (m *MockCapacityBlockGroupService) GetByResourceAffinity(arg0 context.Context, arg1 *v1.GetCapacityBlockGroupByResourceAffinityRequest, arg2 ...grpc.CallOption) (*v1.CapacityBlockGroup, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetByResourceAffinity", varargs...)
	ret0, _ := ret[0].(*v1.CapacityBlockGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByResourceAffinity indicates an expected call of GetByResourceAffinity.
func (mr *MockCapacityBlockGroupServiceMockRecorder) GetByResourceAffinity(arg0, arg1 any, arg2 ...any) *MockCapacityBlockGroupServiceGetByResourceAffinityCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByResourceAffinity", reflect.TypeOf((*MockCapacityBlockGroupService)(nil).GetByResourceAffinity), varargs...)
	return &MockCapacityBlockGroupServiceGetByResourceAffinityCall{Call: call}
}

// MockCapacityBlockGroupServiceGetByResourceAffinityCall wrap *gomock.Call
type MockCapacityBlockGroupServiceGetByResourceAffinityCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCapacityBlockGroupServiceGetByResourceAffinityCall) Return(arg0 *v1.CapacityBlockGroup, arg1 error) *MockCapacityBlockGroupServiceGetByResourceAffinityCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCapacityBlockGroupServiceGetByResourceAffinityCall) Do(f func(context.Context, *v1.GetCapacityBlockGroupByResourceAffinityRequest, ...grpc.CallOption) (*v1.CapacityBlockGroup, error)) *MockCapacityBlockGroupServiceGetByResourceAffinityCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCapacityBlockGroupServiceGetByResourceAffinityCall) DoAndReturn(f func(context.Context, *v1.GetCapacityBlockGroupByResourceAffinityRequest, ...grpc.CallOption) (*v1.CapacityBlockGroup, error)) *MockCapacityBlockGroupServiceGetByResourceAffinityCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// List mocks base method.
func (m *MockCapacityBlockGroupService) List(arg0 context.Context, arg1 *v1.ListCapacityBlockGroupsRequest, arg2 ...grpc.CallOption) (*v1.ListCapacityBlockGroupsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].(*v1.ListCapacityBlockGroupsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockCapacityBlockGroupServiceMockRecorder) List(arg0, arg1 any, arg2 ...any) *MockCapacityBlockGroupServiceListCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockCapacityBlockGroupService)(nil).List), varargs...)
	return &MockCapacityBlockGroupServiceListCall{Call: call}
}

// MockCapacityBlockGroupServiceListCall wrap *gomock.Call
type MockCapacityBlockGroupServiceListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCapacityBlockGroupServiceListCall) Return(arg0 *v1.ListCapacityBlockGroupsResponse, arg1 error) *MockCapacityBlockGroupServiceListCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCapacityBlockGroupServiceListCall) Do(f func(context.Context, *v1.ListCapacityBlockGroupsRequest, ...grpc.CallOption) (*v1.ListCapacityBlockGroupsResponse, error)) *MockCapacityBlockGroupServiceListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCapacityBlockGroupServiceListCall) DoAndReturn(f func(context.Context, *v1.ListCapacityBlockGroupsRequest, ...grpc.CallOption) (*v1.ListCapacityBlockGroupsResponse, error)) *MockCapacityBlockGroupServiceListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListResources mocks base method.
func (m *MockCapacityBlockGroupService) ListResources(arg0 context.Context, arg1 *v1.ListCapacityBlockGroupResourcesRequest, arg2 ...grpc.CallOption) (*v1.ListCapacityBlockGroupResourcesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListResources", varargs...)
	ret0, _ := ret[0].(*v1.ListCapacityBlockGroupResourcesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListResources indicates an expected call of ListResources.
func (mr *MockCapacityBlockGroupServiceMockRecorder) ListResources(arg0, arg1 any, arg2 ...any) *MockCapacityBlockGroupServiceListResourcesCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListResources", reflect.TypeOf((*MockCapacityBlockGroupService)(nil).ListResources), varargs...)
	return &MockCapacityBlockGroupServiceListResourcesCall{Call: call}
}

// MockCapacityBlockGroupServiceListResourcesCall wrap *gomock.Call
type MockCapacityBlockGroupServiceListResourcesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCapacityBlockGroupServiceListResourcesCall) Return(arg0 *v1.ListCapacityBlockGroupResourcesResponse, arg1 error) *MockCapacityBlockGroupServiceListResourcesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCapacityBlockGroupServiceListResourcesCall) Do(f func(context.Context, *v1.ListCapacityBlockGroupResourcesRequest, ...grpc.CallOption) (*v1.ListCapacityBlockGroupResourcesResponse, error)) *MockCapacityBlockGroupServiceListResourcesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCapacityBlockGroupServiceListResourcesCall) DoAndReturn(f func(context.Context, *v1.ListCapacityBlockGroupResourcesRequest, ...grpc.CallOption) (*v1.ListCapacityBlockGroupResourcesResponse, error)) *MockCapacityBlockGroupServiceListResourcesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
