// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.3
// nebius/compute/v1alpha1/image_service.proto is a deprecated file.

package v1alpha1

import (
	_ "github.com/nebius/gosdk/proto/nebius"
	v1 "github.com/nebius/gosdk/proto/nebius/common/v1"
	v1alpha1 "github.com/nebius/gosdk/proto/nebius/common/v1alpha1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Deprecated: The entire proto file nebius/compute/v1alpha1/image_service.proto is marked as deprecated.
type GetImageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Deprecated: The entire proto file nebius/compute/v1alpha1/image_service.proto is marked as deprecated.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetImageRequest) Reset() {
	*x = GetImageRequest{}
	mi := &file_nebius_compute_v1alpha1_image_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImageRequest) ProtoMessage() {}

func (x *GetImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nebius_compute_v1alpha1_image_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImageRequest.ProtoReflect.Descriptor instead.
func (*GetImageRequest) Descriptor() ([]byte, []int) {
	return file_nebius_compute_v1alpha1_image_service_proto_rawDescGZIP(), []int{0}
}

// Deprecated: The entire proto file nebius/compute/v1alpha1/image_service.proto is marked as deprecated.
func (x *GetImageRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Deprecated: The entire proto file nebius/compute/v1alpha1/image_service.proto is marked as deprecated.
type GetImageLatestByFamilyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Deprecated: The entire proto file nebius/compute/v1alpha1/image_service.proto is marked as deprecated.
	ImageFamily string `protobuf:"bytes,1,opt,name=image_family,json=imageFamily,proto3" json:"image_family,omitempty"`
	// Deprecated: The entire proto file nebius/compute/v1alpha1/image_service.proto is marked as deprecated.
	ParentId      string `protobuf:"bytes,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"` // default 'project-{region}public-images'
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetImageLatestByFamilyRequest) Reset() {
	*x = GetImageLatestByFamilyRequest{}
	mi := &file_nebius_compute_v1alpha1_image_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetImageLatestByFamilyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImageLatestByFamilyRequest) ProtoMessage() {}

func (x *GetImageLatestByFamilyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nebius_compute_v1alpha1_image_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImageLatestByFamilyRequest.ProtoReflect.Descriptor instead.
func (*GetImageLatestByFamilyRequest) Descriptor() ([]byte, []int) {
	return file_nebius_compute_v1alpha1_image_service_proto_rawDescGZIP(), []int{1}
}

// Deprecated: The entire proto file nebius/compute/v1alpha1/image_service.proto is marked as deprecated.
func (x *GetImageLatestByFamilyRequest) GetImageFamily() string {
	if x != nil {
		return x.ImageFamily
	}
	return ""
}

// Deprecated: The entire proto file nebius/compute/v1alpha1/image_service.proto is marked as deprecated.
func (x *GetImageLatestByFamilyRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

// Deprecated: The entire proto file nebius/compute/v1alpha1/image_service.proto is marked as deprecated.
type ListImagesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Deprecated: The entire proto file nebius/compute/v1alpha1/image_service.proto is marked as deprecated.
	ParentId string `protobuf:"bytes,1,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	// Deprecated: The entire proto file nebius/compute/v1alpha1/image_service.proto is marked as deprecated.
	PageSize int64 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Deprecated: The entire proto file nebius/compute/v1alpha1/image_service.proto is marked as deprecated.
	PageToken string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Deprecated: The entire proto file nebius/compute/v1alpha1/image_service.proto is marked as deprecated.
	Filter        string `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListImagesRequest) Reset() {
	*x = ListImagesRequest{}
	mi := &file_nebius_compute_v1alpha1_image_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListImagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListImagesRequest) ProtoMessage() {}

func (x *ListImagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nebius_compute_v1alpha1_image_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListImagesRequest.ProtoReflect.Descriptor instead.
func (*ListImagesRequest) Descriptor() ([]byte, []int) {
	return file_nebius_compute_v1alpha1_image_service_proto_rawDescGZIP(), []int{2}
}

// Deprecated: The entire proto file nebius/compute/v1alpha1/image_service.proto is marked as deprecated.
func (x *ListImagesRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

// Deprecated: The entire proto file nebius/compute/v1alpha1/image_service.proto is marked as deprecated.
func (x *ListImagesRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// Deprecated: The entire proto file nebius/compute/v1alpha1/image_service.proto is marked as deprecated.
func (x *ListImagesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// Deprecated: The entire proto file nebius/compute/v1alpha1/image_service.proto is marked as deprecated.
func (x *ListImagesRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

// Deprecated: The entire proto file nebius/compute/v1alpha1/image_service.proto is marked as deprecated.
type ListImagesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Deprecated: The entire proto file nebius/compute/v1alpha1/image_service.proto is marked as deprecated.
	Items []*Image `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	// Deprecated: The entire proto file nebius/compute/v1alpha1/image_service.proto is marked as deprecated.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListImagesResponse) Reset() {
	*x = ListImagesResponse{}
	mi := &file_nebius_compute_v1alpha1_image_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListImagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListImagesResponse) ProtoMessage() {}

func (x *ListImagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nebius_compute_v1alpha1_image_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListImagesResponse.ProtoReflect.Descriptor instead.
func (*ListImagesResponse) Descriptor() ([]byte, []int) {
	return file_nebius_compute_v1alpha1_image_service_proto_rawDescGZIP(), []int{3}
}

// Deprecated: The entire proto file nebius/compute/v1alpha1/image_service.proto is marked as deprecated.
func (x *ListImagesResponse) GetItems() []*Image {
	if x != nil {
		return x.Items
	}
	return nil
}

// Deprecated: The entire proto file nebius/compute/v1alpha1/image_service.proto is marked as deprecated.
func (x *ListImagesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_nebius_compute_v1alpha1_image_service_proto protoreflect.FileDescriptor

const file_nebius_compute_v1alpha1_image_service_proto_rawDesc = "" +
	"\n" +
	"+nebius/compute/v1alpha1/image_service.proto\x12\x17nebius.compute.v1alpha1\x1a\x18nebius/annotations.proto\x1a\x1fnebius/common/v1/metadata.proto\x1a.nebius/common/v1alpha1/operation_service.proto\x1a#nebius/compute/v1alpha1/image.proto\"!\n" +
	"\x0fGetImageRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"_\n" +
	"\x1dGetImageLatestByFamilyRequest\x12!\n" +
	"\fimage_family\x18\x01 \x01(\tR\vimageFamily\x12\x1b\n" +
	"\tparent_id\x18\x02 \x01(\tR\bparentId\"\xd6\x01\n" +
	"\x11ListImagesRequest\x12\x1b\n" +
	"\tparent_id\x18\x01 \x01(\tR\bparentId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\x12h\n" +
	"\x06filter\x18\x04 \x01(\tBP\xd2JK\n" +
	"\n" +
	"2025-06-16\x12=it is not implemented, filtering could be done on client side\x18\x01R\x06filter\"r\n" +
	"\x12ListImagesResponse\x124\n" +
	"\x05items\x18\x01 \x03(\v2\x1e.nebius.compute.v1alpha1.ImageR\x05items\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken2\x8e\x04\n" +
	"\fImageService\x12O\n" +
	"\x03Get\x12(.nebius.compute.v1alpha1.GetImageRequest\x1a\x1e.nebius.compute.v1alpha1.Image\x12O\n" +
	"\tGetByName\x12\".nebius.common.v1.GetByNameRequest\x1a\x1e.nebius.compute.v1alpha1.Image\x12k\n" +
	"\x11GetLatestByFamily\x126.nebius.compute.v1alpha1.GetImageLatestByFamilyRequest\x1a\x1e.nebius.compute.v1alpha1.Image\x12_\n" +
	"\x04List\x12*.nebius.compute.v1alpha1.ListImagesRequest\x1a+.nebius.compute.v1alpha1.ListImagesResponse\x12\x7f\n" +
	"\x16ListOperationsByParent\x125.nebius.common.v1alpha1.ListOperationsByParentRequest\x1a..nebius.common.v1alpha1.ListOperationsResponse\x1a\r\xbaJ\acompute\x88\x02\x01Bo\n" +
	"\x1eai.nebius.pub.compute.v1alpha1B\x11ImageServiceProtoP\x01Z5github.com/nebius/gosdk/proto/nebius/compute/v1alpha1\xb8\x01\x01b\x06proto3"

var (
	file_nebius_compute_v1alpha1_image_service_proto_rawDescOnce sync.Once
	file_nebius_compute_v1alpha1_image_service_proto_rawDescData []byte
)

func file_nebius_compute_v1alpha1_image_service_proto_rawDescGZIP() []byte {
	file_nebius_compute_v1alpha1_image_service_proto_rawDescOnce.Do(func() {
		file_nebius_compute_v1alpha1_image_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nebius_compute_v1alpha1_image_service_proto_rawDesc), len(file_nebius_compute_v1alpha1_image_service_proto_rawDesc)))
	})
	return file_nebius_compute_v1alpha1_image_service_proto_rawDescData
}

var file_nebius_compute_v1alpha1_image_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_nebius_compute_v1alpha1_image_service_proto_goTypes = []any{
	(*GetImageRequest)(nil),                        // 0: nebius.compute.v1alpha1.GetImageRequest
	(*GetImageLatestByFamilyRequest)(nil),          // 1: nebius.compute.v1alpha1.GetImageLatestByFamilyRequest
	(*ListImagesRequest)(nil),                      // 2: nebius.compute.v1alpha1.ListImagesRequest
	(*ListImagesResponse)(nil),                     // 3: nebius.compute.v1alpha1.ListImagesResponse
	(*Image)(nil),                                  // 4: nebius.compute.v1alpha1.Image
	(*v1.GetByNameRequest)(nil),                    // 5: nebius.common.v1.GetByNameRequest
	(*v1alpha1.ListOperationsByParentRequest)(nil), // 6: nebius.common.v1alpha1.ListOperationsByParentRequest
	(*v1alpha1.ListOperationsResponse)(nil),        // 7: nebius.common.v1alpha1.ListOperationsResponse
}
var file_nebius_compute_v1alpha1_image_service_proto_depIdxs = []int32{
	4, // 0: nebius.compute.v1alpha1.ListImagesResponse.items:type_name -> nebius.compute.v1alpha1.Image
	0, // 1: nebius.compute.v1alpha1.ImageService.Get:input_type -> nebius.compute.v1alpha1.GetImageRequest
	5, // 2: nebius.compute.v1alpha1.ImageService.GetByName:input_type -> nebius.common.v1.GetByNameRequest
	1, // 3: nebius.compute.v1alpha1.ImageService.GetLatestByFamily:input_type -> nebius.compute.v1alpha1.GetImageLatestByFamilyRequest
	2, // 4: nebius.compute.v1alpha1.ImageService.List:input_type -> nebius.compute.v1alpha1.ListImagesRequest
	6, // 5: nebius.compute.v1alpha1.ImageService.ListOperationsByParent:input_type -> nebius.common.v1alpha1.ListOperationsByParentRequest
	4, // 6: nebius.compute.v1alpha1.ImageService.Get:output_type -> nebius.compute.v1alpha1.Image
	4, // 7: nebius.compute.v1alpha1.ImageService.GetByName:output_type -> nebius.compute.v1alpha1.Image
	4, // 8: nebius.compute.v1alpha1.ImageService.GetLatestByFamily:output_type -> nebius.compute.v1alpha1.Image
	3, // 9: nebius.compute.v1alpha1.ImageService.List:output_type -> nebius.compute.v1alpha1.ListImagesResponse
	7, // 10: nebius.compute.v1alpha1.ImageService.ListOperationsByParent:output_type -> nebius.common.v1alpha1.ListOperationsResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_nebius_compute_v1alpha1_image_service_proto_init() }
func file_nebius_compute_v1alpha1_image_service_proto_init() {
	if File_nebius_compute_v1alpha1_image_service_proto != nil {
		return
	}
	file_nebius_compute_v1alpha1_image_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nebius_compute_v1alpha1_image_service_proto_rawDesc), len(file_nebius_compute_v1alpha1_image_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nebius_compute_v1alpha1_image_service_proto_goTypes,
		DependencyIndexes: file_nebius_compute_v1alpha1_image_service_proto_depIdxs,
		MessageInfos:      file_nebius_compute_v1alpha1_image_service_proto_msgTypes,
	}.Build()
	File_nebius_compute_v1alpha1_image_service_proto = out.File
	file_nebius_compute_v1alpha1_image_service_proto_goTypes = nil
	file_nebius_compute_v1alpha1_image_service_proto_depIdxs = nil
}
