// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.3
// source: nebius/vpc/v1/allocation_service.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/nebius/gosdk/proto/nebius"
	v1 "github.com/nebius/gosdk/proto/nebius/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAllocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllocationRequest) Reset() {
	*x = GetAllocationRequest{}
	mi := &file_nebius_vpc_v1_allocation_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllocationRequest) ProtoMessage() {}

func (x *GetAllocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nebius_vpc_v1_allocation_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllocationRequest.ProtoReflect.Descriptor instead.
func (*GetAllocationRequest) Descriptor() ([]byte, []int) {
	return file_nebius_vpc_v1_allocation_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetAllocationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAllocationByNameRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the project.
	ParentId      string `protobuf:"bytes,1,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllocationByNameRequest) Reset() {
	*x = GetAllocationByNameRequest{}
	mi := &file_nebius_vpc_v1_allocation_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllocationByNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllocationByNameRequest) ProtoMessage() {}

func (x *GetAllocationByNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nebius_vpc_v1_allocation_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllocationByNameRequest.ProtoReflect.Descriptor instead.
func (*GetAllocationByNameRequest) Descriptor() ([]byte, []int) {
	return file_nebius_vpc_v1_allocation_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetAllocationByNameRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *GetAllocationByNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListAllocationsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the project.
	ParentId      string `protobuf:"bytes,1,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	PageSize      int64  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAllocationsRequest) Reset() {
	*x = ListAllocationsRequest{}
	mi := &file_nebius_vpc_v1_allocation_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllocationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllocationsRequest) ProtoMessage() {}

func (x *ListAllocationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nebius_vpc_v1_allocation_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllocationsRequest.ProtoReflect.Descriptor instead.
func (*ListAllocationsRequest) Descriptor() ([]byte, []int) {
	return file_nebius_vpc_v1_allocation_service_proto_rawDescGZIP(), []int{2}
}

func (x *ListAllocationsRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *ListAllocationsRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListAllocationsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListAllocationsByPoolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PoolId        string                 `protobuf:"bytes,1,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	PageSize      int64                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAllocationsByPoolRequest) Reset() {
	*x = ListAllocationsByPoolRequest{}
	mi := &file_nebius_vpc_v1_allocation_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllocationsByPoolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllocationsByPoolRequest) ProtoMessage() {}

func (x *ListAllocationsByPoolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nebius_vpc_v1_allocation_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllocationsByPoolRequest.ProtoReflect.Descriptor instead.
func (*ListAllocationsByPoolRequest) Descriptor() ([]byte, []int) {
	return file_nebius_vpc_v1_allocation_service_proto_rawDescGZIP(), []int{3}
}

func (x *ListAllocationsByPoolRequest) GetPoolId() string {
	if x != nil {
		return x.PoolId
	}
	return ""
}

func (x *ListAllocationsByPoolRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListAllocationsByPoolRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListAllocationsBySubnetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubnetId      string                 `protobuf:"bytes,1,opt,name=subnet_id,json=subnetId,proto3" json:"subnet_id,omitempty"`
	PageSize      int64                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAllocationsBySubnetRequest) Reset() {
	*x = ListAllocationsBySubnetRequest{}
	mi := &file_nebius_vpc_v1_allocation_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllocationsBySubnetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllocationsBySubnetRequest) ProtoMessage() {}

func (x *ListAllocationsBySubnetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nebius_vpc_v1_allocation_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllocationsBySubnetRequest.ProtoReflect.Descriptor instead.
func (*ListAllocationsBySubnetRequest) Descriptor() ([]byte, []int) {
	return file_nebius_vpc_v1_allocation_service_proto_rawDescGZIP(), []int{4}
}

func (x *ListAllocationsBySubnetRequest) GetSubnetId() string {
	if x != nil {
		return x.SubnetId
	}
	return ""
}

func (x *ListAllocationsBySubnetRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListAllocationsBySubnetRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListAllocationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Allocation          `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAllocationsResponse) Reset() {
	*x = ListAllocationsResponse{}
	mi := &file_nebius_vpc_v1_allocation_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllocationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllocationsResponse) ProtoMessage() {}

func (x *ListAllocationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nebius_vpc_v1_allocation_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllocationsResponse.ProtoReflect.Descriptor instead.
func (*ListAllocationsResponse) Descriptor() ([]byte, []int) {
	return file_nebius_vpc_v1_allocation_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListAllocationsResponse) GetItems() []*Allocation {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListAllocationsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type CreateAllocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *v1.ResourceMetadata   `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Spec          *AllocationSpec        `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAllocationRequest) Reset() {
	*x = CreateAllocationRequest{}
	mi := &file_nebius_vpc_v1_allocation_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAllocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAllocationRequest) ProtoMessage() {}

func (x *CreateAllocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nebius_vpc_v1_allocation_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAllocationRequest.ProtoReflect.Descriptor instead.
func (*CreateAllocationRequest) Descriptor() ([]byte, []int) {
	return file_nebius_vpc_v1_allocation_service_proto_rawDescGZIP(), []int{6}
}

func (x *CreateAllocationRequest) GetMetadata() *v1.ResourceMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CreateAllocationRequest) GetSpec() *AllocationSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type UpdateAllocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *v1.ResourceMetadata   `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Spec          *AllocationSpec        `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAllocationRequest) Reset() {
	*x = UpdateAllocationRequest{}
	mi := &file_nebius_vpc_v1_allocation_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAllocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAllocationRequest) ProtoMessage() {}

func (x *UpdateAllocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nebius_vpc_v1_allocation_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAllocationRequest.ProtoReflect.Descriptor instead.
func (*UpdateAllocationRequest) Descriptor() ([]byte, []int) {
	return file_nebius_vpc_v1_allocation_service_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateAllocationRequest) GetMetadata() *v1.ResourceMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *UpdateAllocationRequest) GetSpec() *AllocationSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type DeleteAllocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAllocationRequest) Reset() {
	*x = DeleteAllocationRequest{}
	mi := &file_nebius_vpc_v1_allocation_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAllocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAllocationRequest) ProtoMessage() {}

func (x *DeleteAllocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nebius_vpc_v1_allocation_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAllocationRequest.ProtoReflect.Descriptor instead.
func (*DeleteAllocationRequest) Descriptor() ([]byte, []int) {
	return file_nebius_vpc_v1_allocation_service_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteAllocationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_nebius_vpc_v1_allocation_service_proto protoreflect.FileDescriptor

const file_nebius_vpc_v1_allocation_service_proto_rawDesc = "" +
	"\n" +
	"&nebius/vpc/v1/allocation_service.proto\x12\rnebius.vpc.v1\x1a\x1bbuf/validate/validate.proto\x1a\x18nebius/annotations.proto\x1a\x1fnebius/common/v1/metadata.proto\x1a nebius/common/v1/operation.proto\x1a\x1enebius/vpc/v1/allocation.proto\".\n" +
	"\x14GetAllocationRequest\x12\x16\n" +
	"\x02id\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x02id\"]\n" +
	"\x1aGetAllocationByNameRequest\x12#\n" +
	"\tparent_id\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\bparentId\x12\x1a\n" +
	"\x04name\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x04name\"y\n" +
	"\x16ListAllocationsRequest\x12#\n" +
	"\tparent_id\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\bparentId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"\x87\x01\n" +
	"\x1cListAllocationsByPoolRequest\x12+\n" +
	"\apool_id\x18\x01 \x01(\tB\x12\xbaH\x03\xc8\x01\x01\xe2J\t\n" +
	"\avpcpoolR\x06poolId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"\x8f\x01\n" +
	"\x1eListAllocationsBySubnetRequest\x121\n" +
	"\tsubnet_id\x18\x01 \x01(\tB\x14\xbaH\x03\xc8\x01\x01\xe2J\v\n" +
	"\tvpcsubnetR\bsubnetId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"r\n" +
	"\x17ListAllocationsResponse\x12/\n" +
	"\x05items\x18\x01 \x03(\v2\x19.nebius.vpc.v1.AllocationR\x05items\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xe1\x02\n" +
	"\x17CreateAllocationRequest\x12\x8a\x02\n" +
	"\bmetadata\x18\x01 \x01(\v2\".nebius.common.v1.ResourceMetadataB\xc9\x01\xbaH\xc5\x01\xba\x01\xbe\x01\n" +
	"\rmetadata_name\x12s'name' must start with a letter or digit, allow '-', '_', '.', '/', and have a length between 2 and 255 characters.\x1a8this.name.matches('^[a-zA-Z0-9][-_./a-zA-Z0-9]{1,254}$')\xc8\x01\x01R\bmetadata\x129\n" +
	"\x04spec\x18\x02 \x01(\v2\x1d.nebius.vpc.v1.AllocationSpecB\x06\xbaH\x03\xc8\x01\x01R\x04spec\"\xd6\x02\n" +
	"\x17UpdateAllocationRequest\x12\x87\x02\n" +
	"\bmetadata\x18\x01 \x01(\v2\".nebius.common.v1.ResourceMetadataB\xc6\x01\xbaH\xc2\x01\xba\x01\xbe\x01\n" +
	"\rmetadata_name\x12s'name' must start with a letter or digit, allow '-', '_', '.', '/', and have a length between 2 and 255 characters.\x1a8this.name.matches('^[a-zA-Z0-9][-_./a-zA-Z0-9]{1,254}$')R\bmetadata\x121\n" +
	"\x04spec\x18\x02 \x01(\v2\x1d.nebius.vpc.v1.AllocationSpecR\x04spec\"1\n" +
	"\x17DeleteAllocationRequest\x12\x16\n" +
	"\x02id\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x02id2\xc3\x05\n" +
	"\x11AllocationService\x12E\n" +
	"\x03Get\x12#.nebius.vpc.v1.GetAllocationRequest\x1a\x19.nebius.vpc.v1.Allocation\x12Q\n" +
	"\tGetByName\x12).nebius.vpc.v1.GetAllocationByNameRequest\x1a\x19.nebius.vpc.v1.Allocation\x12U\n" +
	"\x04List\x12%.nebius.vpc.v1.ListAllocationsRequest\x1a&.nebius.vpc.v1.ListAllocationsResponse\x12a\n" +
	"\n" +
	"ListByPool\x12+.nebius.vpc.v1.ListAllocationsByPoolRequest\x1a&.nebius.vpc.v1.ListAllocationsResponse\x12e\n" +
	"\fListBySubnet\x12-.nebius.vpc.v1.ListAllocationsBySubnetRequest\x1a&.nebius.vpc.v1.ListAllocationsResponse\x12M\n" +
	"\x06Create\x12&.nebius.vpc.v1.CreateAllocationRequest\x1a\x1b.nebius.common.v1.Operation\x12M\n" +
	"\x06Update\x12&.nebius.vpc.v1.UpdateAllocationRequest\x1a\x1b.nebius.common.v1.Operation\x12M\n" +
	"\x06Delete\x12&.nebius.vpc.v1.DeleteAllocationRequest\x1a\x1b.nebius.common.v1.Operation\x1a\x06\xbaJ\x03vpcB]\n" +
	"\x14ai.nebius.pub.vpc.v1B\x16AllocationServiceProtoP\x01Z+github.com/nebius/gosdk/proto/nebius/vpc/v1b\x06proto3"

var (
	file_nebius_vpc_v1_allocation_service_proto_rawDescOnce sync.Once
	file_nebius_vpc_v1_allocation_service_proto_rawDescData []byte
)

func file_nebius_vpc_v1_allocation_service_proto_rawDescGZIP() []byte {
	file_nebius_vpc_v1_allocation_service_proto_rawDescOnce.Do(func() {
		file_nebius_vpc_v1_allocation_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nebius_vpc_v1_allocation_service_proto_rawDesc), len(file_nebius_vpc_v1_allocation_service_proto_rawDesc)))
	})
	return file_nebius_vpc_v1_allocation_service_proto_rawDescData
}

var file_nebius_vpc_v1_allocation_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_nebius_vpc_v1_allocation_service_proto_goTypes = []any{
	(*GetAllocationRequest)(nil),           // 0: nebius.vpc.v1.GetAllocationRequest
	(*GetAllocationByNameRequest)(nil),     // 1: nebius.vpc.v1.GetAllocationByNameRequest
	(*ListAllocationsRequest)(nil),         // 2: nebius.vpc.v1.ListAllocationsRequest
	(*ListAllocationsByPoolRequest)(nil),   // 3: nebius.vpc.v1.ListAllocationsByPoolRequest
	(*ListAllocationsBySubnetRequest)(nil), // 4: nebius.vpc.v1.ListAllocationsBySubnetRequest
	(*ListAllocationsResponse)(nil),        // 5: nebius.vpc.v1.ListAllocationsResponse
	(*CreateAllocationRequest)(nil),        // 6: nebius.vpc.v1.CreateAllocationRequest
	(*UpdateAllocationRequest)(nil),        // 7: nebius.vpc.v1.UpdateAllocationRequest
	(*DeleteAllocationRequest)(nil),        // 8: nebius.vpc.v1.DeleteAllocationRequest
	(*Allocation)(nil),                     // 9: nebius.vpc.v1.Allocation
	(*v1.ResourceMetadata)(nil),            // 10: nebius.common.v1.ResourceMetadata
	(*AllocationSpec)(nil),                 // 11: nebius.vpc.v1.AllocationSpec
	(*v1.Operation)(nil),                   // 12: nebius.common.v1.Operation
}
var file_nebius_vpc_v1_allocation_service_proto_depIdxs = []int32{
	9,  // 0: nebius.vpc.v1.ListAllocationsResponse.items:type_name -> nebius.vpc.v1.Allocation
	10, // 1: nebius.vpc.v1.CreateAllocationRequest.metadata:type_name -> nebius.common.v1.ResourceMetadata
	11, // 2: nebius.vpc.v1.CreateAllocationRequest.spec:type_name -> nebius.vpc.v1.AllocationSpec
	10, // 3: nebius.vpc.v1.UpdateAllocationRequest.metadata:type_name -> nebius.common.v1.ResourceMetadata
	11, // 4: nebius.vpc.v1.UpdateAllocationRequest.spec:type_name -> nebius.vpc.v1.AllocationSpec
	0,  // 5: nebius.vpc.v1.AllocationService.Get:input_type -> nebius.vpc.v1.GetAllocationRequest
	1,  // 6: nebius.vpc.v1.AllocationService.GetByName:input_type -> nebius.vpc.v1.GetAllocationByNameRequest
	2,  // 7: nebius.vpc.v1.AllocationService.List:input_type -> nebius.vpc.v1.ListAllocationsRequest
	3,  // 8: nebius.vpc.v1.AllocationService.ListByPool:input_type -> nebius.vpc.v1.ListAllocationsByPoolRequest
	4,  // 9: nebius.vpc.v1.AllocationService.ListBySubnet:input_type -> nebius.vpc.v1.ListAllocationsBySubnetRequest
	6,  // 10: nebius.vpc.v1.AllocationService.Create:input_type -> nebius.vpc.v1.CreateAllocationRequest
	7,  // 11: nebius.vpc.v1.AllocationService.Update:input_type -> nebius.vpc.v1.UpdateAllocationRequest
	8,  // 12: nebius.vpc.v1.AllocationService.Delete:input_type -> nebius.vpc.v1.DeleteAllocationRequest
	9,  // 13: nebius.vpc.v1.AllocationService.Get:output_type -> nebius.vpc.v1.Allocation
	9,  // 14: nebius.vpc.v1.AllocationService.GetByName:output_type -> nebius.vpc.v1.Allocation
	5,  // 15: nebius.vpc.v1.AllocationService.List:output_type -> nebius.vpc.v1.ListAllocationsResponse
	5,  // 16: nebius.vpc.v1.AllocationService.ListByPool:output_type -> nebius.vpc.v1.ListAllocationsResponse
	5,  // 17: nebius.vpc.v1.AllocationService.ListBySubnet:output_type -> nebius.vpc.v1.ListAllocationsResponse
	12, // 18: nebius.vpc.v1.AllocationService.Create:output_type -> nebius.common.v1.Operation
	12, // 19: nebius.vpc.v1.AllocationService.Update:output_type -> nebius.common.v1.Operation
	12, // 20: nebius.vpc.v1.AllocationService.Delete:output_type -> nebius.common.v1.Operation
	13, // [13:21] is the sub-list for method output_type
	5,  // [5:13] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_nebius_vpc_v1_allocation_service_proto_init() }
func file_nebius_vpc_v1_allocation_service_proto_init() {
	if File_nebius_vpc_v1_allocation_service_proto != nil {
		return
	}
	file_nebius_vpc_v1_allocation_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nebius_vpc_v1_allocation_service_proto_rawDesc), len(file_nebius_vpc_v1_allocation_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nebius_vpc_v1_allocation_service_proto_goTypes,
		DependencyIndexes: file_nebius_vpc_v1_allocation_service_proto_depIdxs,
		MessageInfos:      file_nebius_vpc_v1_allocation_service_proto_msgTypes,
	}.Build()
	File_nebius_vpc_v1_allocation_service_proto = out.File
	file_nebius_vpc_v1_allocation_service_proto_goTypes = nil
	file_nebius_vpc_v1_allocation_service_proto_depIdxs = nil
}
