// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.28.3
// source: nebius/vpc/v1/security_rule_service.proto

package v1

import (
	context "context"
	v1 "github.com/nebius/gosdk/proto/nebius/common/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SecurityRuleService_Get_FullMethodName       = "/nebius.vpc.v1.SecurityRuleService/Get"
	SecurityRuleService_GetByName_FullMethodName = "/nebius.vpc.v1.SecurityRuleService/GetByName"
	SecurityRuleService_List_FullMethodName      = "/nebius.vpc.v1.SecurityRuleService/List"
	SecurityRuleService_Create_FullMethodName    = "/nebius.vpc.v1.SecurityRuleService/Create"
	SecurityRuleService_Update_FullMethodName    = "/nebius.vpc.v1.SecurityRuleService/Update"
	SecurityRuleService_Delete_FullMethodName    = "/nebius.vpc.v1.SecurityRuleService/Delete"
)

// SecurityRuleServiceClient is the client API for SecurityRuleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SecurityRuleServiceClient interface {
	Get(ctx context.Context, in *GetSecurityRuleRequest, opts ...grpc.CallOption) (*SecurityRule, error)
	GetByName(ctx context.Context, in *GetSecurityRuleByNameRequest, opts ...grpc.CallOption) (*SecurityRule, error)
	List(ctx context.Context, in *ListSecurityRulesRequest, opts ...grpc.CallOption) (*ListSecurityRulesResponse, error)
	Create(ctx context.Context, in *CreateSecurityRuleRequest, opts ...grpc.CallOption) (*v1.Operation, error)
	Update(ctx context.Context, in *UpdateSecurityRuleRequest, opts ...grpc.CallOption) (*v1.Operation, error)
	Delete(ctx context.Context, in *DeleteSecurityRuleRequest, opts ...grpc.CallOption) (*v1.Operation, error)
}

type securityRuleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSecurityRuleServiceClient(cc grpc.ClientConnInterface) SecurityRuleServiceClient {
	return &securityRuleServiceClient{cc}
}

func (c *securityRuleServiceClient) Get(ctx context.Context, in *GetSecurityRuleRequest, opts ...grpc.CallOption) (*SecurityRule, error) {
	out := new(SecurityRule)
	err := c.cc.Invoke(ctx, SecurityRuleService_Get_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *securityRuleServiceClient) GetByName(ctx context.Context, in *GetSecurityRuleByNameRequest, opts ...grpc.CallOption) (*SecurityRule, error) {
	out := new(SecurityRule)
	err := c.cc.Invoke(ctx, SecurityRuleService_GetByName_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *securityRuleServiceClient) List(ctx context.Context, in *ListSecurityRulesRequest, opts ...grpc.CallOption) (*ListSecurityRulesResponse, error) {
	out := new(ListSecurityRulesResponse)
	err := c.cc.Invoke(ctx, SecurityRuleService_List_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *securityRuleServiceClient) Create(ctx context.Context, in *CreateSecurityRuleRequest, opts ...grpc.CallOption) (*v1.Operation, error) {
	out := new(v1.Operation)
	err := c.cc.Invoke(ctx, SecurityRuleService_Create_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *securityRuleServiceClient) Update(ctx context.Context, in *UpdateSecurityRuleRequest, opts ...grpc.CallOption) (*v1.Operation, error) {
	out := new(v1.Operation)
	err := c.cc.Invoke(ctx, SecurityRuleService_Update_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *securityRuleServiceClient) Delete(ctx context.Context, in *DeleteSecurityRuleRequest, opts ...grpc.CallOption) (*v1.Operation, error) {
	out := new(v1.Operation)
	err := c.cc.Invoke(ctx, SecurityRuleService_Delete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SecurityRuleServiceServer is the server API for SecurityRuleService service.
// All implementations should embed UnimplementedSecurityRuleServiceServer
// for forward compatibility
type SecurityRuleServiceServer interface {
	Get(context.Context, *GetSecurityRuleRequest) (*SecurityRule, error)
	GetByName(context.Context, *GetSecurityRuleByNameRequest) (*SecurityRule, error)
	List(context.Context, *ListSecurityRulesRequest) (*ListSecurityRulesResponse, error)
	Create(context.Context, *CreateSecurityRuleRequest) (*v1.Operation, error)
	Update(context.Context, *UpdateSecurityRuleRequest) (*v1.Operation, error)
	Delete(context.Context, *DeleteSecurityRuleRequest) (*v1.Operation, error)
}

// UnimplementedSecurityRuleServiceServer should be embedded to have forward compatible implementations.
type UnimplementedSecurityRuleServiceServer struct {
}

func (UnimplementedSecurityRuleServiceServer) Get(context.Context, *GetSecurityRuleRequest) (*SecurityRule, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedSecurityRuleServiceServer) GetByName(context.Context, *GetSecurityRuleByNameRequest) (*SecurityRule, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByName not implemented")
}
func (UnimplementedSecurityRuleServiceServer) List(context.Context, *ListSecurityRulesRequest) (*ListSecurityRulesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedSecurityRuleServiceServer) Create(context.Context, *CreateSecurityRuleRequest) (*v1.Operation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedSecurityRuleServiceServer) Update(context.Context, *UpdateSecurityRuleRequest) (*v1.Operation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedSecurityRuleServiceServer) Delete(context.Context, *DeleteSecurityRuleRequest) (*v1.Operation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

// UnsafeSecurityRuleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SecurityRuleServiceServer will
// result in compilation errors.
type UnsafeSecurityRuleServiceServer interface {
	mustEmbedUnimplementedSecurityRuleServiceServer()
}

func RegisterSecurityRuleServiceServer(s grpc.ServiceRegistrar, srv SecurityRuleServiceServer) {
	s.RegisterService(&SecurityRuleService_ServiceDesc, srv)
}

func _SecurityRuleService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSecurityRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecurityRuleServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecurityRuleService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecurityRuleServiceServer).Get(ctx, req.(*GetSecurityRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecurityRuleService_GetByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSecurityRuleByNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecurityRuleServiceServer).GetByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecurityRuleService_GetByName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecurityRuleServiceServer).GetByName(ctx, req.(*GetSecurityRuleByNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecurityRuleService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSecurityRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecurityRuleServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecurityRuleService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecurityRuleServiceServer).List(ctx, req.(*ListSecurityRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecurityRuleService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSecurityRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecurityRuleServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecurityRuleService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecurityRuleServiceServer).Create(ctx, req.(*CreateSecurityRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecurityRuleService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSecurityRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecurityRuleServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecurityRuleService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecurityRuleServiceServer).Update(ctx, req.(*UpdateSecurityRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecurityRuleService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSecurityRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecurityRuleServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecurityRuleService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecurityRuleServiceServer).Delete(ctx, req.(*DeleteSecurityRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SecurityRuleService_ServiceDesc is the grpc.ServiceDesc for SecurityRuleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SecurityRuleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nebius.vpc.v1.SecurityRuleService",
	HandlerType: (*SecurityRuleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _SecurityRuleService_Get_Handler,
		},
		{
			MethodName: "GetByName",
			Handler:    _SecurityRuleService_GetByName_Handler,
		},
		{
			MethodName: "List",
			Handler:    _SecurityRuleService_List_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _SecurityRuleService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _SecurityRuleService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _SecurityRuleService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nebius/vpc/v1/security_rule_service.proto",
}
