// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.3
// source: nebius/vpc/v1/target_group.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/nebius/gosdk/proto/nebius"
	v1 "github.com/nebius/gosdk/proto/nebius/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TargetStatus_TargetState int32

const (
	TargetStatus_TARGET_STATE_UNSPECIFIED TargetStatus_TargetState = 0
	// The target exists and ready to receive traffic
	TargetStatus_READY TargetStatus_TargetState = 1
	// The target exists, but not ready to receive traffic (i.e. network interface is not allocated)
	TargetStatus_DISABLED TargetStatus_TargetState = 2
	// The target does not exist anymore (i.e. network interface was deleted)
	TargetStatus_DELETED TargetStatus_TargetState = 3
)

// Enum value maps for TargetStatus_TargetState.
var (
	TargetStatus_TargetState_name = map[int32]string{
		0: "TARGET_STATE_UNSPECIFIED",
		1: "READY",
		2: "DISABLED",
		3: "DELETED",
	}
	TargetStatus_TargetState_value = map[string]int32{
		"TARGET_STATE_UNSPECIFIED": 0,
		"READY":                    1,
		"DISABLED":                 2,
		"DELETED":                  3,
	}
)

func (x TargetStatus_TargetState) Enum() *TargetStatus_TargetState {
	p := new(TargetStatus_TargetState)
	*p = x
	return p
}

func (x TargetStatus_TargetState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TargetStatus_TargetState) Descriptor() protoreflect.EnumDescriptor {
	return file_nebius_vpc_v1_target_group_proto_enumTypes[0].Descriptor()
}

func (TargetStatus_TargetState) Type() protoreflect.EnumType {
	return &file_nebius_vpc_v1_target_group_proto_enumTypes[0]
}

func (x TargetStatus_TargetState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TargetStatus_TargetState.Descriptor instead.
func (TargetStatus_TargetState) EnumDescriptor() ([]byte, []int) {
	return file_nebius_vpc_v1_target_group_proto_rawDescGZIP(), []int{5, 0}
}

// Target group represents the set of resources that receive traffic from a load balancer listener
type TargetGroup struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Metadata for the TargetGroup resource.
	// `metadata.parent_id` represents IAM container
	Metadata *v1.ResourceMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Specification of the TargetGroup.
	Spec *TargetGroupSpec `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	// Status of the TargetGroup.
	Status        *TargetGroupStatus `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetGroup) Reset() {
	*x = TargetGroup{}
	mi := &file_nebius_vpc_v1_target_group_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetGroup) ProtoMessage() {}

func (x *TargetGroup) ProtoReflect() protoreflect.Message {
	mi := &file_nebius_vpc_v1_target_group_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetGroup.ProtoReflect.Descriptor instead.
func (*TargetGroup) Descriptor() ([]byte, []int) {
	return file_nebius_vpc_v1_target_group_proto_rawDescGZIP(), []int{0}
}

func (x *TargetGroup) GetMetadata() *v1.ResourceMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *TargetGroup) GetSpec() *TargetGroupSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *TargetGroup) GetStatus() *TargetGroupStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type TargetGroupSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Targets of the TargetGroup
	Targets       []*Target `protobuf:"bytes,1,rep,name=targets,proto3" json:"targets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetGroupSpec) Reset() {
	*x = TargetGroupSpec{}
	mi := &file_nebius_vpc_v1_target_group_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetGroupSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetGroupSpec) ProtoMessage() {}

func (x *TargetGroupSpec) ProtoReflect() protoreflect.Message {
	mi := &file_nebius_vpc_v1_target_group_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetGroupSpec.ProtoReflect.Descriptor instead.
func (*TargetGroupSpec) Descriptor() ([]byte, []int) {
	return file_nebius_vpc_v1_target_group_proto_rawDescGZIP(), []int{1}
}

func (x *TargetGroupSpec) GetTargets() []*Target {
	if x != nil {
		return x.Targets
	}
	return nil
}

// Represents the target which can receive traffic from a load balancer listener
type Target struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Target:
	//
	//	*Target_ComputeInstance
	Target        isTarget_Target `protobuf_oneof:"target"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Target) Reset() {
	*x = Target{}
	mi := &file_nebius_vpc_v1_target_group_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Target) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Target) ProtoMessage() {}

func (x *Target) ProtoReflect() protoreflect.Message {
	mi := &file_nebius_vpc_v1_target_group_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Target.ProtoReflect.Descriptor instead.
func (*Target) Descriptor() ([]byte, []int) {
	return file_nebius_vpc_v1_target_group_proto_rawDescGZIP(), []int{2}
}

func (x *Target) GetTarget() isTarget_Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *Target) GetComputeInstance() *ComputeInstance {
	if x != nil {
		if x, ok := x.Target.(*Target_ComputeInstance); ok {
			return x.ComputeInstance
		}
	}
	return nil
}

type isTarget_Target interface {
	isTarget_Target()
}

type Target_ComputeInstance struct {
	// Compute instance used as a target
	ComputeInstance *ComputeInstance `protobuf:"bytes,1,opt,name=compute_instance,json=computeInstance,proto3,oneof"`
}

func (*Target_ComputeInstance) isTarget_Target() {}

// Target representing compute instance
type ComputeInstance struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Compute instance id to send traffic to
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Name of the compute instance's NetworkInterface to send traffic to. If not specified the first one will be used.
	NetworkInterfaceName string `protobuf:"bytes,2,opt,name=network_interface_name,json=networkInterfaceName,proto3" json:"network_interface_name,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ComputeInstance) Reset() {
	*x = ComputeInstance{}
	mi := &file_nebius_vpc_v1_target_group_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeInstance) ProtoMessage() {}

func (x *ComputeInstance) ProtoReflect() protoreflect.Message {
	mi := &file_nebius_vpc_v1_target_group_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputeInstance.ProtoReflect.Descriptor instead.
func (*ComputeInstance) Descriptor() ([]byte, []int) {
	return file_nebius_vpc_v1_target_group_proto_rawDescGZIP(), []int{3}
}

func (x *ComputeInstance) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ComputeInstance) GetNetworkInterfaceName() string {
	if x != nil {
		return x.NetworkInterfaceName
	}
	return ""
}

type TargetGroupStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// LoadBalancer ids target group is attached to
	LoadBalancerIds []string `protobuf:"bytes,1,rep,name=load_balancer_ids,json=loadBalancerIds,proto3" json:"load_balancer_ids,omitempty"`
	// Statuses of specified targets
	TargetStatuses []*TargetStatus `protobuf:"bytes,2,rep,name=target_statuses,json=targetStatuses,proto3" json:"target_statuses,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TargetGroupStatus) Reset() {
	*x = TargetGroupStatus{}
	mi := &file_nebius_vpc_v1_target_group_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetGroupStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetGroupStatus) ProtoMessage() {}

func (x *TargetGroupStatus) ProtoReflect() protoreflect.Message {
	mi := &file_nebius_vpc_v1_target_group_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetGroupStatus.ProtoReflect.Descriptor instead.
func (*TargetGroupStatus) Descriptor() ([]byte, []int) {
	return file_nebius_vpc_v1_target_group_proto_rawDescGZIP(), []int{4}
}

func (x *TargetGroupStatus) GetLoadBalancerIds() []string {
	if x != nil {
		return x.LoadBalancerIds
	}
	return nil
}

func (x *TargetGroupStatus) GetTargetStatuses() []*TargetStatus {
	if x != nil {
		return x.TargetStatuses
	}
	return nil
}

type TargetStatus struct {
	state             protoimpl.MessageState   `protogen:"open.v1"`
	ComputeInstanceId string                   `protobuf:"bytes,1,opt,name=compute_instance_id,json=computeInstanceId,proto3" json:"compute_instance_id,omitempty"`
	TargetState       TargetStatus_TargetState `protobuf:"varint,2,opt,name=target_state,json=targetState,proto3,enum=nebius.vpc.v1.TargetStatus_TargetState" json:"target_state,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TargetStatus) Reset() {
	*x = TargetStatus{}
	mi := &file_nebius_vpc_v1_target_group_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetStatus) ProtoMessage() {}

func (x *TargetStatus) ProtoReflect() protoreflect.Message {
	mi := &file_nebius_vpc_v1_target_group_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetStatus.ProtoReflect.Descriptor instead.
func (*TargetStatus) Descriptor() ([]byte, []int) {
	return file_nebius_vpc_v1_target_group_proto_rawDescGZIP(), []int{5}
}

func (x *TargetStatus) GetComputeInstanceId() string {
	if x != nil {
		return x.ComputeInstanceId
	}
	return ""
}

func (x *TargetStatus) GetTargetState() TargetStatus_TargetState {
	if x != nil {
		return x.TargetState
	}
	return TargetStatus_TARGET_STATE_UNSPECIFIED
}

var File_nebius_vpc_v1_target_group_proto protoreflect.FileDescriptor

const file_nebius_vpc_v1_target_group_proto_rawDesc = "" +
	"\n" +
	" nebius/vpc/v1/target_group.proto\x12\rnebius.vpc.v1\x1a\x1bbuf/validate/validate.proto\x1a\x18nebius/annotations.proto\x1a\x1fnebius/common/v1/metadata.proto\"\xbb\x01\n" +
	"\vTargetGroup\x12>\n" +
	"\bmetadata\x18\x01 \x01(\v2\".nebius.common.v1.ResourceMetadataR\bmetadata\x122\n" +
	"\x04spec\x18\x02 \x01(\v2\x1e.nebius.vpc.v1.TargetGroupSpecR\x04spec\x128\n" +
	"\x06status\x18\x03 \x01(\v2 .nebius.vpc.v1.TargetGroupStatusR\x06status\"B\n" +
	"\x0fTargetGroupSpec\x12/\n" +
	"\atargets\x18\x01 \x03(\v2\x15.nebius.vpc.v1.TargetR\atargets\"f\n" +
	"\x06Target\x12K\n" +
	"\x10compute_instance\x18\x01 \x01(\v2\x1e.nebius.vpc.v1.ComputeInstanceH\x00R\x0fcomputeInstanceB\x0f\n" +
	"\x06target\x12\x05\xbaH\x02\b\x01\"e\n" +
	"\x0fComputeInstance\x12\x16\n" +
	"\x02id\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x02id\x12:\n" +
	"\x16network_interface_name\x18\x02 \x01(\tB\x04\xbaJ\x01\aR\x14networkInterfaceName\"\x85\x01\n" +
	"\x11TargetGroupStatus\x12*\n" +
	"\x11load_balancer_ids\x18\x01 \x03(\tR\x0floadBalancerIds\x12D\n" +
	"\x0ftarget_statuses\x18\x02 \x03(\v2\x1b.nebius.vpc.v1.TargetStatusR\x0etargetStatuses\"\xdd\x01\n" +
	"\fTargetStatus\x12.\n" +
	"\x13compute_instance_id\x18\x01 \x01(\tR\x11computeInstanceId\x12J\n" +
	"\ftarget_state\x18\x02 \x01(\x0e2'.nebius.vpc.v1.TargetStatus.TargetStateR\vtargetState\"Q\n" +
	"\vTargetState\x12\x1c\n" +
	"\x18TARGET_STATE_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05READY\x10\x01\x12\f\n" +
	"\bDISABLED\x10\x02\x12\v\n" +
	"\aDELETED\x10\x03BW\n" +
	"\x14ai.nebius.pub.vpc.v1B\x10TargetGroupProtoP\x01Z+github.com/nebius/gosdk/proto/nebius/vpc/v1b\x06proto3"

var (
	file_nebius_vpc_v1_target_group_proto_rawDescOnce sync.Once
	file_nebius_vpc_v1_target_group_proto_rawDescData []byte
)

func file_nebius_vpc_v1_target_group_proto_rawDescGZIP() []byte {
	file_nebius_vpc_v1_target_group_proto_rawDescOnce.Do(func() {
		file_nebius_vpc_v1_target_group_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nebius_vpc_v1_target_group_proto_rawDesc), len(file_nebius_vpc_v1_target_group_proto_rawDesc)))
	})
	return file_nebius_vpc_v1_target_group_proto_rawDescData
}

var file_nebius_vpc_v1_target_group_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_nebius_vpc_v1_target_group_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_nebius_vpc_v1_target_group_proto_goTypes = []any{
	(TargetStatus_TargetState)(0), // 0: nebius.vpc.v1.TargetStatus.TargetState
	(*TargetGroup)(nil),           // 1: nebius.vpc.v1.TargetGroup
	(*TargetGroupSpec)(nil),       // 2: nebius.vpc.v1.TargetGroupSpec
	(*Target)(nil),                // 3: nebius.vpc.v1.Target
	(*ComputeInstance)(nil),       // 4: nebius.vpc.v1.ComputeInstance
	(*TargetGroupStatus)(nil),     // 5: nebius.vpc.v1.TargetGroupStatus
	(*TargetStatus)(nil),          // 6: nebius.vpc.v1.TargetStatus
	(*v1.ResourceMetadata)(nil),   // 7: nebius.common.v1.ResourceMetadata
}
var file_nebius_vpc_v1_target_group_proto_depIdxs = []int32{
	7, // 0: nebius.vpc.v1.TargetGroup.metadata:type_name -> nebius.common.v1.ResourceMetadata
	2, // 1: nebius.vpc.v1.TargetGroup.spec:type_name -> nebius.vpc.v1.TargetGroupSpec
	5, // 2: nebius.vpc.v1.TargetGroup.status:type_name -> nebius.vpc.v1.TargetGroupStatus
	3, // 3: nebius.vpc.v1.TargetGroupSpec.targets:type_name -> nebius.vpc.v1.Target
	4, // 4: nebius.vpc.v1.Target.compute_instance:type_name -> nebius.vpc.v1.ComputeInstance
	6, // 5: nebius.vpc.v1.TargetGroupStatus.target_statuses:type_name -> nebius.vpc.v1.TargetStatus
	0, // 6: nebius.vpc.v1.TargetStatus.target_state:type_name -> nebius.vpc.v1.TargetStatus.TargetState
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_nebius_vpc_v1_target_group_proto_init() }
func file_nebius_vpc_v1_target_group_proto_init() {
	if File_nebius_vpc_v1_target_group_proto != nil {
		return
	}
	file_nebius_vpc_v1_target_group_proto_msgTypes[2].OneofWrappers = []any{
		(*Target_ComputeInstance)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nebius_vpc_v1_target_group_proto_rawDesc), len(file_nebius_vpc_v1_target_group_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nebius_vpc_v1_target_group_proto_goTypes,
		DependencyIndexes: file_nebius_vpc_v1_target_group_proto_depIdxs,
		EnumInfos:         file_nebius_vpc_v1_target_group_proto_enumTypes,
		MessageInfos:      file_nebius_vpc_v1_target_group_proto_msgTypes,
	}.Build()
	File_nebius_vpc_v1_target_group_proto = out.File
	file_nebius_vpc_v1_target_group_proto_goTypes = nil
	file_nebius_vpc_v1_target_group_proto_depIdxs = nil
}
