// Code generated by protoc-gen-gosdk. DO NOT EDIT.

package v1

import (
	context "context"
	check_nid "github.com/nebius/gosdk/check-nid"
	conn "github.com/nebius/gosdk/conn"
	iface "github.com/nebius/gosdk/internal/iface"
	operations "github.com/nebius/gosdk/operations"
	grpcheader "github.com/nebius/gosdk/proto/fieldmask/grpcheader"
	v11 "github.com/nebius/gosdk/proto/nebius/common/v1"
	v1 "github.com/nebius/gosdk/proto/nebius/kms/v1"
	grpc "google.golang.org/grpc"
	proto "google.golang.org/protobuf/proto"
	iter "iter"
	slog "log/slog"
)

func init() {
	conn.ConventionResolverServiceIDToNameMap[SymmetricKeyServiceID] = "cpl.kms"
}

func (s Services) SymmetricKey() SymmetricKeyService {
	return NewSymmetricKeyService(s.sdk)
}

const SymmetricKeyServiceID conn.ServiceID = "nebius.kms.v1.SymmetricKeyService"

type SymmetricKeyService interface {
	Create(context.Context, *v1.CreateSymmetricKeyRequest, ...grpc.CallOption) (operations.Operation, error)
	Update(context.Context, *v1.UpdateSymmetricKeyRequest, ...grpc.CallOption) (operations.Operation, error)
	Rotate(context.Context, *v1.RotateSymmetricKeyRequest, ...grpc.CallOption) (operations.Operation, error)
	Get(context.Context, *v1.GetSymmetricKeyRequest, ...grpc.CallOption) (*v1.SymmetricKey, error)
	GetByName(context.Context, *v1.GetSymmetricKeyByNameRequest, ...grpc.CallOption) (*v1.SymmetricKey, error)
	List(context.Context, *v1.ListSymmetricKeysRequest, ...grpc.CallOption) (*v1.ListSymmetricKeysResponse, error)
	Filter(context.Context, *v1.ListSymmetricKeysRequest, ...grpc.CallOption) iter.Seq2[*v1.SymmetricKey, error]
	Delete(context.Context, *v1.DeleteSymmetricKeyRequest, ...grpc.CallOption) (operations.Operation, error)
	UpdateDeletionDelay(context.Context, *v1.UpdateSymmetricKeyDeletionDelayRequest, ...grpc.CallOption) (operations.Operation, error)
	Undelete(context.Context, *v1.UndeleteSymmetricKeyRequest, ...grpc.CallOption) (operations.Operation, error)
	GetOperation(context.Context, *v11.GetOperationRequest, ...grpc.CallOption) (operations.Operation, error)
	ListOperations(context.Context, *v11.ListOperationsRequest, ...grpc.CallOption) (*v11.ListOperationsResponse, error)
}

type symmetricKeyService struct {
	sdk iface.SDKWithParentID
}

func NewSymmetricKeyService(sdk iface.SDK) SymmetricKeyService {
	return symmetricKeyService{
		sdk: iface.WrapSDK(sdk),
	}
}

func (s symmetricKeyService) Create(ctx context.Context, request *v1.CreateSymmetricKeyRequest, opts ...grpc.CallOption) (
	operations.Operation,
	error,
) {
	nidCheckCtx := check_nid.NewNIDCheckContext([]*check_nid.SubfieldSettings{{FieldPath: "metadata.parent_id", Nid: &check_nid.NIDFieldSettings{Resource: []string{}}}})
	if request.GetMetadata().GetParentId() == "" {
		if tenantID := s.sdk.TenantID(); tenantID != "" {
			if check_nid.ValidateNIDString(tenantID, nil) == "" {
				md := request.GetMetadata()
				if md == nil {
					md = &v11.ResourceMetadata{}
				}
				md.ParentId = tenantID
				request.Metadata = md
			}
		}
		if parentID := s.sdk.ParentID(); parentID != "" {
			if check_nid.ValidateNIDString(parentID, nil) == "" {
				md := request.GetMetadata()
				if md == nil {
					md = &v11.ResourceMetadata{}
				}
				md.ParentId = parentID
				request.Metadata = md
			}
		}
	}
	if logger := s.sdk.GetLogger(); logger != nil {
		for path, warning := range check_nid.CheckMessageFields(request, nidCheckCtx) {
			logger.WarnContext(ctx, warning, slog.String("path", path))
		}
	}
	address, err := s.sdk.Resolve(ctx, SymmetricKeyServiceID)
	if err != nil {
		return nil, err
	}
	con, err := s.sdk.Dial(ctx, address)
	if err != nil {
		return nil, err
	}
	op, err := v1.NewSymmetricKeyServiceClient(con).Create(ctx, request, opts...)
	if err != nil {
		return nil, err
	}
	return operations.New(op, v11.NewOperationServiceClient(con))
}

func (s symmetricKeyService) Update(ctx context.Context, request *v1.UpdateSymmetricKeyRequest, opts ...grpc.CallOption) (
	operations.Operation,
	error,
) {
	nidCheckCtx := check_nid.NewNIDCheckContext([]*check_nid.SubfieldSettings{{FieldPath: "metadata.parent_id", Nid: &check_nid.NIDFieldSettings{Resource: []string{}}}})
	ctx, err := grpcheader.EnsureMessageResetMaskInOutgoingContext(ctx, request)
	if err != nil {
		return nil, err
	}
	if logger := s.sdk.GetLogger(); logger != nil {
		for path, warning := range check_nid.CheckMessageFields(request, nidCheckCtx) {
			logger.WarnContext(ctx, warning, slog.String("path", path))
		}
	}
	address, err := s.sdk.Resolve(ctx, SymmetricKeyServiceID)
	if err != nil {
		return nil, err
	}
	con, err := s.sdk.Dial(ctx, address)
	if err != nil {
		return nil, err
	}
	op, err := v1.NewSymmetricKeyServiceClient(con).Update(ctx, request, opts...)
	if err != nil {
		return nil, err
	}
	return operations.New(op, v11.NewOperationServiceClient(con))
}

func (s symmetricKeyService) Rotate(ctx context.Context, request *v1.RotateSymmetricKeyRequest, opts ...grpc.CallOption) (
	operations.Operation,
	error,
) {
	nidCheckCtx := check_nid.NewNIDCheckContext(nil)
	if logger := s.sdk.GetLogger(); logger != nil {
		for path, warning := range check_nid.CheckMessageFields(request, nidCheckCtx) {
			logger.WarnContext(ctx, warning, slog.String("path", path))
		}
	}
	address, err := s.sdk.Resolve(ctx, SymmetricKeyServiceID)
	if err != nil {
		return nil, err
	}
	con, err := s.sdk.Dial(ctx, address)
	if err != nil {
		return nil, err
	}
	op, err := v1.NewSymmetricKeyServiceClient(con).Rotate(ctx, request, opts...)
	if err != nil {
		return nil, err
	}
	return operations.New(op, v11.NewOperationServiceClient(con))
}

func (s symmetricKeyService) Get(ctx context.Context, request *v1.GetSymmetricKeyRequest, opts ...grpc.CallOption) (
	*v1.SymmetricKey,
	error,
) {
	nidCheckCtx := check_nid.NewNIDCheckContext(nil)
	if logger := s.sdk.GetLogger(); logger != nil {
		for path, warning := range check_nid.CheckMessageFields(request, nidCheckCtx) {
			logger.WarnContext(ctx, warning, slog.String("path", path))
		}
	}
	address, err := s.sdk.Resolve(ctx, SymmetricKeyServiceID)
	if err != nil {
		return nil, err
	}
	con, err := s.sdk.Dial(ctx, address)
	if err != nil {
		return nil, err
	}
	return v1.NewSymmetricKeyServiceClient(con).Get(ctx, request, opts...)
}

func (s symmetricKeyService) GetByName(ctx context.Context, request *v1.GetSymmetricKeyByNameRequest, opts ...grpc.CallOption) (
	*v1.SymmetricKey,
	error,
) {
	nidCheckCtx := check_nid.NewNIDCheckContext(nil)
	if request.GetParentId() == "" {
		if parentID := s.sdk.ParentID(); parentID != "" {
			if check_nid.ValidateNIDString(parentID, nil) == "" {
				request.ParentId = parentID
			}
		}
		if request.GetParentId() == "" {
			if tenantID := s.sdk.TenantID(); tenantID != "" {
				if check_nid.ValidateNIDString(tenantID, nil) == "" {
					request.ParentId = tenantID
				}
			}
		}
	}
	if logger := s.sdk.GetLogger(); logger != nil {
		for path, warning := range check_nid.CheckMessageFields(request, nidCheckCtx) {
			logger.WarnContext(ctx, warning, slog.String("path", path))
		}
	}
	address, err := s.sdk.Resolve(ctx, SymmetricKeyServiceID)
	if err != nil {
		return nil, err
	}
	con, err := s.sdk.Dial(ctx, address)
	if err != nil {
		return nil, err
	}
	return v1.NewSymmetricKeyServiceClient(con).GetByName(ctx, request, opts...)
}

func (s symmetricKeyService) List(ctx context.Context, request *v1.ListSymmetricKeysRequest, opts ...grpc.CallOption) (
	*v1.ListSymmetricKeysResponse,
	error,
) {
	nidCheckCtx := check_nid.NewNIDCheckContext(nil)
	if request.GetParentId() == "" {
		if parentID := s.sdk.ParentID(); parentID != "" {
			if check_nid.ValidateNIDString(parentID, nil) == "" {
				request.ParentId = parentID
			}
		}
		if request.GetParentId() == "" {
			if tenantID := s.sdk.TenantID(); tenantID != "" {
				if check_nid.ValidateNIDString(tenantID, nil) == "" {
					request.ParentId = tenantID
				}
			}
		}
	}
	if logger := s.sdk.GetLogger(); logger != nil {
		for path, warning := range check_nid.CheckMessageFields(request, nidCheckCtx) {
			logger.WarnContext(ctx, warning, slog.String("path", path))
		}
	}
	address, err := s.sdk.Resolve(ctx, SymmetricKeyServiceID)
	if err != nil {
		return nil, err
	}
	con, err := s.sdk.Dial(ctx, address)
	if err != nil {
		return nil, err
	}
	return v1.NewSymmetricKeyServiceClient(con).List(ctx, request, opts...)
}

func (s symmetricKeyService) Filter(ctx context.Context, request *v1.ListSymmetricKeysRequest, opts ...grpc.CallOption) iter.Seq2[*v1.SymmetricKey, error] {
	req := proto.Clone(request).(*v1.ListSymmetricKeysRequest)
	return func(yield func(*v1.SymmetricKey, error) bool) {
		for {
			res, err := s.List(ctx, req, opts...)
			if err != nil {
				yield(nil, err)
				return
			}

			for _, item := range res.GetItems() {
				if !yield(item, nil) {
					return
				}
			}

			if res.GetNextPageToken() == "" {
				return
			}

			req.PageToken = res.GetNextPageToken()
		}
	}
}

func (s symmetricKeyService) Delete(ctx context.Context, request *v1.DeleteSymmetricKeyRequest, opts ...grpc.CallOption) (
	operations.Operation,
	error,
) {
	nidCheckCtx := check_nid.NewNIDCheckContext(nil)
	if logger := s.sdk.GetLogger(); logger != nil {
		for path, warning := range check_nid.CheckMessageFields(request, nidCheckCtx) {
			logger.WarnContext(ctx, warning, slog.String("path", path))
		}
	}
	address, err := s.sdk.Resolve(ctx, SymmetricKeyServiceID)
	if err != nil {
		return nil, err
	}
	con, err := s.sdk.Dial(ctx, address)
	if err != nil {
		return nil, err
	}
	op, err := v1.NewSymmetricKeyServiceClient(con).Delete(ctx, request, opts...)
	if err != nil {
		return nil, err
	}
	return operations.New(op, v11.NewOperationServiceClient(con))
}

func (s symmetricKeyService) UpdateDeletionDelay(ctx context.Context, request *v1.UpdateSymmetricKeyDeletionDelayRequest, opts ...grpc.CallOption) (
	operations.Operation,
	error,
) {
	nidCheckCtx := check_nid.NewNIDCheckContext(nil)
	if logger := s.sdk.GetLogger(); logger != nil {
		for path, warning := range check_nid.CheckMessageFields(request, nidCheckCtx) {
			logger.WarnContext(ctx, warning, slog.String("path", path))
		}
	}
	address, err := s.sdk.Resolve(ctx, SymmetricKeyServiceID)
	if err != nil {
		return nil, err
	}
	con, err := s.sdk.Dial(ctx, address)
	if err != nil {
		return nil, err
	}
	op, err := v1.NewSymmetricKeyServiceClient(con).UpdateDeletionDelay(ctx, request, opts...)
	if err != nil {
		return nil, err
	}
	return operations.New(op, v11.NewOperationServiceClient(con))
}

func (s symmetricKeyService) Undelete(ctx context.Context, request *v1.UndeleteSymmetricKeyRequest, opts ...grpc.CallOption) (
	operations.Operation,
	error,
) {
	nidCheckCtx := check_nid.NewNIDCheckContext(nil)
	if logger := s.sdk.GetLogger(); logger != nil {
		for path, warning := range check_nid.CheckMessageFields(request, nidCheckCtx) {
			logger.WarnContext(ctx, warning, slog.String("path", path))
		}
	}
	address, err := s.sdk.Resolve(ctx, SymmetricKeyServiceID)
	if err != nil {
		return nil, err
	}
	con, err := s.sdk.Dial(ctx, address)
	if err != nil {
		return nil, err
	}
	op, err := v1.NewSymmetricKeyServiceClient(con).Undelete(ctx, request, opts...)
	if err != nil {
		return nil, err
	}
	return operations.New(op, v11.NewOperationServiceClient(con))
}

func (s symmetricKeyService) GetOperation(ctx context.Context, request *v11.GetOperationRequest, opts ...grpc.CallOption) (operations.Operation, error) {
	address, err := s.sdk.Resolve(ctx, SymmetricKeyServiceID)
	if err != nil {
		return nil, err
	}
	con, err := s.sdk.Dial(ctx, address)
	if err != nil {
		return nil, err
	}
	client := v11.NewOperationServiceClient(con)
	op, err := client.Get(ctx, request, opts...)
	if err != nil {
		return nil, err
	}
	return operations.New(op, client)
}

func (s symmetricKeyService) ListOperations(ctx context.Context, request *v11.ListOperationsRequest, opts ...grpc.CallOption) (*v11.ListOperationsResponse, error) {
	address, err := s.sdk.Resolve(ctx, SymmetricKeyServiceID)
	if err != nil {
		return nil, err
	}
	con, err := s.sdk.Dial(ctx, address)
	if err != nil {
		return nil, err
	}
	return v11.NewOperationServiceClient(con).List(ctx, request, opts...)
}
