// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.3
// source: nebius/iam/v2/access_key.proto

package v2

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/nebius/gosdk/proto/nebius"
	v1 "github.com/nebius/gosdk/proto/nebius/common/v1"
	v11 "github.com/nebius/gosdk/proto/nebius/iam/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SecretDeliveryMode int32

const (
	// If not specified, the default behaviour will be applied. Currently it's INLINE, later will be EXPLICIT.
	SecretDeliveryMode_UNSPECIFIED SecretDeliveryMode = 0
	// The secret value will be returned directly in the API response
	SecretDeliveryMode_INLINE SecretDeliveryMode = 1
	// The secret will be delivered via a MysteryBox secret, in case of terraform it is recommended to use that enum
	SecretDeliveryMode_MYSTERY_BOX SecretDeliveryMode = 2
	// The secret value will be accessible via a separate method GetSecret
	SecretDeliveryMode_EXPLICIT SecretDeliveryMode = 3
)

// Enum value maps for SecretDeliveryMode.
var (
	SecretDeliveryMode_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "INLINE",
		2: "MYSTERY_BOX",
		3: "EXPLICIT",
	}
	SecretDeliveryMode_value = map[string]int32{
		"UNSPECIFIED": 0,
		"INLINE":      1,
		"MYSTERY_BOX": 2,
		"EXPLICIT":    3,
	}
)

func (x SecretDeliveryMode) Enum() *SecretDeliveryMode {
	p := new(SecretDeliveryMode)
	*p = x
	return p
}

func (x SecretDeliveryMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SecretDeliveryMode) Descriptor() protoreflect.EnumDescriptor {
	return file_nebius_iam_v2_access_key_proto_enumTypes[0].Descriptor()
}

func (SecretDeliveryMode) Type() protoreflect.EnumType {
	return &file_nebius_iam_v2_access_key_proto_enumTypes[0]
}

func (x SecretDeliveryMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SecretDeliveryMode.Descriptor instead.
func (SecretDeliveryMode) EnumDescriptor() ([]byte, []int) {
	return file_nebius_iam_v2_access_key_proto_rawDescGZIP(), []int{0}
}

type AccessKeyStatus_State int32

const (
	AccessKeyStatus_STATE_UNSPECIFIED AccessKeyStatus_State = 0
	AccessKeyStatus_ACTIVE            AccessKeyStatus_State = 1
	AccessKeyStatus_INACTIVE          AccessKeyStatus_State = 2
	AccessKeyStatus_EXPIRED           AccessKeyStatus_State = 3
	AccessKeyStatus_DELETING          AccessKeyStatus_State = 4
	AccessKeyStatus_DELETED           AccessKeyStatus_State = 5
)

// Enum value maps for AccessKeyStatus_State.
var (
	AccessKeyStatus_State_name = map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "ACTIVE",
		2: "INACTIVE",
		3: "EXPIRED",
		4: "DELETING",
		5: "DELETED",
	}
	AccessKeyStatus_State_value = map[string]int32{
		"STATE_UNSPECIFIED": 0,
		"ACTIVE":            1,
		"INACTIVE":          2,
		"EXPIRED":           3,
		"DELETING":          4,
		"DELETED":           5,
	}
)

func (x AccessKeyStatus_State) Enum() *AccessKeyStatus_State {
	p := new(AccessKeyStatus_State)
	*p = x
	return p
}

func (x AccessKeyStatus_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccessKeyStatus_State) Descriptor() protoreflect.EnumDescriptor {
	return file_nebius_iam_v2_access_key_proto_enumTypes[1].Descriptor()
}

func (AccessKeyStatus_State) Type() protoreflect.EnumType {
	return &file_nebius_iam_v2_access_key_proto_enumTypes[1]
}

func (x AccessKeyStatus_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccessKeyStatus_State.Descriptor instead.
func (AccessKeyStatus_State) EnumDescriptor() ([]byte, []int) {
	return file_nebius_iam_v2_access_key_proto_rawDescGZIP(), []int{2, 0}
}

type AccessKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *v1.ResourceMetadata   `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Spec          *AccessKeySpec         `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	Status        *AccessKeyStatus       `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessKey) Reset() {
	*x = AccessKey{}
	mi := &file_nebius_iam_v2_access_key_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessKey) ProtoMessage() {}

func (x *AccessKey) ProtoReflect() protoreflect.Message {
	mi := &file_nebius_iam_v2_access_key_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessKey.ProtoReflect.Descriptor instead.
func (*AccessKey) Descriptor() ([]byte, []int) {
	return file_nebius_iam_v2_access_key_proto_rawDescGZIP(), []int{0}
}

func (x *AccessKey) GetMetadata() *v1.ResourceMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *AccessKey) GetSpec() *AccessKeySpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *AccessKey) GetStatus() *AccessKeyStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type AccessKeySpec struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Account     *v11.Account           `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	ExpiresAt   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Description string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Specifies how the secret will be delivered upon creation. This field is immutable — it cannot be changed after the resource is
	// created.
	SecretDeliveryMode SecretDeliveryMode `protobuf:"varint,4,opt,name=secret_delivery_mode,json=secretDeliveryMode,proto3,enum=nebius.iam.v2.SecretDeliveryMode" json:"secret_delivery_mode,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AccessKeySpec) Reset() {
	*x = AccessKeySpec{}
	mi := &file_nebius_iam_v2_access_key_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessKeySpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessKeySpec) ProtoMessage() {}

func (x *AccessKeySpec) ProtoReflect() protoreflect.Message {
	mi := &file_nebius_iam_v2_access_key_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessKeySpec.ProtoReflect.Descriptor instead.
func (*AccessKeySpec) Descriptor() ([]byte, []int) {
	return file_nebius_iam_v2_access_key_proto_rawDescGZIP(), []int{1}
}

func (x *AccessKeySpec) GetAccount() *v11.Account {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *AccessKeySpec) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *AccessKeySpec) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AccessKeySpec) GetSecretDeliveryMode() SecretDeliveryMode {
	if x != nil {
		return x.SecretDeliveryMode
	}
	return SecretDeliveryMode_UNSPECIFIED
}

type AccessKeyStatus struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	State             AccessKeyStatus_State  `protobuf:"varint,1,opt,name=state,proto3,enum=nebius.iam.v2.AccessKeyStatus_State" json:"state,omitempty"`
	Fingerprint       string                 `protobuf:"bytes,2,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	Algorithm         string                 `protobuf:"bytes,3,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	KeySize           int32                  `protobuf:"varint,4,opt,name=key_size,json=keySize,proto3" json:"key_size,omitempty"`
	AwsAccessKeyId    string                 `protobuf:"bytes,5,opt,name=aws_access_key_id,json=awsAccessKeyId,proto3" json:"aws_access_key_id,omitempty"`
	Secret            string                 `protobuf:"bytes,6,opt,name=secret,proto3" json:"secret,omitempty"`
	SecretReferenceId string                 `protobuf:"bytes,7,opt,name=secret_reference_id,json=secretReferenceId,proto3" json:"secret_reference_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AccessKeyStatus) Reset() {
	*x = AccessKeyStatus{}
	mi := &file_nebius_iam_v2_access_key_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessKeyStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessKeyStatus) ProtoMessage() {}

func (x *AccessKeyStatus) ProtoReflect() protoreflect.Message {
	mi := &file_nebius_iam_v2_access_key_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessKeyStatus.ProtoReflect.Descriptor instead.
func (*AccessKeyStatus) Descriptor() ([]byte, []int) {
	return file_nebius_iam_v2_access_key_proto_rawDescGZIP(), []int{2}
}

func (x *AccessKeyStatus) GetState() AccessKeyStatus_State {
	if x != nil {
		return x.State
	}
	return AccessKeyStatus_STATE_UNSPECIFIED
}

func (x *AccessKeyStatus) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *AccessKeyStatus) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *AccessKeyStatus) GetKeySize() int32 {
	if x != nil {
		return x.KeySize
	}
	return 0
}

func (x *AccessKeyStatus) GetAwsAccessKeyId() string {
	if x != nil {
		return x.AwsAccessKeyId
	}
	return ""
}

func (x *AccessKeyStatus) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *AccessKeyStatus) GetSecretReferenceId() string {
	if x != nil {
		return x.SecretReferenceId
	}
	return ""
}

var File_nebius_iam_v2_access_key_proto protoreflect.FileDescriptor

const file_nebius_iam_v2_access_key_proto_rawDesc = "" +
	"\n" +
	"\x1enebius/iam/v2/access_key.proto\x12\rnebius.iam.v2\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x18nebius/annotations.proto\x1a\x1fnebius/common/v1/metadata.proto\x1a\x1anebius/iam/v1/access.proto\"\xd1\x01\n" +
	"\tAccessKey\x12F\n" +
	"\bmetadata\x18\x01 \x01(\v2\".nebius.common.v1.ResourceMetadataB\x06\xbaH\x03\xc8\x01\x01R\bmetadata\x128\n" +
	"\x04spec\x18\x02 \x01(\v2\x1c.nebius.iam.v2.AccessKeySpecB\x06\xbaH\x03\xc8\x01\x01R\x04spec\x12<\n" +
	"\x06status\x18\x03 \x01(\v2\x1e.nebius.iam.v2.AccessKeyStatusB\x04\xbaJ\x01\x05R\x06status:\x04\xbaJ\x01\x02\"\x85\x02\n" +
	"\rAccessKeySpec\x126\n" +
	"\aaccount\x18\x01 \x01(\v2\x16.nebius.iam.v1.AccountB\x04\xbaJ\x01\x02R\aaccount\x12?\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampB\x04\xbaJ\x01\x02R\texpiresAt\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12Y\n" +
	"\x14secret_delivery_mode\x18\x04 \x01(\x0e2!.nebius.iam.v2.SecretDeliveryModeB\x04\xbaJ\x01\x02R\x12secretDeliveryMode\"\x82\x03\n" +
	"\x0fAccessKeyStatus\x12:\n" +
	"\x05state\x18\x01 \x01(\x0e2$.nebius.iam.v2.AccessKeyStatus.StateR\x05state\x12 \n" +
	"\vfingerprint\x18\x02 \x01(\tR\vfingerprint\x12\x1c\n" +
	"\talgorithm\x18\x03 \x01(\tR\talgorithm\x12\x19\n" +
	"\bkey_size\x18\x04 \x01(\x05R\akeySize\x12)\n" +
	"\x11aws_access_key_id\x18\x05 \x01(\tR\x0eawsAccessKeyId\x12\x1b\n" +
	"\x06secret\x18\x06 \x01(\tB\x03\xc0J\x01R\x06secret\x12.\n" +
	"\x13secret_reference_id\x18\a \x01(\tR\x11secretReferenceId\"`\n" +
	"\x05State\x12\x15\n" +
	"\x11STATE_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\x01\x12\f\n" +
	"\bINACTIVE\x10\x02\x12\v\n" +
	"\aEXPIRED\x10\x03\x12\f\n" +
	"\bDELETING\x10\x04\x12\v\n" +
	"\aDELETED\x10\x05*P\n" +
	"\x12SecretDeliveryMode\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06INLINE\x10\x01\x12\x0f\n" +
	"\vMYSTERY_BOX\x10\x02\x12\f\n" +
	"\bEXPLICIT\x10\x03BU\n" +
	"\x14ai.nebius.pub.iam.v2B\x0eAccessKeyProtoP\x01Z+github.com/nebius/gosdk/proto/nebius/iam/v2b\x06proto3"

var (
	file_nebius_iam_v2_access_key_proto_rawDescOnce sync.Once
	file_nebius_iam_v2_access_key_proto_rawDescData []byte
)

func file_nebius_iam_v2_access_key_proto_rawDescGZIP() []byte {
	file_nebius_iam_v2_access_key_proto_rawDescOnce.Do(func() {
		file_nebius_iam_v2_access_key_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nebius_iam_v2_access_key_proto_rawDesc), len(file_nebius_iam_v2_access_key_proto_rawDesc)))
	})
	return file_nebius_iam_v2_access_key_proto_rawDescData
}

var file_nebius_iam_v2_access_key_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_nebius_iam_v2_access_key_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_nebius_iam_v2_access_key_proto_goTypes = []any{
	(SecretDeliveryMode)(0),       // 0: nebius.iam.v2.SecretDeliveryMode
	(AccessKeyStatus_State)(0),    // 1: nebius.iam.v2.AccessKeyStatus.State
	(*AccessKey)(nil),             // 2: nebius.iam.v2.AccessKey
	(*AccessKeySpec)(nil),         // 3: nebius.iam.v2.AccessKeySpec
	(*AccessKeyStatus)(nil),       // 4: nebius.iam.v2.AccessKeyStatus
	(*v1.ResourceMetadata)(nil),   // 5: nebius.common.v1.ResourceMetadata
	(*v11.Account)(nil),           // 6: nebius.iam.v1.Account
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_nebius_iam_v2_access_key_proto_depIdxs = []int32{
	5, // 0: nebius.iam.v2.AccessKey.metadata:type_name -> nebius.common.v1.ResourceMetadata
	3, // 1: nebius.iam.v2.AccessKey.spec:type_name -> nebius.iam.v2.AccessKeySpec
	4, // 2: nebius.iam.v2.AccessKey.status:type_name -> nebius.iam.v2.AccessKeyStatus
	6, // 3: nebius.iam.v2.AccessKeySpec.account:type_name -> nebius.iam.v1.Account
	7, // 4: nebius.iam.v2.AccessKeySpec.expires_at:type_name -> google.protobuf.Timestamp
	0, // 5: nebius.iam.v2.AccessKeySpec.secret_delivery_mode:type_name -> nebius.iam.v2.SecretDeliveryMode
	1, // 6: nebius.iam.v2.AccessKeyStatus.state:type_name -> nebius.iam.v2.AccessKeyStatus.State
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_nebius_iam_v2_access_key_proto_init() }
func file_nebius_iam_v2_access_key_proto_init() {
	if File_nebius_iam_v2_access_key_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nebius_iam_v2_access_key_proto_rawDesc), len(file_nebius_iam_v2_access_key_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nebius_iam_v2_access_key_proto_goTypes,
		DependencyIndexes: file_nebius_iam_v2_access_key_proto_depIdxs,
		EnumInfos:         file_nebius_iam_v2_access_key_proto_enumTypes,
		MessageInfos:      file_nebius_iam_v2_access_key_proto_msgTypes,
	}.Build()
	File_nebius_iam_v2_access_key_proto = out.File
	file_nebius_iam_v2_access_key_proto_goTypes = nil
	file_nebius_iam_v2_access_key_proto_depIdxs = nil
}
