// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.3
// source: nebius/billing/v1alpha1/offer_type.proto

package v1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OfferType is a enum that specifies the type of offer.
type OfferType int32

const (
	OfferType_OFFER_TYPE_UNSPECIFIED OfferType = 0
	// Contract price is a special price for SKU.
	OfferType_OFFER_TYPE_CONTRACT_PRICE OfferType = 1
)

// Enum value maps for OfferType.
var (
	OfferType_name = map[int32]string{
		0: "OFFER_TYPE_UNSPECIFIED",
		1: "OFFER_TYPE_CONTRACT_PRICE",
	}
	OfferType_value = map[string]int32{
		"OFFER_TYPE_UNSPECIFIED":    0,
		"OFFER_TYPE_CONTRACT_PRICE": 1,
	}
)

func (x OfferType) Enum() *OfferType {
	p := new(OfferType)
	*p = x
	return p
}

func (x OfferType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OfferType) Descriptor() protoreflect.EnumDescriptor {
	return file_nebius_billing_v1alpha1_offer_type_proto_enumTypes[0].Descriptor()
}

func (OfferType) Type() protoreflect.EnumType {
	return &file_nebius_billing_v1alpha1_offer_type_proto_enumTypes[0]
}

func (x OfferType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OfferType.Descriptor instead.
func (OfferType) EnumDescriptor() ([]byte, []int) {
	return file_nebius_billing_v1alpha1_offer_type_proto_rawDescGZIP(), []int{0}
}

var File_nebius_billing_v1alpha1_offer_type_proto protoreflect.FileDescriptor

const file_nebius_billing_v1alpha1_offer_type_proto_rawDesc = "" +
	"\n" +
	"(nebius/billing/v1alpha1/offer_type.proto\x12\x17nebius.billing.v1alpha1*F\n" +
	"\tOfferType\x12\x1a\n" +
	"\x16OFFER_TYPE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19OFFER_TYPE_CONTRACT_PRICE\x10\x01Bi\n" +
	"\x1eai.nebius.pub.billing.v1alpha1B\x0eOfferTypeProtoP\x01Z5github.com/nebius/gosdk/proto/nebius/billing/v1alpha1b\x06proto3"

var (
	file_nebius_billing_v1alpha1_offer_type_proto_rawDescOnce sync.Once
	file_nebius_billing_v1alpha1_offer_type_proto_rawDescData []byte
)

func file_nebius_billing_v1alpha1_offer_type_proto_rawDescGZIP() []byte {
	file_nebius_billing_v1alpha1_offer_type_proto_rawDescOnce.Do(func() {
		file_nebius_billing_v1alpha1_offer_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nebius_billing_v1alpha1_offer_type_proto_rawDesc), len(file_nebius_billing_v1alpha1_offer_type_proto_rawDesc)))
	})
	return file_nebius_billing_v1alpha1_offer_type_proto_rawDescData
}

var file_nebius_billing_v1alpha1_offer_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_nebius_billing_v1alpha1_offer_type_proto_goTypes = []any{
	(OfferType)(0), // 0: nebius.billing.v1alpha1.OfferType
}
var file_nebius_billing_v1alpha1_offer_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_nebius_billing_v1alpha1_offer_type_proto_init() }
func file_nebius_billing_v1alpha1_offer_type_proto_init() {
	if File_nebius_billing_v1alpha1_offer_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nebius_billing_v1alpha1_offer_type_proto_rawDesc), len(file_nebius_billing_v1alpha1_offer_type_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nebius_billing_v1alpha1_offer_type_proto_goTypes,
		DependencyIndexes: file_nebius_billing_v1alpha1_offer_type_proto_depIdxs,
		EnumInfos:         file_nebius_billing_v1alpha1_offer_type_proto_enumTypes,
	}.Build()
	File_nebius_billing_v1alpha1_offer_type_proto = out.File
	file_nebius_billing_v1alpha1_offer_type_proto_goTypes = nil
	file_nebius_billing_v1alpha1_offer_type_proto_depIdxs = nil
}
