// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.3
// source: nebius/iam/v1/project_service.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/nebius/gosdk/proto/nebius"
	v1 "github.com/nebius/gosdk/proto/nebius/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *v1.ResourceMetadata   `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Spec          *ContainerSpec         `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProjectRequest) Reset() {
	*x = CreateProjectRequest{}
	mi := &file_nebius_iam_v1_project_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProjectRequest) ProtoMessage() {}

func (x *CreateProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nebius_iam_v1_project_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProjectRequest.ProtoReflect.Descriptor instead.
func (*CreateProjectRequest) Descriptor() ([]byte, []int) {
	return file_nebius_iam_v1_project_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateProjectRequest) GetMetadata() *v1.ResourceMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CreateProjectRequest) GetSpec() *ContainerSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type GetProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectRequest) Reset() {
	*x = GetProjectRequest{}
	mi := &file_nebius_iam_v1_project_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectRequest) ProtoMessage() {}

func (x *GetProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nebius_iam_v1_project_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectRequest.ProtoReflect.Descriptor instead.
func (*GetProjectRequest) Descriptor() ([]byte, []int) {
	return file_nebius_iam_v1_project_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetProjectRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetProjectByNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParentId      string                 `protobuf:"bytes,1,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectByNameRequest) Reset() {
	*x = GetProjectByNameRequest{}
	mi := &file_nebius_iam_v1_project_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectByNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectByNameRequest) ProtoMessage() {}

func (x *GetProjectByNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nebius_iam_v1_project_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectByNameRequest.ProtoReflect.Descriptor instead.
func (*GetProjectByNameRequest) Descriptor() ([]byte, []int) {
	return file_nebius_iam_v1_project_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetProjectByNameRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *GetProjectByNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListProjectsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Represents the container ID.
	ParentId string `protobuf:"bytes,1,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	// Specifies the maximum number of items to return in the response.
	// Default value: 10
	PageSize int64 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Token for pagination, allowing the retrieval of the next set of results.
	PageToken string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// A filter to narrow down the results based on specific criteria.
	Filter        string `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectsRequest) Reset() {
	*x = ListProjectsRequest{}
	mi := &file_nebius_iam_v1_project_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsRequest) ProtoMessage() {}

func (x *ListProjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nebius_iam_v1_project_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsRequest.ProtoReflect.Descriptor instead.
func (*ListProjectsRequest) Descriptor() ([]byte, []int) {
	return file_nebius_iam_v1_project_service_proto_rawDescGZIP(), []int{3}
}

func (x *ListProjectsRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *ListProjectsRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListProjectsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListProjectsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

type UpdateProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *v1.ResourceMetadata   `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Spec          *ContainerSpec         `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProjectRequest) Reset() {
	*x = UpdateProjectRequest{}
	mi := &file_nebius_iam_v1_project_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProjectRequest) ProtoMessage() {}

func (x *UpdateProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nebius_iam_v1_project_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProjectRequest.ProtoReflect.Descriptor instead.
func (*UpdateProjectRequest) Descriptor() ([]byte, []int) {
	return file_nebius_iam_v1_project_service_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateProjectRequest) GetMetadata() *v1.ResourceMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *UpdateProjectRequest) GetSpec() *ContainerSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type ListProjectsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Items []*Container           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	// Token for pagination, indicating the next set of results can be retrieved using this token.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectsResponse) Reset() {
	*x = ListProjectsResponse{}
	mi := &file_nebius_iam_v1_project_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsResponse) ProtoMessage() {}

func (x *ListProjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nebius_iam_v1_project_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsResponse.ProtoReflect.Descriptor instead.
func (*ListProjectsResponse) Descriptor() ([]byte, []int) {
	return file_nebius_iam_v1_project_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListProjectsResponse) GetItems() []*Container {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListProjectsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_nebius_iam_v1_project_service_proto protoreflect.FileDescriptor

const file_nebius_iam_v1_project_service_proto_rawDesc = "" +
	"\n" +
	"#nebius/iam/v1/project_service.proto\x12\rnebius.iam.v1\x1a\x1bbuf/validate/validate.proto\x1a\x18nebius/annotations.proto\x1a\x1fnebius/common/v1/metadata.proto\x1a nebius/common/v1/operation.proto\x1a\x1dnebius/iam/v1/container.proto\"\x88\x01\n" +
	"\x14CreateProjectRequest\x12>\n" +
	"\bmetadata\x18\x01 \x01(\v2\".nebius.common.v1.ResourceMetadataR\bmetadata\x120\n" +
	"\x04spec\x18\x02 \x01(\v2\x1c.nebius.iam.v1.ContainerSpecR\x04spec\"#\n" +
	"\x11GetProjectRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"Z\n" +
	"\x17GetProjectByNameRequest\x12#\n" +
	"\tparent_id\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\bparentId\x12\x1a\n" +
	"\x04name\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x04name\"\x86\x01\n" +
	"\x13ListProjectsRequest\x12\x1b\n" +
	"\tparent_id\x18\x01 \x01(\tR\bparentId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\x12\x16\n" +
	"\x06filter\x18\x04 \x01(\tR\x06filter\"\x88\x01\n" +
	"\x14UpdateProjectRequest\x12>\n" +
	"\bmetadata\x18\x01 \x01(\v2\".nebius.common.v1.ResourceMetadataR\bmetadata\x120\n" +
	"\x04spec\x18\x02 \x01(\v2\x1c.nebius.iam.v1.ContainerSpecR\x04spec\"n\n" +
	"\x14ListProjectsResponse\x12.\n" +
	"\x05items\x18\x01 \x03(\v2\x18.nebius.iam.v1.ContainerR\x05items\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken2\x97\x03\n" +
	"\x0eProjectService\x12J\n" +
	"\x06Create\x12#.nebius.iam.v1.CreateProjectRequest\x1a\x1b.nebius.common.v1.Operation\x12A\n" +
	"\x03Get\x12 .nebius.iam.v1.GetProjectRequest\x1a\x18.nebius.iam.v1.Container\x12M\n" +
	"\tGetByName\x12&.nebius.iam.v1.GetProjectByNameRequest\x1a\x18.nebius.iam.v1.Container\x12O\n" +
	"\x04List\x12\".nebius.iam.v1.ListProjectsRequest\x1a#.nebius.iam.v1.ListProjectsResponse\x12J\n" +
	"\x06Update\x12#.nebius.iam.v1.UpdateProjectRequest\x1a\x1b.nebius.common.v1.Operation\x1a\n" +
	"\xbaJ\acpl.iamBZ\n" +
	"\x14ai.nebius.pub.iam.v1B\x13ProjectServiceProtoP\x01Z+github.com/nebius/gosdk/proto/nebius/iam/v1b\x06proto3"

var (
	file_nebius_iam_v1_project_service_proto_rawDescOnce sync.Once
	file_nebius_iam_v1_project_service_proto_rawDescData []byte
)

func file_nebius_iam_v1_project_service_proto_rawDescGZIP() []byte {
	file_nebius_iam_v1_project_service_proto_rawDescOnce.Do(func() {
		file_nebius_iam_v1_project_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nebius_iam_v1_project_service_proto_rawDesc), len(file_nebius_iam_v1_project_service_proto_rawDesc)))
	})
	return file_nebius_iam_v1_project_service_proto_rawDescData
}

var file_nebius_iam_v1_project_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_nebius_iam_v1_project_service_proto_goTypes = []any{
	(*CreateProjectRequest)(nil),    // 0: nebius.iam.v1.CreateProjectRequest
	(*GetProjectRequest)(nil),       // 1: nebius.iam.v1.GetProjectRequest
	(*GetProjectByNameRequest)(nil), // 2: nebius.iam.v1.GetProjectByNameRequest
	(*ListProjectsRequest)(nil),     // 3: nebius.iam.v1.ListProjectsRequest
	(*UpdateProjectRequest)(nil),    // 4: nebius.iam.v1.UpdateProjectRequest
	(*ListProjectsResponse)(nil),    // 5: nebius.iam.v1.ListProjectsResponse
	(*v1.ResourceMetadata)(nil),     // 6: nebius.common.v1.ResourceMetadata
	(*ContainerSpec)(nil),           // 7: nebius.iam.v1.ContainerSpec
	(*Container)(nil),               // 8: nebius.iam.v1.Container
	(*v1.Operation)(nil),            // 9: nebius.common.v1.Operation
}
var file_nebius_iam_v1_project_service_proto_depIdxs = []int32{
	6,  // 0: nebius.iam.v1.CreateProjectRequest.metadata:type_name -> nebius.common.v1.ResourceMetadata
	7,  // 1: nebius.iam.v1.CreateProjectRequest.spec:type_name -> nebius.iam.v1.ContainerSpec
	6,  // 2: nebius.iam.v1.UpdateProjectRequest.metadata:type_name -> nebius.common.v1.ResourceMetadata
	7,  // 3: nebius.iam.v1.UpdateProjectRequest.spec:type_name -> nebius.iam.v1.ContainerSpec
	8,  // 4: nebius.iam.v1.ListProjectsResponse.items:type_name -> nebius.iam.v1.Container
	0,  // 5: nebius.iam.v1.ProjectService.Create:input_type -> nebius.iam.v1.CreateProjectRequest
	1,  // 6: nebius.iam.v1.ProjectService.Get:input_type -> nebius.iam.v1.GetProjectRequest
	2,  // 7: nebius.iam.v1.ProjectService.GetByName:input_type -> nebius.iam.v1.GetProjectByNameRequest
	3,  // 8: nebius.iam.v1.ProjectService.List:input_type -> nebius.iam.v1.ListProjectsRequest
	4,  // 9: nebius.iam.v1.ProjectService.Update:input_type -> nebius.iam.v1.UpdateProjectRequest
	9,  // 10: nebius.iam.v1.ProjectService.Create:output_type -> nebius.common.v1.Operation
	8,  // 11: nebius.iam.v1.ProjectService.Get:output_type -> nebius.iam.v1.Container
	8,  // 12: nebius.iam.v1.ProjectService.GetByName:output_type -> nebius.iam.v1.Container
	5,  // 13: nebius.iam.v1.ProjectService.List:output_type -> nebius.iam.v1.ListProjectsResponse
	9,  // 14: nebius.iam.v1.ProjectService.Update:output_type -> nebius.common.v1.Operation
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_nebius_iam_v1_project_service_proto_init() }
func file_nebius_iam_v1_project_service_proto_init() {
	if File_nebius_iam_v1_project_service_proto != nil {
		return
	}
	file_nebius_iam_v1_container_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nebius_iam_v1_project_service_proto_rawDesc), len(file_nebius_iam_v1_project_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nebius_iam_v1_project_service_proto_goTypes,
		DependencyIndexes: file_nebius_iam_v1_project_service_proto_depIdxs,
		MessageInfos:      file_nebius_iam_v1_project_service_proto_msgTypes,
	}.Build()
	File_nebius_iam_v1_project_service_proto = out.File
	file_nebius_iam_v1_project_service_proto_goTypes = nil
	file_nebius_iam_v1_project_service_proto_depIdxs = nil
}
