// Code generated by protoc-gen-sensitive. DO NOT EDIT.

package v1

import (
	proto "google.golang.org/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	slog "log/slog"
)

// Sanitize mutates [UserAccountExternalId] to remove/mask all sensitive values.
// Sensitive fields are marked with [(nebius.sensitive) = true].
func (x *UserAccountExternalId) Sanitize() {
	if x == nil {
		return
	}
	x.FederationUserAccountId = "***"
}

// LogValue implements [slog.LogValuer] interface. It returns sanitized copy of [UserAccountExternalId].
// Properly implemented [slog.Handler] must call LogValue, so sensitive values are not logged.
// Sensitive strings and bytes are masked with `***`, other sensitive fields are omitted.
//
// Returning value has kind [slog.KindAny]. To extract [proto.Message], use the following code:
//
//	var original *UserAccountExternalId
//	sanitized := original.LogValue().Any().(proto.Message)
//
// If you need to extract [UserAccountExternalId], use the following code:
//
//	var original *UserAccountExternalId
//	sanitized := original.LogValue().Any().(proto.Message).ProtoReflect().Interface().(*UserAccountExternalId)
func (x *UserAccountExternalId) LogValue() slog.Value {
	if x == nil {
		return slog.AnyValue(x)
	}
	c := proto.Clone(x).(*UserAccountExternalId) // TODO: generate static cloner without protoreflect
	c.Sanitize()
	return slog.AnyValue((*wrapperUserAccountExternalId)(c))
}

// wrapperUserAccountExternalId is used to return [UserAccountExternalId] not implementing [slog.LogValuer] to avoid recursion while resolving.
type wrapperUserAccountExternalId UserAccountExternalId

func (w *wrapperUserAccountExternalId) String() string {
	return (*UserAccountExternalId)(w).String()
}

func (*wrapperUserAccountExternalId) ProtoMessage() {}

func (w *wrapperUserAccountExternalId) ProtoReflect() protoreflect.Message {
	return (*UserAccountExternalId)(w).ProtoReflect()
}
