# This file specifies the exclusions needed for compatibility with older Go versions and dependencies.
# It is merged with the main .golangci.yml file to run the linter using the latest dependencies and go.mod.
linters:
  exclusions:
    rules:
      # patch for latest deps
      - text: 'reflecttypeassert: .* can be simplified using reflect.TypeAssert' # remove after go 1.25+
        linters:
          - modernize
      - text: 'newexpr: call of .* can be simplified to new' # remove after go 1.26+
        linters:
          - modernize
      - text: 'errorsastype: errors.As can be simplified using .*' # remove after go 1.26+
        linters:
          - modernize
