// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.28.3
// source: nebius/capacity/v1/capacity_interval_service.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	CapacityIntervalService_Get_FullMethodName  = "/nebius.capacity.v1.CapacityIntervalService/Get"
	CapacityIntervalService_List_FullMethodName = "/nebius.capacity.v1.CapacityIntervalService/List"
)

// CapacityIntervalServiceClient is the client API for CapacityIntervalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CapacityIntervalServiceClient interface {
	// Get Capacity Interval by its ID.
	Get(ctx context.Context, in *GetCapacityIntervalRequest, opts ...grpc.CallOption) (*CapacityInterval, error)
	// List all capacity intervals in a Capacity Block Group.
	List(ctx context.Context, in *ListCapacityIntervalsRequest, opts ...grpc.CallOption) (*ListCapacityIntervalsResponse, error)
}

type capacityIntervalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCapacityIntervalServiceClient(cc grpc.ClientConnInterface) CapacityIntervalServiceClient {
	return &capacityIntervalServiceClient{cc}
}

func (c *capacityIntervalServiceClient) Get(ctx context.Context, in *GetCapacityIntervalRequest, opts ...grpc.CallOption) (*CapacityInterval, error) {
	out := new(CapacityInterval)
	err := c.cc.Invoke(ctx, CapacityIntervalService_Get_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *capacityIntervalServiceClient) List(ctx context.Context, in *ListCapacityIntervalsRequest, opts ...grpc.CallOption) (*ListCapacityIntervalsResponse, error) {
	out := new(ListCapacityIntervalsResponse)
	err := c.cc.Invoke(ctx, CapacityIntervalService_List_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CapacityIntervalServiceServer is the server API for CapacityIntervalService service.
// All implementations should embed UnimplementedCapacityIntervalServiceServer
// for forward compatibility
type CapacityIntervalServiceServer interface {
	// Get Capacity Interval by its ID.
	Get(context.Context, *GetCapacityIntervalRequest) (*CapacityInterval, error)
	// List all capacity intervals in a Capacity Block Group.
	List(context.Context, *ListCapacityIntervalsRequest) (*ListCapacityIntervalsResponse, error)
}

// UnimplementedCapacityIntervalServiceServer should be embedded to have forward compatible implementations.
type UnimplementedCapacityIntervalServiceServer struct {
}

func (UnimplementedCapacityIntervalServiceServer) Get(context.Context, *GetCapacityIntervalRequest) (*CapacityInterval, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedCapacityIntervalServiceServer) List(context.Context, *ListCapacityIntervalsRequest) (*ListCapacityIntervalsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}

// UnsafeCapacityIntervalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CapacityIntervalServiceServer will
// result in compilation errors.
type UnsafeCapacityIntervalServiceServer interface {
	mustEmbedUnimplementedCapacityIntervalServiceServer()
}

func RegisterCapacityIntervalServiceServer(s grpc.ServiceRegistrar, srv CapacityIntervalServiceServer) {
	s.RegisterService(&CapacityIntervalService_ServiceDesc, srv)
}

func _CapacityIntervalService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCapacityIntervalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CapacityIntervalServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CapacityIntervalService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CapacityIntervalServiceServer).Get(ctx, req.(*GetCapacityIntervalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CapacityIntervalService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCapacityIntervalsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CapacityIntervalServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CapacityIntervalService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CapacityIntervalServiceServer).List(ctx, req.(*ListCapacityIntervalsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CapacityIntervalService_ServiceDesc is the grpc.ServiceDesc for CapacityIntervalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CapacityIntervalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nebius.capacity.v1.CapacityIntervalService",
	HandlerType: (*CapacityIntervalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _CapacityIntervalService_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _CapacityIntervalService_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nebius/capacity/v1/capacity_interval_service.proto",
}
