// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.6
// source: nebius/compute/v1/disk_snapshot.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/nebius/gosdk/proto/nebius"
	v1 "github.com/nebius/gosdk/proto/nebius/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// All possible states for DiskSnapshot resource
type DiskSnapshotStatus_State int32

const (
	DiskSnapshotStatus_UNSPECIFIED DiskSnapshotStatus_State = 0
	DiskSnapshotStatus_CREATING    DiskSnapshotStatus_State = 1
	DiskSnapshotStatus_READY       DiskSnapshotStatus_State = 2
	DiskSnapshotStatus_DELETING    DiskSnapshotStatus_State = 3
	DiskSnapshotStatus_ERROR       DiskSnapshotStatus_State = 4
)

// Enum value maps for DiskSnapshotStatus_State.
var (
	DiskSnapshotStatus_State_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "CREATING",
		2: "READY",
		3: "DELETING",
		4: "ERROR",
	}
	DiskSnapshotStatus_State_value = map[string]int32{
		"UNSPECIFIED": 0,
		"CREATING":    1,
		"READY":       2,
		"DELETING":    3,
		"ERROR":       4,
	}
)

func (x DiskSnapshotStatus_State) Enum() *DiskSnapshotStatus_State {
	p := new(DiskSnapshotStatus_State)
	*p = x
	return p
}

func (x DiskSnapshotStatus_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DiskSnapshotStatus_State) Descriptor() protoreflect.EnumDescriptor {
	return file_nebius_compute_v1_disk_snapshot_proto_enumTypes[0].Descriptor()
}

func (DiskSnapshotStatus_State) Type() protoreflect.EnumType {
	return &file_nebius_compute_v1_disk_snapshot_proto_enumTypes[0]
}

func (x DiskSnapshotStatus_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DiskSnapshotStatus_State.Descriptor instead.
func (DiskSnapshotStatus_State) EnumDescriptor() ([]byte, []int) {
	return file_nebius_compute_v1_disk_snapshot_proto_rawDescGZIP(), []int{2, 0}
}

// Right now UNDEFINED is an alias for AMD64, but that might change in the future
type DiskSnapshotStatus_CPUArchitecture int32

const (
	DiskSnapshotStatus_UNDEFINED DiskSnapshotStatus_CPUArchitecture = 0
	DiskSnapshotStatus_AMD64     DiskSnapshotStatus_CPUArchitecture = 1
	DiskSnapshotStatus_ARM64     DiskSnapshotStatus_CPUArchitecture = 2
)

// Enum value maps for DiskSnapshotStatus_CPUArchitecture.
var (
	DiskSnapshotStatus_CPUArchitecture_name = map[int32]string{
		0: "UNDEFINED",
		1: "AMD64",
		2: "ARM64",
	}
	DiskSnapshotStatus_CPUArchitecture_value = map[string]int32{
		"UNDEFINED": 0,
		"AMD64":     1,
		"ARM64":     2,
	}
)

func (x DiskSnapshotStatus_CPUArchitecture) Enum() *DiskSnapshotStatus_CPUArchitecture {
	p := new(DiskSnapshotStatus_CPUArchitecture)
	*p = x
	return p
}

func (x DiskSnapshotStatus_CPUArchitecture) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DiskSnapshotStatus_CPUArchitecture) Descriptor() protoreflect.EnumDescriptor {
	return file_nebius_compute_v1_disk_snapshot_proto_enumTypes[1].Descriptor()
}

func (DiskSnapshotStatus_CPUArchitecture) Type() protoreflect.EnumType {
	return &file_nebius_compute_v1_disk_snapshot_proto_enumTypes[1]
}

func (x DiskSnapshotStatus_CPUArchitecture) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DiskSnapshotStatus_CPUArchitecture.Descriptor instead.
func (DiskSnapshotStatus_CPUArchitecture) EnumDescriptor() ([]byte, []int) {
	return file_nebius_compute_v1_disk_snapshot_proto_rawDescGZIP(), []int{2, 1}
}

// DiskSnapshot resource
type DiskSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *v1.ResourceMetadata   `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Spec          *DiskSnapshotSpec      `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	Status        *DiskSnapshotStatus    `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskSnapshot) Reset() {
	*x = DiskSnapshot{}
	mi := &file_nebius_compute_v1_disk_snapshot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskSnapshot) ProtoMessage() {}

func (x *DiskSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_nebius_compute_v1_disk_snapshot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskSnapshot.ProtoReflect.Descriptor instead.
func (*DiskSnapshot) Descriptor() ([]byte, []int) {
	return file_nebius_compute_v1_disk_snapshot_proto_rawDescGZIP(), []int{0}
}

func (x *DiskSnapshot) GetMetadata() *v1.ResourceMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *DiskSnapshot) GetSpec() *DiskSnapshotSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *DiskSnapshot) GetStatus() *DiskSnapshotStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type DiskSnapshotSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier of the source disk. May become stale if the disk is deleted.
	SourceDiskId string `protobuf:"bytes,1,opt,name=source_disk_id,json=sourceDiskId,proto3" json:"source_disk_id,omitempty"`
	// Arbitrary information about this snapshot provided by user.
	Description   string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskSnapshotSpec) Reset() {
	*x = DiskSnapshotSpec{}
	mi := &file_nebius_compute_v1_disk_snapshot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskSnapshotSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskSnapshotSpec) ProtoMessage() {}

func (x *DiskSnapshotSpec) ProtoReflect() protoreflect.Message {
	mi := &file_nebius_compute_v1_disk_snapshot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskSnapshotSpec.ProtoReflect.Descriptor instead.
func (*DiskSnapshotSpec) Descriptor() ([]byte, []int) {
	return file_nebius_compute_v1_disk_snapshot_proto_rawDescGZIP(), []int{1}
}

func (x *DiskSnapshotSpec) GetSourceDiskId() string {
	if x != nil {
		return x.SourceDiskId
	}
	return ""
}

func (x *DiskSnapshotSpec) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type DiskSnapshotStatus struct {
	state protoimpl.MessageState   `protogen:"open.v1"`
	State DiskSnapshotStatus_State `protobuf:"varint,1,opt,name=state,proto3,enum=nebius.compute.v1.DiskSnapshotStatus_State" json:"state,omitempty"`
	// Logical size of the snapshot content.
	// This is the size of a disk that would be created from this snapshot.
	ContentSizeBytes int64 `protobuf:"varint,2,opt,name=content_size_bytes,json=contentSizeBytes,proto3" json:"content_size_bytes,omitempty"`
	// Physical storage used by this snapshot in the snapshot backend.
	// This value is used for billing and quota and may change over time as the snapshot chain evolves
	// (e.g., when earlier snapshots are deleted and data gets re-attributed).
	// Currently is equal to content_size_bytes, as incremental snapshots are not supported yet.
	StorageSizeBytes int64 `protobuf:"varint,3,opt,name=storage_size_bytes,json=storageSizeBytes,proto3" json:"storage_size_bytes,omitempty"`
	// Indicates which resources prevent the disk snapshot from being deleted.
	LockState *DiskSnapshotStatus_LockState `protobuf:"bytes,4,opt,name=lock_state,json=lockState,proto3" json:"lock_state,omitempty"`
	// CPU architecture associated with the source disk.
	// Not set if the architecture is unknown.
	SourceCpuArchitecture DiskSnapshotStatus_CPUArchitecture `protobuf:"varint,5,opt,name=source_cpu_architecture,json=sourceCpuArchitecture,proto3,enum=nebius.compute.v1.DiskSnapshotStatus_CPUArchitecture" json:"source_cpu_architecture,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *DiskSnapshotStatus) Reset() {
	*x = DiskSnapshotStatus{}
	mi := &file_nebius_compute_v1_disk_snapshot_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskSnapshotStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskSnapshotStatus) ProtoMessage() {}

func (x *DiskSnapshotStatus) ProtoReflect() protoreflect.Message {
	mi := &file_nebius_compute_v1_disk_snapshot_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskSnapshotStatus.ProtoReflect.Descriptor instead.
func (*DiskSnapshotStatus) Descriptor() ([]byte, []int) {
	return file_nebius_compute_v1_disk_snapshot_proto_rawDescGZIP(), []int{2}
}

func (x *DiskSnapshotStatus) GetState() DiskSnapshotStatus_State {
	if x != nil {
		return x.State
	}
	return DiskSnapshotStatus_UNSPECIFIED
}

func (x *DiskSnapshotStatus) GetContentSizeBytes() int64 {
	if x != nil {
		return x.ContentSizeBytes
	}
	return 0
}

func (x *DiskSnapshotStatus) GetStorageSizeBytes() int64 {
	if x != nil {
		return x.StorageSizeBytes
	}
	return 0
}

func (x *DiskSnapshotStatus) GetLockState() *DiskSnapshotStatus_LockState {
	if x != nil {
		return x.LockState
	}
	return nil
}

func (x *DiskSnapshotStatus) GetSourceCpuArchitecture() DiskSnapshotStatus_CPUArchitecture {
	if x != nil {
		return x.SourceCpuArchitecture
	}
	return DiskSnapshotStatus_UNDEFINED
}

type DiskSnapshotStatus_LockState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The snapshot is locked for deletion while disk is being created from this snapshot.
	// Here is the list of these disks.
	Disks         []string `protobuf:"bytes,1,rep,name=disks,proto3" json:"disks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskSnapshotStatus_LockState) Reset() {
	*x = DiskSnapshotStatus_LockState{}
	mi := &file_nebius_compute_v1_disk_snapshot_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskSnapshotStatus_LockState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskSnapshotStatus_LockState) ProtoMessage() {}

func (x *DiskSnapshotStatus_LockState) ProtoReflect() protoreflect.Message {
	mi := &file_nebius_compute_v1_disk_snapshot_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskSnapshotStatus_LockState.ProtoReflect.Descriptor instead.
func (*DiskSnapshotStatus_LockState) Descriptor() ([]byte, []int) {
	return file_nebius_compute_v1_disk_snapshot_proto_rawDescGZIP(), []int{2, 0}
}

func (x *DiskSnapshotStatus_LockState) GetDisks() []string {
	if x != nil {
		return x.Disks
	}
	return nil
}

var File_nebius_compute_v1_disk_snapshot_proto protoreflect.FileDescriptor

const file_nebius_compute_v1_disk_snapshot_proto_rawDesc = "" +
	"\n" +
	"%nebius/compute/v1/disk_snapshot.proto\x12\x11nebius.compute.v1\x1a\x1bbuf/validate/validate.proto\x1a\x18nebius/annotations.proto\x1a\x1fnebius/common/v1/metadata.proto\"\xc6\x01\n" +
	"\fDiskSnapshot\x12>\n" +
	"\bmetadata\x18\x01 \x01(\v2\".nebius.common.v1.ResourceMetadataR\bmetadata\x127\n" +
	"\x04spec\x18\x02 \x01(\v2#.nebius.compute.v1.DiskSnapshotSpecR\x04spec\x12=\n" +
	"\x06status\x18\x03 \x01(\v2%.nebius.compute.v1.DiskSnapshotStatusR\x06status\"p\n" +
	"\x10DiskSnapshotSpec\x120\n" +
	"\x0esource_disk_id\x18\x01 \x01(\tB\n" +
	"\xbaH\x03\xc8\x01\x01\xbaJ\x01\x02R\fsourceDiskId\x12*\n" +
	"\vdescription\x18\x02 \x01(\tB\b\xbaH\x05r\x03\x18\x80\bR\vdescription\"\x99\x04\n" +
	"\x12DiskSnapshotStatus\x12A\n" +
	"\x05state\x18\x01 \x01(\x0e2+.nebius.compute.v1.DiskSnapshotStatus.StateR\x05state\x12,\n" +
	"\x12content_size_bytes\x18\x02 \x01(\x03R\x10contentSizeBytes\x12,\n" +
	"\x12storage_size_bytes\x18\x03 \x01(\x03R\x10storageSizeBytes\x12N\n" +
	"\n" +
	"lock_state\x18\x04 \x01(\v2/.nebius.compute.v1.DiskSnapshotStatus.LockStateR\tlockState\x12m\n" +
	"\x17source_cpu_architecture\x18\x05 \x01(\x0e25.nebius.compute.v1.DiskSnapshotStatus.CPUArchitectureR\x15sourceCpuArchitecture\x1a!\n" +
	"\tLockState\x12\x14\n" +
	"\x05disks\x18\x01 \x03(\tR\x05disks\"J\n" +
	"\x05State\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\f\n" +
	"\bCREATING\x10\x01\x12\t\n" +
	"\x05READY\x10\x02\x12\f\n" +
	"\bDELETING\x10\x03\x12\t\n" +
	"\x05ERROR\x10\x04\"6\n" +
	"\x0fCPUArchitecture\x12\r\n" +
	"\tUNDEFINED\x10\x00\x12\t\n" +
	"\x05AMD64\x10\x01\x12\t\n" +
	"\x05ARM64\x10\x02B`\n" +
	"\x18ai.nebius.pub.compute.v1B\x11DiskSnapshotProtoP\x01Z/github.com/nebius/gosdk/proto/nebius/compute/v1b\x06proto3"

var (
	file_nebius_compute_v1_disk_snapshot_proto_rawDescOnce sync.Once
	file_nebius_compute_v1_disk_snapshot_proto_rawDescData []byte
)

func file_nebius_compute_v1_disk_snapshot_proto_rawDescGZIP() []byte {
	file_nebius_compute_v1_disk_snapshot_proto_rawDescOnce.Do(func() {
		file_nebius_compute_v1_disk_snapshot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nebius_compute_v1_disk_snapshot_proto_rawDesc), len(file_nebius_compute_v1_disk_snapshot_proto_rawDesc)))
	})
	return file_nebius_compute_v1_disk_snapshot_proto_rawDescData
}

var file_nebius_compute_v1_disk_snapshot_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_nebius_compute_v1_disk_snapshot_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_nebius_compute_v1_disk_snapshot_proto_goTypes = []any{
	(DiskSnapshotStatus_State)(0),           // 0: nebius.compute.v1.DiskSnapshotStatus.State
	(DiskSnapshotStatus_CPUArchitecture)(0), // 1: nebius.compute.v1.DiskSnapshotStatus.CPUArchitecture
	(*DiskSnapshot)(nil),                    // 2: nebius.compute.v1.DiskSnapshot
	(*DiskSnapshotSpec)(nil),                // 3: nebius.compute.v1.DiskSnapshotSpec
	(*DiskSnapshotStatus)(nil),              // 4: nebius.compute.v1.DiskSnapshotStatus
	(*DiskSnapshotStatus_LockState)(nil),    // 5: nebius.compute.v1.DiskSnapshotStatus.LockState
	(*v1.ResourceMetadata)(nil),             // 6: nebius.common.v1.ResourceMetadata
}
var file_nebius_compute_v1_disk_snapshot_proto_depIdxs = []int32{
	6, // 0: nebius.compute.v1.DiskSnapshot.metadata:type_name -> nebius.common.v1.ResourceMetadata
	3, // 1: nebius.compute.v1.DiskSnapshot.spec:type_name -> nebius.compute.v1.DiskSnapshotSpec
	4, // 2: nebius.compute.v1.DiskSnapshot.status:type_name -> nebius.compute.v1.DiskSnapshotStatus
	0, // 3: nebius.compute.v1.DiskSnapshotStatus.state:type_name -> nebius.compute.v1.DiskSnapshotStatus.State
	5, // 4: nebius.compute.v1.DiskSnapshotStatus.lock_state:type_name -> nebius.compute.v1.DiskSnapshotStatus.LockState
	1, // 5: nebius.compute.v1.DiskSnapshotStatus.source_cpu_architecture:type_name -> nebius.compute.v1.DiskSnapshotStatus.CPUArchitecture
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_nebius_compute_v1_disk_snapshot_proto_init() }
func file_nebius_compute_v1_disk_snapshot_proto_init() {
	if File_nebius_compute_v1_disk_snapshot_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nebius_compute_v1_disk_snapshot_proto_rawDesc), len(file_nebius_compute_v1_disk_snapshot_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nebius_compute_v1_disk_snapshot_proto_goTypes,
		DependencyIndexes: file_nebius_compute_v1_disk_snapshot_proto_depIdxs,
		EnumInfos:         file_nebius_compute_v1_disk_snapshot_proto_enumTypes,
		MessageInfos:      file_nebius_compute_v1_disk_snapshot_proto_msgTypes,
	}.Build()
	File_nebius_compute_v1_disk_snapshot_proto = out.File
	file_nebius_compute_v1_disk_snapshot_proto_goTypes = nil
	file_nebius_compute_v1_disk_snapshot_proto_depIdxs = nil
}
