// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.3
// source: nebius/compute/v1/filesystem_service.proto

package v1

import (
	_ "github.com/nebius/gosdk/proto/nebius"
	v1 "github.com/nebius/gosdk/proto/nebius/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetFilesystemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFilesystemRequest) Reset() {
	*x = GetFilesystemRequest{}
	mi := &file_nebius_compute_v1_filesystem_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFilesystemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFilesystemRequest) ProtoMessage() {}

func (x *GetFilesystemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nebius_compute_v1_filesystem_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFilesystemRequest.ProtoReflect.Descriptor instead.
func (*GetFilesystemRequest) Descriptor() ([]byte, []int) {
	return file_nebius_compute_v1_filesystem_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetFilesystemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListFilesystemsRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ParentId  string                 `protobuf:"bytes,1,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	PageSize  int64                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Deprecated: Marked as deprecated in nebius/compute/v1/filesystem_service.proto.
	Filter        string `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesystemsRequest) Reset() {
	*x = ListFilesystemsRequest{}
	mi := &file_nebius_compute_v1_filesystem_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesystemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesystemsRequest) ProtoMessage() {}

func (x *ListFilesystemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nebius_compute_v1_filesystem_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesystemsRequest.ProtoReflect.Descriptor instead.
func (*ListFilesystemsRequest) Descriptor() ([]byte, []int) {
	return file_nebius_compute_v1_filesystem_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListFilesystemsRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *ListFilesystemsRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListFilesystemsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// Deprecated: Marked as deprecated in nebius/compute/v1/filesystem_service.proto.
func (x *ListFilesystemsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

type CreateFilesystemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *v1.ResourceMetadata   `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Spec          *FilesystemSpec        `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFilesystemRequest) Reset() {
	*x = CreateFilesystemRequest{}
	mi := &file_nebius_compute_v1_filesystem_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFilesystemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFilesystemRequest) ProtoMessage() {}

func (x *CreateFilesystemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nebius_compute_v1_filesystem_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFilesystemRequest.ProtoReflect.Descriptor instead.
func (*CreateFilesystemRequest) Descriptor() ([]byte, []int) {
	return file_nebius_compute_v1_filesystem_service_proto_rawDescGZIP(), []int{2}
}

func (x *CreateFilesystemRequest) GetMetadata() *v1.ResourceMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CreateFilesystemRequest) GetSpec() *FilesystemSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type UpdateFilesystemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *v1.ResourceMetadata   `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Spec          *FilesystemSpec        `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFilesystemRequest) Reset() {
	*x = UpdateFilesystemRequest{}
	mi := &file_nebius_compute_v1_filesystem_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFilesystemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFilesystemRequest) ProtoMessage() {}

func (x *UpdateFilesystemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nebius_compute_v1_filesystem_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFilesystemRequest.ProtoReflect.Descriptor instead.
func (*UpdateFilesystemRequest) Descriptor() ([]byte, []int) {
	return file_nebius_compute_v1_filesystem_service_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateFilesystemRequest) GetMetadata() *v1.ResourceMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *UpdateFilesystemRequest) GetSpec() *FilesystemSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type DeleteFilesystemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFilesystemRequest) Reset() {
	*x = DeleteFilesystemRequest{}
	mi := &file_nebius_compute_v1_filesystem_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFilesystemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFilesystemRequest) ProtoMessage() {}

func (x *DeleteFilesystemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nebius_compute_v1_filesystem_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFilesystemRequest.ProtoReflect.Descriptor instead.
func (*DeleteFilesystemRequest) Descriptor() ([]byte, []int) {
	return file_nebius_compute_v1_filesystem_service_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteFilesystemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListFilesystemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Filesystem          `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesystemsResponse) Reset() {
	*x = ListFilesystemsResponse{}
	mi := &file_nebius_compute_v1_filesystem_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesystemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesystemsResponse) ProtoMessage() {}

func (x *ListFilesystemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nebius_compute_v1_filesystem_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesystemsResponse.ProtoReflect.Descriptor instead.
func (*ListFilesystemsResponse) Descriptor() ([]byte, []int) {
	return file_nebius_compute_v1_filesystem_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListFilesystemsResponse) GetItems() []*Filesystem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListFilesystemsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_nebius_compute_v1_filesystem_service_proto protoreflect.FileDescriptor

const file_nebius_compute_v1_filesystem_service_proto_rawDesc = "" +
	"\n" +
	"*nebius/compute/v1/filesystem_service.proto\x12\x11nebius.compute.v1\x1a\x18nebius/annotations.proto\x1a\x1fnebius/common/v1/metadata.proto\x1a nebius/common/v1/operation.proto\x1a(nebius/common/v1/operation_service.proto\x1a\"nebius/compute/v1/filesystem.proto\x1a)nebius/compute/v1/operation_service.proto\"&\n" +
	"\x14GetFilesystemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xdb\x01\n" +
	"\x16ListFilesystemsRequest\x12\x1b\n" +
	"\tparent_id\x18\x01 \x01(\tR\bparentId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\x12h\n" +
	"\x06filter\x18\x04 \x01(\tBP\xd2JK\n" +
	"\n" +
	"2025-06-16\x12=it is not implemented, filtering could be done on client side\x18\x01R\x06filter\"\x90\x01\n" +
	"\x17CreateFilesystemRequest\x12>\n" +
	"\bmetadata\x18\x01 \x01(\v2\".nebius.common.v1.ResourceMetadataR\bmetadata\x125\n" +
	"\x04spec\x18\x02 \x01(\v2!.nebius.compute.v1.FilesystemSpecR\x04spec\"\x90\x01\n" +
	"\x17UpdateFilesystemRequest\x12>\n" +
	"\bmetadata\x18\x01 \x01(\v2\".nebius.common.v1.ResourceMetadataR\bmetadata\x125\n" +
	"\x04spec\x18\x02 \x01(\v2!.nebius.compute.v1.FilesystemSpecR\x04spec\")\n" +
	"\x17DeleteFilesystemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"v\n" +
	"\x17ListFilesystemsResponse\x123\n" +
	"\x05items\x18\x01 \x03(\v2\x1d.nebius.compute.v1.FilesystemR\x05items\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken2\x8c\x05\n" +
	"\x11FilesystemService\x12M\n" +
	"\x03Get\x12'.nebius.compute.v1.GetFilesystemRequest\x1a\x1d.nebius.compute.v1.Filesystem\x12N\n" +
	"\tGetByName\x12\".nebius.common.v1.GetByNameRequest\x1a\x1d.nebius.compute.v1.Filesystem\x12]\n" +
	"\x04List\x12).nebius.compute.v1.ListFilesystemsRequest\x1a*.nebius.compute.v1.ListFilesystemsResponse\x12Q\n" +
	"\x06Create\x12*.nebius.compute.v1.CreateFilesystemRequest\x1a\x1b.nebius.common.v1.Operation\x12Q\n" +
	"\x06Update\x12*.nebius.compute.v1.UpdateFilesystemRequest\x1a\x1b.nebius.common.v1.Operation\x12Q\n" +
	"\x06Delete\x12*.nebius.compute.v1.DeleteFilesystemRequest\x1a\x1b.nebius.common.v1.Operation\x12t\n" +
	"\x16ListOperationsByParent\x120.nebius.compute.v1.ListOperationsByParentRequest\x1a(.nebius.common.v1.ListOperationsResponse\x1a\n" +
	"\xbaJ\acomputeBe\n" +
	"\x18ai.nebius.pub.compute.v1B\x16FilesystemServiceProtoP\x01Z/github.com/nebius/gosdk/proto/nebius/compute/v1b\x06proto3"

var (
	file_nebius_compute_v1_filesystem_service_proto_rawDescOnce sync.Once
	file_nebius_compute_v1_filesystem_service_proto_rawDescData []byte
)

func file_nebius_compute_v1_filesystem_service_proto_rawDescGZIP() []byte {
	file_nebius_compute_v1_filesystem_service_proto_rawDescOnce.Do(func() {
		file_nebius_compute_v1_filesystem_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nebius_compute_v1_filesystem_service_proto_rawDesc), len(file_nebius_compute_v1_filesystem_service_proto_rawDesc)))
	})
	return file_nebius_compute_v1_filesystem_service_proto_rawDescData
}

var file_nebius_compute_v1_filesystem_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_nebius_compute_v1_filesystem_service_proto_goTypes = []any{
	(*GetFilesystemRequest)(nil),          // 0: nebius.compute.v1.GetFilesystemRequest
	(*ListFilesystemsRequest)(nil),        // 1: nebius.compute.v1.ListFilesystemsRequest
	(*CreateFilesystemRequest)(nil),       // 2: nebius.compute.v1.CreateFilesystemRequest
	(*UpdateFilesystemRequest)(nil),       // 3: nebius.compute.v1.UpdateFilesystemRequest
	(*DeleteFilesystemRequest)(nil),       // 4: nebius.compute.v1.DeleteFilesystemRequest
	(*ListFilesystemsResponse)(nil),       // 5: nebius.compute.v1.ListFilesystemsResponse
	(*v1.ResourceMetadata)(nil),           // 6: nebius.common.v1.ResourceMetadata
	(*FilesystemSpec)(nil),                // 7: nebius.compute.v1.FilesystemSpec
	(*Filesystem)(nil),                    // 8: nebius.compute.v1.Filesystem
	(*v1.GetByNameRequest)(nil),           // 9: nebius.common.v1.GetByNameRequest
	(*ListOperationsByParentRequest)(nil), // 10: nebius.compute.v1.ListOperationsByParentRequest
	(*v1.Operation)(nil),                  // 11: nebius.common.v1.Operation
	(*v1.ListOperationsResponse)(nil),     // 12: nebius.common.v1.ListOperationsResponse
}
var file_nebius_compute_v1_filesystem_service_proto_depIdxs = []int32{
	6,  // 0: nebius.compute.v1.CreateFilesystemRequest.metadata:type_name -> nebius.common.v1.ResourceMetadata
	7,  // 1: nebius.compute.v1.CreateFilesystemRequest.spec:type_name -> nebius.compute.v1.FilesystemSpec
	6,  // 2: nebius.compute.v1.UpdateFilesystemRequest.metadata:type_name -> nebius.common.v1.ResourceMetadata
	7,  // 3: nebius.compute.v1.UpdateFilesystemRequest.spec:type_name -> nebius.compute.v1.FilesystemSpec
	8,  // 4: nebius.compute.v1.ListFilesystemsResponse.items:type_name -> nebius.compute.v1.Filesystem
	0,  // 5: nebius.compute.v1.FilesystemService.Get:input_type -> nebius.compute.v1.GetFilesystemRequest
	9,  // 6: nebius.compute.v1.FilesystemService.GetByName:input_type -> nebius.common.v1.GetByNameRequest
	1,  // 7: nebius.compute.v1.FilesystemService.List:input_type -> nebius.compute.v1.ListFilesystemsRequest
	2,  // 8: nebius.compute.v1.FilesystemService.Create:input_type -> nebius.compute.v1.CreateFilesystemRequest
	3,  // 9: nebius.compute.v1.FilesystemService.Update:input_type -> nebius.compute.v1.UpdateFilesystemRequest
	4,  // 10: nebius.compute.v1.FilesystemService.Delete:input_type -> nebius.compute.v1.DeleteFilesystemRequest
	10, // 11: nebius.compute.v1.FilesystemService.ListOperationsByParent:input_type -> nebius.compute.v1.ListOperationsByParentRequest
	8,  // 12: nebius.compute.v1.FilesystemService.Get:output_type -> nebius.compute.v1.Filesystem
	8,  // 13: nebius.compute.v1.FilesystemService.GetByName:output_type -> nebius.compute.v1.Filesystem
	5,  // 14: nebius.compute.v1.FilesystemService.List:output_type -> nebius.compute.v1.ListFilesystemsResponse
	11, // 15: nebius.compute.v1.FilesystemService.Create:output_type -> nebius.common.v1.Operation
	11, // 16: nebius.compute.v1.FilesystemService.Update:output_type -> nebius.common.v1.Operation
	11, // 17: nebius.compute.v1.FilesystemService.Delete:output_type -> nebius.common.v1.Operation
	12, // 18: nebius.compute.v1.FilesystemService.ListOperationsByParent:output_type -> nebius.common.v1.ListOperationsResponse
	12, // [12:19] is the sub-list for method output_type
	5,  // [5:12] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_nebius_compute_v1_filesystem_service_proto_init() }
func file_nebius_compute_v1_filesystem_service_proto_init() {
	if File_nebius_compute_v1_filesystem_service_proto != nil {
		return
	}
	file_nebius_compute_v1_filesystem_proto_init()
	file_nebius_compute_v1_operation_service_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nebius_compute_v1_filesystem_service_proto_rawDesc), len(file_nebius_compute_v1_filesystem_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nebius_compute_v1_filesystem_service_proto_goTypes,
		DependencyIndexes: file_nebius_compute_v1_filesystem_service_proto_depIdxs,
		MessageInfos:      file_nebius_compute_v1_filesystem_service_proto_msgTypes,
	}.Build()
	File_nebius_compute_v1_filesystem_service_proto = out.File
	file_nebius_compute_v1_filesystem_service_proto_goTypes = nil
	file_nebius_compute_v1_filesystem_service_proto_depIdxs = nil
}
