// Code generated by protoc-gen-sensitive. DO NOT EDIT.

package v1

// func (x *MaintenanceEvent) Sanitize()            // is not generated as no sensitive fields found
// func (x *MaintenanceEvent) LogValue() slog.Value // is not generated as no sensitive fields found

// func (x *MaintenanceEventSpec) Sanitize()            // is not generated as no sensitive fields found
// func (x *MaintenanceEventSpec) LogValue() slog.Value // is not generated as no sensitive fields found

// func (x *MaintenanceEventStatus) Sanitize()            // is not generated as no sensitive fields found
// func (x *MaintenanceEventStatus) LogValue() slog.Value // is not generated as no sensitive fields found
