// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: nebius/compute/v1/nvlinstancegroup_service.proto

package v1

import (
	_ "github.com/nebius/gosdk/proto/nebius"
	v1 "github.com/nebius/gosdk/proto/nebius/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateNVLInstanceGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *v1.ResourceMetadata   `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Spec          *NVLInstanceGroupSpec  `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNVLInstanceGroupRequest) Reset() {
	*x = CreateNVLInstanceGroupRequest{}
	mi := &file_nebius_compute_v1_nvlinstancegroup_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNVLInstanceGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNVLInstanceGroupRequest) ProtoMessage() {}

func (x *CreateNVLInstanceGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nebius_compute_v1_nvlinstancegroup_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNVLInstanceGroupRequest.ProtoReflect.Descriptor instead.
func (*CreateNVLInstanceGroupRequest) Descriptor() ([]byte, []int) {
	return file_nebius_compute_v1_nvlinstancegroup_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateNVLInstanceGroupRequest) GetMetadata() *v1.ResourceMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CreateNVLInstanceGroupRequest) GetSpec() *NVLInstanceGroupSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type UpdateNVLInstanceGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *v1.ResourceMetadata   `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Spec          *NVLInstanceGroupSpec  `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNVLInstanceGroupRequest) Reset() {
	*x = UpdateNVLInstanceGroupRequest{}
	mi := &file_nebius_compute_v1_nvlinstancegroup_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNVLInstanceGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNVLInstanceGroupRequest) ProtoMessage() {}

func (x *UpdateNVLInstanceGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nebius_compute_v1_nvlinstancegroup_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNVLInstanceGroupRequest.ProtoReflect.Descriptor instead.
func (*UpdateNVLInstanceGroupRequest) Descriptor() ([]byte, []int) {
	return file_nebius_compute_v1_nvlinstancegroup_service_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateNVLInstanceGroupRequest) GetMetadata() *v1.ResourceMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *UpdateNVLInstanceGroupRequest) GetSpec() *NVLInstanceGroupSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type GetNVLInstanceGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNVLInstanceGroupRequest) Reset() {
	*x = GetNVLInstanceGroupRequest{}
	mi := &file_nebius_compute_v1_nvlinstancegroup_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNVLInstanceGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNVLInstanceGroupRequest) ProtoMessage() {}

func (x *GetNVLInstanceGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nebius_compute_v1_nvlinstancegroup_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNVLInstanceGroupRequest.ProtoReflect.Descriptor instead.
func (*GetNVLInstanceGroupRequest) Descriptor() ([]byte, []int) {
	return file_nebius_compute_v1_nvlinstancegroup_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetNVLInstanceGroupRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListNVLInstanceGroupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParentId      string                 `protobuf:"bytes,1,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	PageSize      int64                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNVLInstanceGroupsRequest) Reset() {
	*x = ListNVLInstanceGroupsRequest{}
	mi := &file_nebius_compute_v1_nvlinstancegroup_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNVLInstanceGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNVLInstanceGroupsRequest) ProtoMessage() {}

func (x *ListNVLInstanceGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nebius_compute_v1_nvlinstancegroup_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNVLInstanceGroupsRequest.ProtoReflect.Descriptor instead.
func (*ListNVLInstanceGroupsRequest) Descriptor() ([]byte, []int) {
	return file_nebius_compute_v1_nvlinstancegroup_service_proto_rawDescGZIP(), []int{3}
}

func (x *ListNVLInstanceGroupsRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *ListNVLInstanceGroupsRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListNVLInstanceGroupsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListNVLInstanceGroupsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*NVLInstanceGroup    `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNVLInstanceGroupsResponse) Reset() {
	*x = ListNVLInstanceGroupsResponse{}
	mi := &file_nebius_compute_v1_nvlinstancegroup_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNVLInstanceGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNVLInstanceGroupsResponse) ProtoMessage() {}

func (x *ListNVLInstanceGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nebius_compute_v1_nvlinstancegroup_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNVLInstanceGroupsResponse.ProtoReflect.Descriptor instead.
func (*ListNVLInstanceGroupsResponse) Descriptor() ([]byte, []int) {
	return file_nebius_compute_v1_nvlinstancegroup_service_proto_rawDescGZIP(), []int{4}
}

func (x *ListNVLInstanceGroupsResponse) GetItems() []*NVLInstanceGroup {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListNVLInstanceGroupsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type DeleteNVLInstanceGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNVLInstanceGroupRequest) Reset() {
	*x = DeleteNVLInstanceGroupRequest{}
	mi := &file_nebius_compute_v1_nvlinstancegroup_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNVLInstanceGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNVLInstanceGroupRequest) ProtoMessage() {}

func (x *DeleteNVLInstanceGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nebius_compute_v1_nvlinstancegroup_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNVLInstanceGroupRequest.ProtoReflect.Descriptor instead.
func (*DeleteNVLInstanceGroupRequest) Descriptor() ([]byte, []int) {
	return file_nebius_compute_v1_nvlinstancegroup_service_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteNVLInstanceGroupRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_nebius_compute_v1_nvlinstancegroup_service_proto protoreflect.FileDescriptor

const file_nebius_compute_v1_nvlinstancegroup_service_proto_rawDesc = "" +
	"\n" +
	"0nebius/compute/v1/nvlinstancegroup_service.proto\x12\x11nebius.compute.v1\x1a\x18nebius/annotations.proto\x1a\x1fnebius/common/v1/metadata.proto\x1a nebius/common/v1/operation.proto\x1a(nebius/compute/v1/nvlinstancegroup.proto\"\x9c\x01\n" +
	"\x1dCreateNVLInstanceGroupRequest\x12>\n" +
	"\bmetadata\x18\x01 \x01(\v2\".nebius.common.v1.ResourceMetadataR\bmetadata\x12;\n" +
	"\x04spec\x18\x02 \x01(\v2'.nebius.compute.v1.NVLInstanceGroupSpecR\x04spec\"\x9c\x01\n" +
	"\x1dUpdateNVLInstanceGroupRequest\x12>\n" +
	"\bmetadata\x18\x01 \x01(\v2\".nebius.common.v1.ResourceMetadataR\bmetadata\x12;\n" +
	"\x04spec\x18\x02 \x01(\v2'.nebius.compute.v1.NVLInstanceGroupSpecR\x04spec\",\n" +
	"\x1aGetNVLInstanceGroupRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"w\n" +
	"\x1cListNVLInstanceGroupsRequest\x12\x1b\n" +
	"\tparent_id\x18\x01 \x01(\tR\bparentId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"\x82\x01\n" +
	"\x1dListNVLInstanceGroupsResponse\x129\n" +
	"\x05items\x18\x01 \x03(\v2#.nebius.compute.v1.NVLInstanceGroupR\x05items\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"/\n" +
	"\x1dDeleteNVLInstanceGroupRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2\xcc\x04\n" +
	"\x17NVLInstanceGroupService\x12W\n" +
	"\x06Create\x120.nebius.compute.v1.CreateNVLInstanceGroupRequest\x1a\x1b.nebius.common.v1.Operation\x12Y\n" +
	"\x03Get\x12-.nebius.compute.v1.GetNVLInstanceGroupRequest\x1a#.nebius.compute.v1.NVLInstanceGroup\x12T\n" +
	"\tGetByName\x12\".nebius.common.v1.GetByNameRequest\x1a#.nebius.compute.v1.NVLInstanceGroup\x12i\n" +
	"\x04List\x12/.nebius.compute.v1.ListNVLInstanceGroupsRequest\x1a0.nebius.compute.v1.ListNVLInstanceGroupsResponse\x12W\n" +
	"\x06Update\x120.nebius.compute.v1.UpdateNVLInstanceGroupRequest\x1a\x1b.nebius.common.v1.Operation\x12W\n" +
	"\x06Delete\x120.nebius.compute.v1.DeleteNVLInstanceGroupRequest\x1a\x1b.nebius.common.v1.Operation\x1a\n" +
	"\xbaJ\acomputeBk\n" +
	"\x18ai.nebius.pub.compute.v1B\x1cNvlinstancegroupServiceProtoP\x01Z/github.com/nebius/gosdk/proto/nebius/compute/v1b\x06proto3"

var (
	file_nebius_compute_v1_nvlinstancegroup_service_proto_rawDescOnce sync.Once
	file_nebius_compute_v1_nvlinstancegroup_service_proto_rawDescData []byte
)

func file_nebius_compute_v1_nvlinstancegroup_service_proto_rawDescGZIP() []byte {
	file_nebius_compute_v1_nvlinstancegroup_service_proto_rawDescOnce.Do(func() {
		file_nebius_compute_v1_nvlinstancegroup_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nebius_compute_v1_nvlinstancegroup_service_proto_rawDesc), len(file_nebius_compute_v1_nvlinstancegroup_service_proto_rawDesc)))
	})
	return file_nebius_compute_v1_nvlinstancegroup_service_proto_rawDescData
}

var file_nebius_compute_v1_nvlinstancegroup_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_nebius_compute_v1_nvlinstancegroup_service_proto_goTypes = []any{
	(*CreateNVLInstanceGroupRequest)(nil), // 0: nebius.compute.v1.CreateNVLInstanceGroupRequest
	(*UpdateNVLInstanceGroupRequest)(nil), // 1: nebius.compute.v1.UpdateNVLInstanceGroupRequest
	(*GetNVLInstanceGroupRequest)(nil),    // 2: nebius.compute.v1.GetNVLInstanceGroupRequest
	(*ListNVLInstanceGroupsRequest)(nil),  // 3: nebius.compute.v1.ListNVLInstanceGroupsRequest
	(*ListNVLInstanceGroupsResponse)(nil), // 4: nebius.compute.v1.ListNVLInstanceGroupsResponse
	(*DeleteNVLInstanceGroupRequest)(nil), // 5: nebius.compute.v1.DeleteNVLInstanceGroupRequest
	(*v1.ResourceMetadata)(nil),           // 6: nebius.common.v1.ResourceMetadata
	(*NVLInstanceGroupSpec)(nil),          // 7: nebius.compute.v1.NVLInstanceGroupSpec
	(*NVLInstanceGroup)(nil),              // 8: nebius.compute.v1.NVLInstanceGroup
	(*v1.GetByNameRequest)(nil),           // 9: nebius.common.v1.GetByNameRequest
	(*v1.Operation)(nil),                  // 10: nebius.common.v1.Operation
}
var file_nebius_compute_v1_nvlinstancegroup_service_proto_depIdxs = []int32{
	6,  // 0: nebius.compute.v1.CreateNVLInstanceGroupRequest.metadata:type_name -> nebius.common.v1.ResourceMetadata
	7,  // 1: nebius.compute.v1.CreateNVLInstanceGroupRequest.spec:type_name -> nebius.compute.v1.NVLInstanceGroupSpec
	6,  // 2: nebius.compute.v1.UpdateNVLInstanceGroupRequest.metadata:type_name -> nebius.common.v1.ResourceMetadata
	7,  // 3: nebius.compute.v1.UpdateNVLInstanceGroupRequest.spec:type_name -> nebius.compute.v1.NVLInstanceGroupSpec
	8,  // 4: nebius.compute.v1.ListNVLInstanceGroupsResponse.items:type_name -> nebius.compute.v1.NVLInstanceGroup
	0,  // 5: nebius.compute.v1.NVLInstanceGroupService.Create:input_type -> nebius.compute.v1.CreateNVLInstanceGroupRequest
	2,  // 6: nebius.compute.v1.NVLInstanceGroupService.Get:input_type -> nebius.compute.v1.GetNVLInstanceGroupRequest
	9,  // 7: nebius.compute.v1.NVLInstanceGroupService.GetByName:input_type -> nebius.common.v1.GetByNameRequest
	3,  // 8: nebius.compute.v1.NVLInstanceGroupService.List:input_type -> nebius.compute.v1.ListNVLInstanceGroupsRequest
	1,  // 9: nebius.compute.v1.NVLInstanceGroupService.Update:input_type -> nebius.compute.v1.UpdateNVLInstanceGroupRequest
	5,  // 10: nebius.compute.v1.NVLInstanceGroupService.Delete:input_type -> nebius.compute.v1.DeleteNVLInstanceGroupRequest
	10, // 11: nebius.compute.v1.NVLInstanceGroupService.Create:output_type -> nebius.common.v1.Operation
	8,  // 12: nebius.compute.v1.NVLInstanceGroupService.Get:output_type -> nebius.compute.v1.NVLInstanceGroup
	8,  // 13: nebius.compute.v1.NVLInstanceGroupService.GetByName:output_type -> nebius.compute.v1.NVLInstanceGroup
	4,  // 14: nebius.compute.v1.NVLInstanceGroupService.List:output_type -> nebius.compute.v1.ListNVLInstanceGroupsResponse
	10, // 15: nebius.compute.v1.NVLInstanceGroupService.Update:output_type -> nebius.common.v1.Operation
	10, // 16: nebius.compute.v1.NVLInstanceGroupService.Delete:output_type -> nebius.common.v1.Operation
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_nebius_compute_v1_nvlinstancegroup_service_proto_init() }
func file_nebius_compute_v1_nvlinstancegroup_service_proto_init() {
	if File_nebius_compute_v1_nvlinstancegroup_service_proto != nil {
		return
	}
	file_nebius_compute_v1_nvlinstancegroup_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nebius_compute_v1_nvlinstancegroup_service_proto_rawDesc), len(file_nebius_compute_v1_nvlinstancegroup_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nebius_compute_v1_nvlinstancegroup_service_proto_goTypes,
		DependencyIndexes: file_nebius_compute_v1_nvlinstancegroup_service_proto_depIdxs,
		MessageInfos:      file_nebius_compute_v1_nvlinstancegroup_service_proto_msgTypes,
	}.Build()
	File_nebius_compute_v1_nvlinstancegroup_service_proto = out.File
	file_nebius_compute_v1_nvlinstancegroup_service_proto_goTypes = nil
	file_nebius_compute_v1_nvlinstancegroup_service_proto_depIdxs = nil
}
