// Code generated by protoc-gen-sensitive. DO NOT EDIT.

package v1

// func (x *CreateNVLInstanceGroupRequest) Sanitize()            // is not generated as no sensitive fields found
// func (x *CreateNVLInstanceGroupRequest) LogValue() slog.Value // is not generated as no sensitive fields found

// func (x *GetNVLInstanceGroupRequest) Sanitize()            // is not generated as no sensitive fields found
// func (x *GetNVLInstanceGroupRequest) LogValue() slog.Value // is not generated as no sensitive fields found

// func (x *ListNVLInstanceGroupsRequest) Sanitize()            // is not generated as no sensitive fields found
// func (x *ListNVLInstanceGroupsRequest) LogValue() slog.Value // is not generated as no sensitive fields found

// func (x *ListNVLInstanceGroupsResponse) Sanitize()            // is not generated as no sensitive fields found
// func (x *ListNVLInstanceGroupsResponse) LogValue() slog.Value // is not generated as no sensitive fields found

// func (x *DeleteNVLInstanceGroupRequest) Sanitize()            // is not generated as no sensitive fields found
// func (x *DeleteNVLInstanceGroupRequest) LogValue() slog.Value // is not generated as no sensitive fields found
