// Code generated by protoc-gen-sensitive. DO NOT EDIT.

package v1

// func (x *Artifact) Sanitize()            // is not generated as no sensitive fields found
// func (x *Artifact) LogValue() slog.Value // is not generated as no sensitive fields found
